In [45]:
PROCESSED_FILE_DIR = "/home/shoaib/recommender-system/royal/journal-revision/New/FH/processed-files"
DATA_FILE_DIR = "/home/shoaib/recommender-system/royal/journal-revision/New/FH/data"

In [46]:
import numpy as np
import pandas as pd
from itertools import product
from collections import defaultdict
import pickle
from lenskit import topn

In [47]:
train=pd.read_csv(f"{DATA_FILE_DIR}/train_ratings.csv").iloc[:,[1,2,3]]

In [48]:
train

        user  item  ratings
0          0   624      1.0
1          0   484      1.5
2          0   466      1.5
3          0   377      1.5
4          0   371      1.5
...      ...   ...      ...
114715  5405    19      1.5
114716  5405     4      1.5
114717  5405   114      1.5
114718  5406     2      1.5
114719  5406   571      1.5

[114720 rows x 3 columns]

In [49]:
train.drop_duplicates(subset=['user', 'item'], inplace=True)

In [50]:
user_item_sets = train.groupby('user')['item'].apply(set).to_dict()

In [51]:
user_item_sets

{0: {160, 193, 241, 248, 261, 266, 336, 371, 377, 466, 484, 624},
 1: {77, 79, 106, 138, 174, 195, 229, 302, 319, 338, 378},
 2: {787, 791, 795, 798, 801, 805, 807, 813, 816, 822, 824},
 3: {261,
  351,
  391,
  503,
  527,
  533,
  600,
  624,
  646,
  657,
  659,
  669,
  695,
  724,
  739,
  1012,
  1024,
  1028,
  1092,
  1104,
  1142,
  1324,
  1334,
  1400,
  1450,
  1515,
  1562,
  1604,
  1635,
  1667},
 4: {163, 165, 204, 262, 264, 374, 443, 692},
 5: {440,
  600,
  604,
  616,
  624,
  646,
  657,
  695,
  859,
  983,
  1028,
  1102,
  1128,
  1154,
  1293,
  1300,
  1310,
  1334,
  1360,
  1370,
  1377,
  1382,
  1400,
  1419,
  1444,
  1449,
  1450,
  1494,
  1515,
  1519,
  1562,
  1659,
  1679},
 6: {64, 90, 381, 434, 889, 1061, 1283, 1327, 1363, 1432, 1524},
 7: {657, 1012, 1024, 1114, 1300, 1304, 1543, 1552, 1604},
 8: {351,
  495,
  527,
  584,
  600,
  604,
  616,
  631,
  646,
  1028,
  1092,
  1104,
  1206,
  1284,
  1304,
  1318,
  1334,
  1377,
  1400,
  1515,
  1562,
  1619},
 9: {148,
  160,
  171,
  241,
  261,
  266,
  286,
  314,
  332,
  391,
  503,
  504,
  523,
  533,
  539,
  561,
  584,
  600,
  604,
  616,
  625,
  628,
  631,
  643,
  646,
  657,
  659,
  669,
  695,
  714,
  724,
  731,
  739,
  774,
  806,
  827,
  859,
  983,
  1012,
  1013,
  1024,
  1028,
  1092,
  1102,
  1104,
  1114,
  1128,
  1142,
  1154,
  1206,
  1272,
  1284,
  1293,
  1300,
  1304,
  1310,
  1318,
  1324,
  1334,
  1338,
  1360,
  1370,
  1377,
  1382,
  1400,
  1408,
  1419,
  1421,
  1444,
  1449,
  1450,
  1467,
  1494,
  1515,
  1519,
  1543,
  1552,
  1562,
  1604,
  1619,
  1635,
  1636,
  1659,
  1667,
  1679},
 10: {58,
  82,
  116,
  134,
  145,
  155,
  179,
  207,
  219,
  234,
  265,
  329,
  349,
  402,
  407,
  507,
  599,
  612,
  674,
  931,
  1168,
  1294,
  1433},
 11: {67, 169, 212, 223, 276, 328, 386, 408, 1402, 1574, 1655},
 12: {30,
  45,
  61,
  62,
  73,
  104,
  105,
  156,
  168,
  200,
  205,
  221,
  238,
  259,
  303,
  370,
  447,
  551,
  587,
  706},
 13: {51,
  101,
  120,
  166,
  193,
  197,
  239,
  277,
  297,
  326,
  344,
  368,
  435,
  444,
  470,
  487,
  538,
  545,
  607,
  622,
  663,
  705,
  712,
  768,
  1082},
 14: {325, 558, 579, 668, 682, 786, 792, 811, 851, 864, 921, 1254},
 15: {272,
  277,
  297,
  316,
  326,
  344,
  353,
  368,
  377,
  415,
  435,
  444,
  448,
  470,
  475,
  500,
  520,
  538,
  541,
  1226,
  1282,
  1294,
  1306,
  1402,
  1423,
  1488,
  1517,
  1583},
 16: {13, 24, 49, 121, 154, 178, 227, 247, 257},
 17: {868,
  890,
  921,
  931,
  946,
  984,
  1012,
  1024,
  1028,
  1068,
  1084,
  1092,
  1099,
  1104,
  1107,
  1113,
  1121,
  1136,
  1145,
  1170,
  1195,
  1206,
  1257,
  1284,
  1312,
  1338,
  1377,
  1450,
  1483,
  1515,
  1562,
  1604,
  1659},
 18: {811, 1267, 1284, 1486, 1518, 1566, 1598},
 19: {1311,
  1314,
  1327,
  1331,
  1340,
  1351,
  1352,
  1358,
  1362,
  1363,
  1368,
  1397,
  1402,
  1407,
  1409,
  1415,
  1416,
  1423,
  1425,
  1428,
  1433,
  1448,
  1449,
  1457,
  1460,
  1463,
  1473,
  1486,
  1488,
  1496,
  1510,
  1517,
  1524,
  1529,
  1540,
  1550,
  1566,
  1574,
  1580,
  1583,
  1584,
  1596,
  1602,
  1617,
  1637,
  1638,
  1647,
  1655,
  1689},
 20: {130,
  148,
  166,
  189,
  193,
  197,
  202,
  236,
  261,
  289,
  334,
  351,
  392,
  397,
  409,
  475,
  522,
  527,
  547,
  561,
  582,
  593,
  600,
  604,
  614,
  624,
  724,
  931},
 21: {50,
  51,
  56,
  65,
  101,
  112,
  120,
  124,
  130,
  166,
  189,
  193,
  197,
  239,
  272,
  277,
  297,
  316,
  344,
  368,
  377,
  415,
  470,
  487,
  538,
  562,
  607,
  613,
  622,
  705,
  768,
  892,
  919,
  1050,
  1058,
  1103,
  1116,
  1123,
  1166,
  1167,
  1184,
  1186,
  1213,
  1222,
  1262,
  1332,
  1348,
  1373},
 22: {88, 198, 207, 353, 397, 470, 607, 624},
 23: {239,
  254,
  287,
  316,
  325,
  332,
  353,
  371,
  394,
  463,
  499,
  527,
  558,
  615,
  724,
  1107},
 24: {852,
  870,
  871,
  936,
  1212,
  1473,
  1488,
  1547,
  1556,
  1634,
  1636,
  1652,
  1653},
 25: {1027,
  1145,
  1161,
  1211,
  1331,
  1358,
  1368,
  1380,
  1394,
  1428,
  1448,
  1463,
  1491,
  1518,
  1556,
  1564,
  1592,
  1602,
  1605,
  1615,
  1661,
  1675,
  1684,
  1687},
 26: {107, 121, 142, 144, 495, 915, 990, 1139, 1435},
 27: {29, 110, 148, 193, 241, 261, 1421},
 28: {796,
  1124,
  1134,
  1169,
  1176,
  1180,
  1193,
  1261,
  1294,
  1340,
  1402,
  1423,
  1583,
  1584,
  1596},
 29: {796, 803, 815, 818, 829, 840, 907, 1076, 1078, 1124, 1134, 1519},
 30: {527, 533, 600, 604, 607, 624, 646, 657, 669, 1519},
 31: {1126, 1274, 1330, 1425, 1495, 1582, 1583, 1584, 1652},
 32: {353,
  368,
  377,
  415,
  435,
  437,
  444,
  470,
  475,
  500,
  520,
  538,
  541,
  545,
  562,
  607,
  613,
  622,
  645,
  660,
  663,
  664},
 33: {57,
  70,
  84,
  102,
  218,
  233,
  260,
  262,
  380,
  439,
  485,
  581,
  597,
  676,
  719,
  788},
 34: {374, 520, 559, 607, 685, 1077, 1517, 1602, 1667},
 35: {912,
  934,
  948,
  951,
  964,
  981,
  1003,
  1011,
  1364,
  1464,
  1509,
  1519,
  1541,
  1568,
  1570,
  1589,
  1594,
  1600,
  1607,
  1641,
  1663},
 36: {1430,
  1437,
  1441,
  1490,
  1495,
  1501,
  1502,
  1506,
  1509,
  1513,
  1528,
  1548,
  1575,
  1580,
  1586,
  1594,
  1599,
  1603,
  1607,
  1611,
  1624,
  1632,
  1652,
  1667},
 37: {1028, 1029, 1057, 1368, 1395, 1400, 1519},
 38: {176, 193, 272, 316, 353, 415, 607, 613, 663, 664, 722, 1040, 1163},
 39: {143, 154, 161, 163, 170, 178, 187, 190, 212},
 40: {1134,
  1169,
  1180,
  1193,
  1212,
  1261,
  1282,
  1286,
  1294,
  1306,
  1397,
  1402,
  1409,
  1416,
  1423,
  1473,
  1486,
  1488,
  1517,
  1524,
  1574,
  1583,
  1584,
  1596,
  1652},
 41: {393,
  400,
  408,
  439,
  519,
  570,
  662,
  681,
  796,
  803,
  815,
  818,
  829,
  1007,
  1061,
  1076,
  1078,
  1096,
  1124,
  1134,
  1159,
  1162,
  1168,
  1169,
  1180,
  1193,
  1194,
  1226,
  1261,
  1271,
  1274,
  1282,
  1286,
  1288,
  1291,
  1294,
  1306,
  1311,
  1328,
  1402,
  1409,
  1416,
  1434,
  1461,
  1473,
  1486,
  1488,
  1490,
  1493,
  1517,
  1524,
  1580,
  1583,
  1584,
  1596,
  1602,
  1637,
  1652},
 42: {464, 553, 556, 557, 670, 825, 1173},
 43: {1082,
  1094,
  1103,
  1284,
  1304,
  1310,
  1313,
  1334,
  1377,
  1382,
  1388,
  1395,
  1398,
  1400,
  1422,
  1450,
  1575,
  1583,
  1648},
 44: {877,
  879,
  893,
  903,
  942,
  944,
  993,
  1014,
  1063,
  1067,
  1088,
  1130,
  1141,
  1187,
  1204,
  1237,
  1248,
  1256,
  1267,
  1268,
  1280,
  1299,
  1309,
  1464,
  1667},
 45: {13, 49, 98, 107, 125, 142, 227},
 46: {250,
  258,
  264,
  318,
  366,
  395,
  409,
  455,
  459,
  461,
  472,
  488,
  508,
  525,
  580,
  592,
  608,
  617,
  619,
  633,
  644,
  688,
  723,
  1372},
 47: {802,
  874,
  894,
  912,
  931,
  936,
  953,
  978,
  987,
  1000,
  1017,
  1021,
  1057,
  1137,
  1159,
  1199,
  1212,
  1260,
  1261,
  1277,
  1282,
  1288,
  1341,
  1519,
  1609},
 48: {796,
  818,
  829,
  1124,
  1169,
  1176,
  1180,
  1261,
  1282,
  1294,
  1306,
  1340,
  1402,
  1423},
 49: {607, 643, 658, 1029, 1042, 1050, 1082, 1186, 1400, 1636, 1660},
 50: {106, 248, 391, 739, 1013, 1028, 1139, 1324, 1338, 1447, 1659, 1667},
 51: {284, 301, 332, 374, 389, 559, 562},
 52: {578,
  599,
  759,
  777,
  851,
  852,
  860,
  1078,
  1093,
  1104,
  1131,
  1200,
  1400,
  1435,
  1567,
  1671},
 53: {367,
  376,
  396,
  556,
  636,
  672,
  708,
  716,
  732,
  734,
  736,
  740,
  743,
  748,
  752,
  755,
  767,
  776,
  782,
  787,
  791,
  801,
  832},
 54: {1057, 1061, 1274, 1283, 1327, 1358, 1409, 1524},
 55: {1232, 1248, 1258, 1274, 1286, 1307, 1316, 1324, 1335},
 56: {41,
  84,
  102,
  119,
  218,
  233,
  275,
  278,
  361,
  380,
  452,
  457,
  463,
  550,
  554,
  581,
  609,
  658,
  719,
  745,
  746,
  863,
  901,
  902,
  907,
  938,
  939,
  976,
  996,
  1008,
  1010,
  1041,
  1060,
  1076,
  1079,
  1088,
  1105,
  1176,
  1182,
  1219,
  1226,
  1245,
  1271,
  1306,
  1314,
  1358,
  1368,
  1384,
  1402,
  1415,
  1428,
  1457,
  1462,
  1463,
  1465,
  1466,
  1482,
  1488,
  1493,
  1519,
  1554,
  1598,
  1637,
  1645,
  1647},
 57: {796, 803, 818, 952, 1100, 1180, 1182, 1193, 1473, 1584, 1645},
 58: {85, 148, 261, 351, 397, 527, 561, 582, 600, 624, 724},
 59: {212,
  507,
  1061,
  1157,
  1226,
  1249,
  1289,
  1291,
  1372,
  1376,
  1407,
  1415,
  1425,
  1428,
  1434,
  1435,
  1459,
  1466,
  1482,
  1496,
  1502,
  1514,
  1519,
  1587,
  1637},
 60: {1007, 1446, 1449, 1451, 1452, 1505, 1553},
 61: {858,
  874,
  887,
  896,
  900,
  908,
  911,
  912,
  915,
  920,
  934,
  937,
  948,
  953,
  959,
  974,
  987,
  991,
  995,
  1022,
  1034,
  1036,
  1044,
  1049,
  1051,
  1054,
  1062,
  1065,
  1071,
  1089,
  1091,
  1122,
  1129,
  1131,
  1148,
  1151,
  1174,
  1178,
  1183,
  1188,
  1201,
  1212,
  1214,
  1218,
  1253,
  1266,
  1279,
  1286,
  1288,
  1307,
  1311,
  1330,
  1335,
  1341,
  1343,
  1356,
  1364,
  1378,
  1385,
  1420,
  1424,
  1430,
  1454,
  1476,
  1484,
  1494,
  1501,
  1502,
  1506,
  1513,
  1528,
  1541,
  1542,
  1548,
  1557,
  1561,
  1585,
  1594,
  1599,
  1600,
  1603,
  1613,
  1622,
  1624,
  1631,
  1632,
  1652,
  1657,
  1658,
  1662,
  1665,
  1671,
  1672,
  1673},
 62: {64,
  69,
  121,
  140,
  224,
  229,
  276,
  326,
  415,
  425,
  558,
  707,
  779,
  824,
  1023,
  1226},
 63: {277, 437, 487, 613, 733, 1213, 1256, 1262, 1373, 1422},
 64: {312,
  318,
  408,
  570,
  620,
  656,
  870,
  871,
  911,
  918,
  936,
  947,
  976,
  1168,
  1169,
  1263,
  1271,
  1280,
  1319,
  1505,
  1519,
  1629},
 65: {1512,
  1526,
  1599,
  1601,
  1608,
  1609,
  1635,
  1637,
  1641,
  1659,
  1666,
  1677,
  1681,
  1686},
 66: {1096,
  1124,
  1168,
  1180,
  1193,
  1261,
  1282,
  1286,
  1294,
  1306,
  1416,
  1473,
  1486,
  1517,
  1584,
  1596,
  1652},
 67: {533, 724, 731, 774, 1444, 1450, 1480, 1515},
 68: {166, 272, 487, 500, 722, 762, 1039, 1133},
 69: {595, 661, 665, 675, 686, 698, 713, 893, 942, 1014, 1046, 1061, 1063},
 70: {89, 204, 279, 323, 730, 1401, 1466, 1472},
 71: {767,
  776,
  782,
  787,
  791,
  813,
  833,
  857,
  866,
  867,
  870,
  882,
  884,
  898,
  904,
  916,
  923,
  928,
  966,
  970,
  985,
  992,
  997,
  999,
  1001,
  1005,
  1009,
  1027,
  1033,
  1066,
  1086,
  1088,
  1125,
  1150,
  1161,
  1196,
  1203,
  1205,
  1211,
  1216,
  1217,
  1227,
  1244,
  1247,
  1251,
  1285,
  1302,
  1329,
  1336,
  1349,
  1350,
  1355,
  1364,
  1372,
  1383,
  1384,
  1439,
  1465,
  1491,
  1502,
  1503,
  1507,
  1519,
  1537,
  1549,
  1553,
  1571,
  1579,
  1588,
  1610,
  1612,
  1639,
  1660},
 72: {51,
  56,
  65,
  101,
  112,
  120,
  124,
  130,
  166,
  189,
  193,
  197,
  239,
  272,
  277,
  297,
  316,
  326,
  344,
  353,
  368,
  377,
  415,
  435,
  437,
  444,
  470,
  487,
  500,
  520,
  538,
  541,
  545,
  562,
  607,
  613,
  622,
  645,
  663,
  664,
  705,
  712,
  722,
  762,
  768,
  830,
  892,
  919,
  1006,
  1042,
  1103,
  1116,
  1123,
  1152,
  1166,
  1167,
  1184,
  1186,
  1213,
  1221,
  1222,
  1239,
  1262,
  1332,
  1348,
  1373,
  1422,
  1453,
  1478},
 73: {112,
  120,
  130,
  189,
  193,
  197,
  272,
  277,
  316,
  344,
  368,
  415,
  435,
  562,
  607,
  705,
  1040,
  1082,
  1123,
  1221,
  1332,
  1348,
  1422,
  1481,
  1572},
 74: {562, 622, 682, 1167, 1449, 1472, 1573, 1602, 1636},
 75: {137,
  138,
  202,
  826,
  892,
  931,
  1078,
  1124,
  1214,
  1332,
  1421,
  1447,
  1486,
  1550,
  1630},
 76: {112, 120, 130, 189, 193, 197, 272, 277, 316, 344, 368, 415, 435, 562},
 77: {779, 803, 815, 818, 829, 1105, 1124},
 78: {231, 399, 415, 431, 451, 476, 557, 624, 1285, 1428, 1534, 1617, 1637},
 79: {13, 50, 1124, 1324, 1325, 1519, 1603},
 80: {1173, 1612, 1626, 1639, 1660, 1661, 1669, 1675, 1684, 1687},
 81: {84,
  185,
  233,
  260,
  275,
  278,
  380,
  452,
  457,
  463,
  581,
  658,
  676,
  788,
  1023},
 82: {92, 164, 517, 634, 775, 947, 1455},
 83: {169, 178, 190, 253, 344, 363, 386, 618},
 84: {18,
  54,
  72,
  80,
  103,
  126,
  150,
  181,
  222,
  231,
  294,
  304,
  313,
  321,
  347,
  381,
  389,
  399,
  423,
  462,
  524,
  544,
  550,
  557,
  563,
  590,
  603,
  726,
  730,
  747,
  749,
  758,
  766,
  1466,
  1496},
 85: {829, 1076, 1180, 1473, 1517, 1566, 1602},
 86: {198, 243, 339, 371, 435, 696, 845, 1221, 1387, 1412, 1515},
 87: {772, 1077, 1208, 1265, 1353, 1364, 1502, 1516, 1517, 1568, 1648, 1667},
 88: {52,
  83,
  110,
  136,
  141,
  162,
  180,
  184,
  223,
  271,
  283,
  301,
  320,
  364,
  384,
  406,
  438,
  522,
  690,
  735,
  754,
  756,
  809,
  840,
  931,
  1236},
 89: {117, 332, 527, 582, 604, 657, 724},
 90: {470, 500, 520, 538, 541, 545, 562, 613, 622, 660},
 91: {329, 600, 604, 657, 724, 729, 769, 774, 803, 883, 890, 1182, 1435, 1689},
 92: {1009, 1077, 1134, 1169, 1363, 1486, 1583},
 93: {58, 148, 308, 369, 503, 504, 523, 659, 669, 714, 724},
 94: {241,
  291,
  324,
  330,
  331,
  337,
  351,
  355,
  361,
  396,
  408,
  441,
  448,
  604,
  631,
  657,
  680,
  689,
  730,
  752,
  758,
  772,
  779,
  809,
  823,
  837,
  844,
  848,
  854,
  874,
  894,
  907,
  908,
  931,
  948,
  969,
  981,
  987,
  1021,
  1022,
  1027,
  1030,
  1034,
  1036,
  1052,
  1074,
  1090,
  1091,
  1096,
  1146,
  1173,
  1196,
  1266,
  1304,
  1316,
  1352,
  1364,
  1511,
  1519,
  1587,
  1684},
 95: {241,
  291,
  324,
  330,
  331,
  337,
  355,
  361,
  396,
  408,
  441,
  448,
  631,
  689,
  730,
  752,
  758,
  772,
  779,
  809,
  823,
  837,
  844,
  848,
  854,
  874,
  894,
  907,
  908,
  931,
  948,
  969,
  981,
  987,
  1021,
  1022,
  1027,
  1030,
  1034,
  1036,
  1052,
  1074,
  1090,
  1091,
  1096,
  1173,
  1196,
  1266,
  1304,
  1316,
  1364,
  1461,
  1511,
  1519,
  1587,
  1684},
 96: {733,
  737,
  741,
  747,
  749,
  758,
  766,
  779,
  794,
  796,
  802,
  803,
  804,
  809,
  815,
  818,
  825,
  826,
  829,
  832,
  837,
  839,
  844,
  848,
  849,
  850,
  853,
  854,
  858,
  862,
  865,
  874,
  875,
  880,
  888,
  889,
  894,
  896,
  900,
  901,
  907,
  908,
  912,
  925,
  930,
  934,
  937,
  947,
  948,
  952,
  954,
  959,
  964,
  976,
  987,
  989,
  995,
  1000,
  1008,
  1017,
  1026,
  1035,
  1036,
  1039,
  1049,
  1052,
  1059,
  1061,
  1074,
  1075,
  1076,
  1078,
  1088,
  1093,
  1100,
  1105,
  1106,
  1117,
  1124,
  1144,
  1149,
  1151,
  1162,
  1168,
  1169,
  1173,
  1174,
  1176,
  1178,
  1180,
  1181,
  1182,
  1183,
  1188,
  1191,
  1197,
  1200,
  1201,
  1212,
  1214,
  1224,
  1226,
  1246,
  1260,
  1261,
  1263,
  1282,
  1283,
  1286,
  1288,
  1294,
  1306,
  1314,
  1327,
  1343,
  1352,
  1357,
  1363,
  1364,
  1397,
  1401,
  1402,
  1407,
  1416,
  1423,
  1424,
  1425,
  1433,
  1448,
  1449,
  1457,
  1461,
  1473,
  1486,
  1488,
  1496,
  1497,
  1504,
  1510,
  1517,
  1519,
  1524,
  1551,
  1557,
  1574,
  1583,
  1584,
  1596,
  1599,
  1603,
  1617,
  1625,
  1628,
  1637,
  1655,
  1686,
  1689},
 97: {937, 1075, 1180, 1288, 1311, 1486, 1580, 1583},
 98: {386,
  400,
  408,
  519,
  667,
  681,
  713,
  796,
  803,
  818,
  829,
  947,
  976,
  1088,
  1124,
  1162,
  1168,
  1169,
  1176,
  1261,
  1282,
  1294,
  1306,
  1402,
  1416,
  1423,
  1433,
  1449,
  1473,
  1486,
  1488,
  1504,
  1510,
  1517,
  1566,
  1583,
  1584,
  1596,
  1623,
  1655,
  1689},
 99: {369,
  371,
  391,
  397,
  428,
  440,
  485,
  503,
  504,
  523,
  527,
  539,
  624,
  628,
  659,
  669,
  695,
  714,
  724,
  739,
  786,
  811,
  827,
  851,
  883,
  914,
  916,
  921,
  983,
  1012,
  1013,
  1024,
  1028,
  1076,
  1104,
  1142,
  1206,
  1257,
  1261,
  1272,
  1300,
  1310,
  1324,
  1334,
  1519,
  1659},
 100: {23,
  92,
  164,
  281,
  352,
  416,
  430,
  517,
  552,
  606,
  761,
  770,
  775,
  803,
  809,
  814,
  878,
  1522},
 101: {183, 241, 266, 267, 314, 332, 369, 391, 713},
 102: {85, 148, 261, 351, 397, 527, 561, 582, 600, 604, 624, 724, 1282},
 103: {876,
  952,
  1019,
  1061,
  1079,
  1125,
  1174,
  1207,
  1208,
  1285,
  1289,
  1343,
  1494,
  1505,
  1594,
  1624,
  1634,
  1635,
  1661,
  1678,
  1687},
 104: {384,
  721,
  757,
  825,
  860,
  872,
  976,
  996,
  1138,
  1181,
  1632,
  1652,
  1683,
  1685},
 105: {39,
  43,
  69,
  74,
  82,
  120,
  165,
  169,
  307,
  346,
  550,
  558,
  564,
  592,
  597,
  618,
  845,
  1077,
  1258,
  1362,
  1371,
  1436},
 106: {527, 547, 561, 582, 593, 600, 604, 624, 931},
 107: {445, 469, 529, 661, 665, 675, 686, 698},
 108: {1431, 1449, 1475, 1571, 1606, 1626, 1639, 1656},
 109: {155, 369, 409, 457, 522, 557, 642, 652, 657, 662, 1206, 1515},
 110: {11, 389, 549, 621, 646, 679, 680, 797},
 111: {1349, 1592, 1610, 1626, 1653, 1661, 1680, 1687},
 112: {227,
  409,
  667,
  681,
  947,
  1124,
  1169,
  1180,
  1193,
  1306,
  1397,
  1423,
  1473,
  1574,
  1583,
  1584,
  1596},
 113: {570,
  609,
  649,
  707,
  848,
  931,
  1056,
  1063,
  1377,
  1400,
  1405,
  1428,
  1449,
  1520,
  1543,
  1565,
  1637},
 114: {148,
  193,
  195,
  241,
  248,
  254,
  261,
  272,
  273,
  290,
  312,
  319,
  332,
  339,
  340,
  355,
  576,
  1502},
 115: {758,
  766,
  794,
  804,
  832,
  836,
  872,
  889,
  901,
  905,
  936,
  952,
  954,
  989,
  994,
  1000,
  1016,
  1017,
  1021,
  1029,
  1039,
  1052,
  1057,
  1059,
  1061,
  1064,
  1074,
  1090,
  1093,
  1098,
  1101,
  1120,
  1143,
  1163,
  1175,
  1192,
  1199,
  1209,
  1223,
  1224,
  1226,
  1229,
  1249,
  1260,
  1263,
  1271,
  1274,
  1283,
  1291,
  1297,
  1301,
  1325,
  1327,
  1328,
  1331,
  1352,
  1358,
  1363,
  1374,
  1376,
  1386,
  1407,
  1409,
  1415,
  1425,
  1432,
  1434,
  1435,
  1457,
  1459,
  1461,
  1463,
  1466,
  1482,
  1496,
  1505,
  1514,
  1519,
  1524,
  1531,
  1535,
  1540,
  1545},
 116: {1501, 1502, 1577, 1592, 1612, 1644, 1653},
 117: {852,
  1032,
  1088,
  1094,
  1105,
  1124,
  1168,
  1169,
  1176,
  1210,
  1264,
  1305,
  1312,
  1313,
  1364},
 118: {408, 620, 681, 733, 779, 818, 825, 829, 976},
 119: {148, 266, 271, 459, 488, 503, 527},
 120: {407, 608, 635, 639, 669, 680, 682, 684, 715},
 121: {562, 578, 579, 616, 624, 659, 724},
 122: {13, 49, 98, 107, 125, 142, 165, 227, 247, 257, 475},
 123: {1088, 1100, 1169, 1210, 1358, 1402, 1450},
 124: {17,
  29,
  50,
  65,
  82,
  85,
  101,
  120,
  143,
  219,
  248,
  261,
  266,
  290,
  314,
  329,
  339,
  353,
  361,
  369,
  402,
  417,
  468,
  472,
  485,
  495,
  496,
  502,
  505,
  507,
  530,
  533,
  539,
  543,
  546,
  550,
  560,
  561,
  564,
  569,
  572,
  583,
  586,
  590,
  602,
  616,
  618,
  625,
  631,
  640,
  643,
  649,
  657,
  682,
  684,
  701,
  703,
  709,
  724,
  725,
  731,
  733,
  742,
  744,
  753,
  786,
  806,
  811,
  819,
  820,
  841,
  843,
  845,
  851,
  868,
  890,
  909,
  914,
  944,
  946,
  952,
  968,
  977,
  983,
  984,
  1002,
  1053,
  1056,
  1076,
  1084,
  1087,
  1099,
  1113,
  1121,
  1123,
  1128,
  1133,
  1136,
  1140,
  1145,
  1154,
  1158,
  1168,
  1170,
  1179,
  1182,
  1190,
  1202,
  1232,
  1233,
  1254,
  1255,
  1257,
  1261,
  1282,
  1300,
  1304,
  1310,
  1312,
  1334,
  1360,
  1361,
  1377,
  1382,
  1400,
  1406,
  1419,
  1477,
  1481,
  1494,
  1515,
  1519,
  1520,
  1552,
  1555,
  1565,
  1597,
  1628},
 125: {117,
  148,
  160,
  241,
  290,
  308,
  351,
  397,
  440,
  495,
  527,
  533,
  561,
  600,
  604,
  616,
  624,
  646,
  657,
  680,
  695,
  1126},
 126: {976, 1076, 1088, 1100, 1105, 1139, 1294, 1310, 1364, 1574, 1689},
 127: {1169, 1193, 1340, 1486, 1488, 1517, 1524, 1584, 1596},
 128: {1050,
  1082,
  1103,
  1123,
  1184,
  1206,
  1213,
  1221,
  1262,
  1324,
  1332,
  1348,
  1373,
  1400},
 129: {1257, 1261, 1306, 1314, 1433, 1473, 1488, 1510},
 130: {326, 344, 377, 470, 487, 520, 538, 545, 562, 607, 622, 645},
 131: {905, 977, 1012, 1100, 1136, 1400, 1573, 1584},

In [52]:
def calculate_cosine_similarity(user1, user2, user_item_sets):
    items_user1 = user_item_sets.get(user1, set())
    items_user2 = user_item_sets.get(user2, set())
    
    # Calculate intersection of items
    intersection = len(items_user1.intersection(items_user2))
    
    # Compute the dot product of the vectors representing the item sets
    dot_product = intersection
    
    # Compute the magnitudes of the vectors
    magnitude_user1 = len(items_user1)
    magnitude_user2 = len(items_user2)
    
    # Handle division by zero
    if magnitude_user1 == 0 or magnitude_user2 == 0:
        return 0.0
    
    # Compute cosine similarity
    cosine_similarity = dot_product / (magnitude_user1 * magnitude_user2) ** 0.5
    return cosine_similarity

In [53]:
unique_users = train['user'].unique()

In [54]:
# Calculate Jaccard similarity for all user pairs
cosine_similarities = []

for user1, user2 in product(unique_users, repeat=2):
    if user1 != user2:
        similarity = calculate_cosine_similarity(user1, user2,user_item_sets)
        cosine_similarities.append({'User1': user1, 'User2': user2, 'Similarity': similarity})

In [55]:
# Create a DataFrame for Jaccard similarities
cosine_df = pd.DataFrame(cosine_similarities)

# Reshape the DataFrame to have User1, User2, and Similarity as columns
cosine_matrix = cosine_df.pivot(index='User1', columns='User2', values='Similarity')

idx = range(len(cosine_matrix))
cosine_matrix.values[idx, idx] = 1.0

In [56]:
cosine_matrix

User2,0,1,2,3,4,5,6,7,8,9,...,5397,5398,5399,5400,5401,5402,5403,5404,5405,5406
User1,,,,,,,,,,,,,,,,,,,,,
0,1.000000,0.0,0.0,0.105409,0.0,0.050252,0.000000,0.000000,0.000000,0.125245,...,0.068041,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
1,0.000000,1.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.083624,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
2,0.000000,0.0,1.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
3,0.105409,0.0,0.0,1.000000,0.0,0.349603,0.000000,0.243432,0.428174,0.534680,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
4,0.000000,0.0,0.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.083333,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5402,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.083333,0.294174,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.0,0.0
5403,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.087039,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.577350,0.696311,0.654654,0.0,1.000000,0.436436,0.0,0.0
5404,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.503953,0.569803,0.571429,0.0,0.436436,1.000000,0.0,0.0
5405,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.092450,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.0,0.0
5406,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,1.0

In [57]:
def file_load(path):
    my_file = open(path, "r")
    # reading the file
    data = my_file.read()
    # splitting the text it further when '.' is seen.
    data_into_list = data.split("\n")[:-1]
    myseed=[int(item) for item in data_into_list]
    return myseed

In [58]:
superspreader=file_load(f'{DATA_FILE_DIR}/superspreader_50.txt')

In [59]:
# Create untrusted users list
untrusted_users = list(superspreader)

# Remove user 0 if it exists (consistent with your Politifact code)
if 0 in untrusted_users:
    untrusted_users.remove(0)

# Save to pickle
with open(f'{PROCESSED_FILE_DIR}/untrusted_users_ss50.pickle', 'wb') as f:
    pickle.dump(untrusted_users, f)

print(f"Saved {len(untrusted_users)} untrusted users to pickle file")

Saved 281 untrusted users to pickle file

In [60]:
reputation_threshold = 0.6

# Filter users based on reputation greater than 0.6 and not in superspreaders
trusted_users = [i for i in range(5407) if i not in superspreader]

# Dictionary to store top similar trustworthy users for each user
top_trustworthy_similar_users = defaultdict(set)

# Iterate over each user
for user in cosine_matrix.index:
    # Get cosine similarity values for the user
    user_similarity = cosine_matrix.loc[user]
    # Exclude untrustworthy similar users (not in trusted_users), users in superspreaders, and the user itself
    similar_trustworthy_users = user_similarity[(user_similarity > 0) & (user_similarity.index != user) & (~np.isin(user_similarity.index, superspreader)) & (user_similarity.index.isin(trusted_users))]
    # Sort similar trustworthy users by similarity (descending order) and take the top 10
    temp = set(similar_trustworthy_users.sort_values(ascending=False).index[:10].tolist())
    if len(temp) > 0:
        top_trustworthy_similar_users[user] = temp

In [61]:
top_trustworthy_similar_users

defaultdict(set,
            {0: {977, 1300, 1343, 1623, 1681, 4227, 4858, 4888, 4976, 5205},
             1: {2902, 3160, 3647, 3824, 4589, 4642, 4832, 5165, 5225, 5345},
             2: {769, 3295, 4133, 4153, 4260, 4309, 4334, 4394, 4452, 4458},
             3: {9, 420, 744, 1431, 1489, 1572, 2626, 3395, 4794, 4995},
             4: {253, 610, 716, 1156, 1690, 4641, 4787, 5048, 5113, 5114},
             5: {9, 789, 792, 840, 844, 1122, 1333, 2056, 2812, 3068},
             6: {54, 245, 587, 1594, 1644, 1709, 2159, 2699, 2706, 2786},
             7: {888, 1182, 1293, 1375, 1572, 1697, 1927, 2452, 3375, 3883},
             8: {9, 470, 744, 1107, 1526, 2060, 2182, 2291, 2580, 2626},
             9: {789, 792, 840, 844, 888, 1122, 1132, 1145, 1333, 1431},
             10: {518, 610, 876, 3194, 4542, 4655, 4972, 5183, 5288, 5350},
             11: {551, 1164, 1478, 1532, 3631, 4422, 4547, 4702, 4703, 4793},
             12: {1042, 1206, 2239, 2335, 2542, 2603, 2716, 4101, 4190, 4507},
             13: {72, 441, 981, 4353, 4430, 4518, 4531, 4596, 4621, 5191},
             14: {512, 524, 647, 672, 700, 819, 3343, 3939, 4188, 4972},
             15: {32, 3009, 3805, 4353, 4490, 4518, 4531, 4596, 4621, 5191},
             16: {45, 122, 508, 4350, 5116, 5138, 5346, 5367, 5388, 5391},
             17: {697, 744, 1200, 1572, 1813, 2182, 2291, 2580, 2626, 3198},
             18: {669, 724, 1125, 1327, 1557, 1570, 1689, 2210, 2450, 2624},
             19: {402, 1128, 1266, 1524, 1686, 1758, 2096, 2138, 2572, 2703},
             20: {58, 102, 2792, 3791, 4024, 4094, 4535, 4752, 4823, 4899},
             21: {72, 851, 940, 1080, 1102, 1393, 2188, 4596, 4859, 5191},
             22: {139, 235, 302, 346, 374, 1160, 2362, 2758, 4880, 4885},
             23: {89, 374, 2049, 3801, 3992, 4102, 4454, 4711, 5012, 5120},
             24: {771, 824, 1240, 1313, 1368, 1372, 1475, 1860, 1884, 2269},
             25: {723, 764, 814, 948, 984, 1528, 1586, 1593, 1619, 2053},
             26: {45, 579, 1695, 4670, 4902, 4927, 5206, 5289, 5346, 5388},
             27: {139, 223, 877, 4277, 5053, 5067, 5353, 5368, 5373, 5380},
             28: {168, 250, 251, 343, 752, 1618, 1882, 1942, 1944, 1958},
             29: {77, 898, 1026, 1251, 1942, 2005, 3143, 3180, 3331, 3556},
             30: {3118, 4406, 4679, 4680, 4681, 4682, 4683, 4684, 4775, 4797},
             31: {191, 268, 366, 993, 1700, 1749, 1845, 1898, 1916, 2069},
             32: {1622, 2522, 4576, 4786, 4789, 4998, 5000, 5044, 5047, 5049},
             33: {56, 81, 395, 1054, 1100, 1474, 2344, 3351, 4722, 4723},
             34: {1499, 2879, 3156, 4108, 4553, 4887, 5080, 5085, 5124, 5126},
             35: {256, 1052, 1259, 1418, 1674, 2421, 2422, 3125, 3165, 3486},
             36: {330, 350, 413, 526, 627, 872, 1155, 1658, 1831, 1871},
             37: {1107, 1351, 1489, 1675, 2039, 2568, 3212, 3446, 3808, 3896},
             38: {549, 981, 1692, 4353, 4430, 4518, 4596, 4621, 4772, 4786},
             39: {1532, 4139, 4231, 4515, 4670, 4793, 5115, 5144, 5234, 5397},
             40: {687, 821, 1627, 1943, 1944, 1946, 1947, 1958, 2118, 2855},
             41: {40, 66, 239, 687, 760, 898, 1618, 1942, 2005, 3180},
             42: {4368, 4491, 4492, 4493, 4626, 4650, 4816, 4915, 4956, 5062},
             43: {296, 619, 754, 999, 1040, 1076, 2056, 2711, 2730, 3068},
             44: {167, 244, 310, 311, 1381, 1383, 2105, 3172, 3202, 3270},
             45: {16, 122, 1991, 4932, 5116, 5138, 5320, 5346, 5367, 5388},
             46: {583, 2372, 2542, 3441, 3816, 4747, 4844, 4990, 5040, 5098},
             47: {623, 1243, 2380, 3547, 3672, 3673, 3674, 3676, 3678, 3686},
             48: {28, 752, 829, 1618, 1882, 1942, 2005, 2528, 2662, 3180},
             49: {37, 128, 635, 1289, 1306, 1307, 1432, 1773, 1827, 2399},
             50: {255, 479, 671, 789, 840, 844, 1927, 3096, 3170, 3896},
             51: {293, 549, 2178, 2879, 4641, 5080, 5085, 5125, 5126, 5218},
             52: {564, 1133, 1569, 2297, 2745, 2854, 3077, 3124, 3329, 3831},
             53: {369, 928, 941, 1999, 2664, 4041, 4334, 4360, 4411, 4474},
             54: {245, 587, 1594, 1709, 2159, 2471, 2699, 2706, 2786, 2990},
             55: {850, 1126, 2529, 2614, 2702, 2749, 2834, 3034, 3122, 3141},
             56: {334, 578, 708, 1295, 1404, 2808, 2934, 3427, 3746, 3843},
             57: {829, 1618, 1840, 1942, 2418, 2803, 3143, 3180, 3516, 3556},
             58: {102, 2792, 3791, 4024, 4094, 4535, 4717, 4752, 4823, 4899},
             59: {426, 443, 577, 646, 1143, 1323, 1426, 2199, 2505, 2685},
             60: {221, 349, 536, 588, 654, 704, 783, 1058, 1753, 2228},
             61: {318, 773, 988, 1052, 1190, 1394, 1418, 1831, 3422, 3463},
             62: {606, 3182, 3216, 3425, 4031, 4207, 4295, 4373, 4506, 4622},
             63: {21, 72, 128, 132, 163, 265, 448, 1662, 4490, 4531},
             64: {118, 157, 386, 453, 1868, 2346, 3209, 3314, 3600, 4217},
             65: {820, 860, 945, 1093, 1187, 1508, 1515, 1804, 1987, 2111},
             66: {40, 343, 687, 753, 821, 1347, 1882, 1924, 1943, 1945},
             67: {3, 9, 227, 742, 1523, 2168, 3724, 3783, 3825, 4104},
             68: {265, 323, 446, 711, 2658, 3521, 3856, 4514, 4531, 4643},
             69: {107, 244, 310, 312, 2105, 3525, 3550, 3872, 4758, 4852},
             70: {484, 1466, 1506, 2006, 2042, 2091, 2494, 2986, 3865, 4911},
             71: {644, 1117, 1268, 2067, 2174, 2304, 2347, 2385, 2442, 3099},
             72: {21, 1095, 4353, 4430, 4518, 4531, 4552, 4596, 4621, 5191},
             73: {76, 283, 981, 2446, 2980, 4730, 4939, 5009, 5317, 5341},
             74: {90, 169, 960, 1314, 1421, 1887, 2115, 4643, 4890, 5004},
             75: {186, 1083, 1531, 1673, 1710, 1924, 1945, 2749, 2841, 3294},
             76: {73, 283, 981, 2980, 4730, 4939, 5009, 5191, 5317, 5341},
             77: {29, 829, 3143, 3793, 3854, 3966, 4103, 4418, 4423, 4447},
             78: {688, 2070, 3871, 4281, 4945, 4947, 4985, 5084, 5150, 5250},
             79: {1502, 1742, 2154, 2249, 2281, 2328, 2949, 3020, 3024, 3289},
             80: {628, 814, 943, 948, 984, 1002, 1152, 1473, 1562, 1593},
             81: {33, 56, 395, 1100, 3351, 4158, 4722, 4723, 4848, 4913},
             82: {100, 157, 340, 453, 1324, 1981, 3760, 3890, 4088, 4109},
             83: {133, 332, 590, 1164, 2378, 4432, 4481, 4547, 5144, 5321},
             84: {498, 1922, 3449, 4527, 4579, 4733, 5042, 5164, 5169, 5325},
             85: {904, 1125, 1227, 1251, 1499, 1962, 2237, 2599, 3143, 3556},
             86: {253, 442, 499, 1320, 1885, 2001, 3009, 4659, 4944, 5162},
             87: {321, 660, 718, 790, 915, 1501, 2027, 2258, 2434, 2724},
             88: {171, 325, 727, 1376, 1467, 3257, 3803, 4872, 5318, 5344},
             89: {3354, 3646, 4078, 4093, 4550, 4617, 4711, 4724, 4918, 5012},
             90: {32, 1622, 4467, 4789, 4998, 5000, 5003, 5044, 5047, 5079},
             91: {89, 749, 847, 1257, 2399, 4379, 4406, 4617, 4762, 4933},
             92: {145, 237, 239, 383, 553, 760, 1227, 1944, 2118, 2530},
             93: {4398, 4408, 4500, 4591, 4598, 4639, 4656, 4697, 4768, 4865},
             94: {95, 1701, 2367, 3442, 3839, 3851, 3999, 4019, 4069, 4226},
             95: {94, 1561, 1701, 2367, 3442, 3851, 3999, 4019, 4069, 4226},
             96: {361, 695, 995, 1245, 1382, 1542, 1561, 2211, 2289, 2500},
             97: {41, 92, 232, 268, 581, 904, 1056, 1059, 1585, 1812},
             98: {343, 752, 816, 1377, 1618, 1882, 2023, 2096, 2349, 2889},
             99: {255, 420, 1333, 1338, 1431, 3261, 3395, 4484, 4746, 4790},
             100: {82, 340, 1324, 1420, 1981, 3578, 3760, 3890, 3966, 4088},
             101: {4111, 4333, 4431, 4660, 5054, 5122, 5200, 5253, 5271, 5324},
             102: {58, 2792, 3791, 4024, 4094, 4535, 4717, 4752, 4823, 4899},
             103: {372, 538, 572, 607, 1235, 1846, 1919, 2083, 2630, 3884},
             104: {1066, 1215, 1323, 1396, 1931, 1948, 3013, 3541, 3619, 3923},
             105: {83, 857, 1135, 1799, 3370, 3425, 3566, 3892, 4580, 5331},
             106: {662, 1257, 2792, 3791, 4094, 4565, 4717, 4752, 4823, 4899},
             107: {69, 244, 310, 312, 3525, 3550, 4415, 4758, 4779, 4852},
             108: {176, 569, 723, 943, 948, 1593, 1714, 2084, 2268, 2271},
             109: {477, 878, 1107, 1434, 1489, 1675, 4114, 4889, 4933, 4970},
             110: {3691, 3906, 3917, 3918, 3931, 3942, 3957, 4247, 4248, 4891},
             111: {116, 596, 628, 814, 943, 948, 984, 1002, 1437, 1593},
             112: {219, 232, 250, 251, 366, 816, 1304, 1605, 2418, 2576},
             113: {162, 619, 1076, 1103, 1322, 1720, 1852, 2694, 2919, 3074},
             114: {27, 877, 977, 1300, 1681, 2090, 3741, 3769, 4227, 4976},
             115: {901, 920, 939, 1123, 1497, 1820, 1849, 1883, 2073, 2185},
             116: {328, 330, 596, 628, 680, 814, 900, 984, 1593, 2312},
             117: {1078, 1634, 2666, 3023, 3171, 3398, 3434, 3506, 3509, 3551},
             118: {77, 212, 2803, 3945, 3966, 4103, 4217, 4390, 4421, 4423},
             119: {1098, 1655, 3543, 3611, 3717, 4516, 4844, 5107, 5143, 5163},
             120: {450, 693, 763, 876, 1960, 2695, 3194, 3922, 4613, 4972},
             121: {457, 2201, 3500, 4362, 4410, 4510, 4597, 4755, 4762, 4889},
             122: {16, 45, 579, 2627, 4925, 5116, 5138, 5346, 5367, 5388},
             123: {436, 1008, 1640, 1886, 2897, 3171, 3196, 3398, 3434, 3506},
             124: {5, 9, 336, 697, 1132, 1145, 1333, 1431, 1813, 2540},
             125: {1923, 2127, 4003, 4204, 4304, 4459, 4562, 4616, 4690, 4983},
             126: {874, 1114, 1286, 2014, 2066, 2481, 3196, 3273, 3571, 3671},
             127: {268, 753, 1263, 1700, 1898, 1916, 1940, 1944, 1946, 2118},
             128: {163, 924, 1289, 1306, 1307, 1393, 1861, 2446, 3075, 3275},
             129: {206, 710, 1108, 1377, 1766, 2096, 2406, 2526, 2572, 2814},
             130: {169, 1445, 4091, 4353, 4522, 4595, 4621, 4786, 5002, 5003},
             131: {57, 802, 960, 1322, 1433, 1449, 1710, 3135, 3245, 3273},
             132: {63, 128, 1393, 1625, 1815, 1901, 2586, 2593, 2775, 2779},
             133: {551, 1532, 3448, 3631, 4422, 4432, 4558, 4702, 4703, 5066},
             134: {752, 1618, 1786, 1882, 1942, 1943, 1945, 1946, 1947, 2833},
             135: {777, 1046, 1838, 2044, 2110, 2262, 2288, 2296, 2397, 2539},
             136: {583, 893, 2542, 3441, 3816, 4747, 4844, 4938, 5040, 5098},
             137: {294, 1690, 2049, 3606, 3996, 4097, 4332, 4641, 5086, 5114},
             138: {48, 251, 829, 1026, 1251, 2003, 2005, 3143, 3180, 3265},
             139: {235, 302, 2362, 2758, 4004, 4528, 4752, 4833, 5053, 5067},
             140: {479, 671, 896, 2995, 3194, 3284, 3907, 4063, 4613, 5012},
             141: {789, 792, 793, 840, 844, 1107, 2056, 2060, 2711, 2800},
             142: {41, 313, 633, 1404, 1585, 1883, 2139, 3051, 3297, 3322},
             143: {753, 1096, 1367, 1627, 1768, 2198, 2514, 2572, 2991, 3239},
             144: {92, 543, 751, 1594, 1709, 2198, 2512, 2662, 2706, 2855},
             145: {250, 383, 556, 1227, 1401, 2528, 2662, 2921, 3265, 3385},
             146: {714, 952, 956, 1210, 1360, 1398, 3286, 3795, 3972, 4351},
             147: {3612, 4333, 4398, 4431, 4591, 4637, 4746, 4790, 4815, 4869},
             148: {824, 1064, 1112, 1288, 1354, 1361, 1475, 2770, 2771, 3587},
             149: {58, 2792, 3791, 4024, 4094, 4535, 4717, 4752, 4823, 4899},
             150: {29, 77, 126, 212, 304, 436, 1961, 2003, 3273, 3923},
             151: {38, 374, 549, 968, 1651, 1775, 2665, 2748, 2980, 3112},
             152: {289, 692, 1085, 1414, 1429, 2531, 2707, 2997, 3228, 3508},
             153: {729, 754, 985, 1078, 1634, 1640, 1886, 2087, 2774, 3023},
             154: {901, 920, 1143, 2073, 2138, 2538, 2650, 2808, 3112, 3347},
             155: {2387, 3052, 3305, 4440, 4730, 4830, 5034, 5317, 5341, 5378},
             156: {145, 556, 1011, 1157, 1370, 1738, 3314, 3371, 3394, 3486},
             157: {64, 796, 832, 1041, 2249, 2752, 2899, 2912, 3193, 3209},
             158: {2420, 2457, 2503, 2639, 2822, 3025, 3102, 3213, 3247, 3300},
             159: {627, 800, 900, 1052, 1418, 1547, 1658, 1993, 2382, 3120},
             160: {424, 1281, 1903, 2516, 2630, 2945, 3244, 3508, 3847, 4394},
             161: {551, 610, 1164, 3631, 4421, 4422, 4542, 4559, 4703, 5288},
             162: {1373, 1538, 2037, 2230, 2850, 2955, 2976, 3000, 3020, 3132},
             163: {21, 72, 128, 1393, 1901, 2754, 2775, 2779, 3294, 3367},
             164: {583, 1100, 4207, 4629, 4640, 4722, 4723, 4791, 4844, 4938},
             165: {88, 727, 1376, 1467, 1727, 3257, 3431, 4872, 5318, 5344},
             166: {695, 868, 995, 1245, 1542, 1561, 2014, 2135, 4066, 4069},
             167: {44, 311, 415, 1383, 2105, 2895, 3202, 3212, 3270, 3510},
             168: {28, 219, 250, 251, 343, 383, 1882, 1944, 1958, 2528},
             169: {130, 190, 441, 4353, 4522, 4595, 4596, 4621, 4643, 5004},
             170: {490, 1058, 1248, 1392, 1450, 1629, 2286, 2469, 3353, 3694},
             171: {88, 1467, 3257, 3803, 3853, 4210, 4291, 4879, 5318, 5344},
             172: {168, 219, 231, 250, 753, 1377, 1479, 1767, 1944, 2118},
             173: {30, 125, 355, 1923, 2127, 3948, 4336, 4406, 4516, 4616},
             174: {117, 648, 985, 1078, 2444, 2567, 3023, 3171, 3232, 3551},
             175: {36, 185, 490, 516, 1450, 1494, 1577, 1919, 1925, 2139},
             176: {116, 569, 723, 814, 1528, 1593, 1619, 1809, 2084, 2298},
             177: {384, 408, 908, 1270, 4029, 4031, 4149, 4419, 4456, 4672},
             178: {213, 631, 781, 794, 2627, 2665, 3411, 3882, 3905, 4638},
             179: {4141, 4442, 4500, 4617, 4639, 4656, 4718, 4768, 4820, 5012},
             180: {311, 991, 1374, 1557, 2034, 2134, 2172, 2282, 2360, 2827},
             181: {901, 920, 939, 1497, 1820, 1849, 1883, 2073, 2185, 2468},
             182: {58, 102, 2232, 2792, 3791, 4022, 4024, 4094, 4535, 4752},
             183: {836, 1174, 1899, 2047, 2295, 3155, 3307, 3340, 3476, 3587},
             184: {3374, 3897, 3981, 4162, 4591, 4637, 4865, 4942, 4946, 5027},
             185: {61, 491, 516, 627, 776, 993, 1052, 1465, 1658, 1921},
             186: {1421, 1559, 1713, 1854, 2406, 2572, 2599, 2624, 2703, 2844},
             187: {0, 302, 885, 2168, 2233, 2309, 4015, 4599, 5053, 5295},
             188: {146, 367, 582, 1383, 2346, 3041, 3282, 3381, 3756, 3764},
             189: {311, 415, 2105, 2327, 3016, 3060, 3209, 3524, 3670, 3744},
             190: {13, 1445, 2104, 4196, 4353, 4490, 4518, 4531, 4621, 4786},
             191: {978, 1121, 1529, 1559, 1606, 1653, 1845, 1857, 2096, 2339},
             192: {1571, 1731, 2673, 3594, 3806, 4418, 4447, 4456, 5127, 5129},
             193: {169, 468, 809, 1759, 2093, 2964, 4585, 4643, 4772, 4941},
             194: {191, 1036, 1066, 1121, 1218, 1624, 1653, 1931, 2010, 2130},
             195: {645, 659, 906, 1471, 1836, 2054, 2088, 2254, 2571, 3195},
             196: {501, 570, 1013, 1103, 1523, 1750, 2687, 2887, 3003, 3373},
             197: {125, 3162, 3611, 4003, 4067, 4204, 4275, 4583, 4616, 5057},
             198: {474, 476, 709, 1787, 1825, 2161, 2222, 2413, 2650, 2715},
             199: {92, 229, 574, 857, 1265, 1276, 1844, 2944, 3188, 3399},
             200: {274, 820, 1342, 1750, 1790, 2180, 2194, 2196, 2778, 3397},
             201: {551, 590, 925, 1164, 1702, 3631, 4076, 4421, 4703, 5144},
             202: {406, 1034, 1153, 1204, 3017, 3108, 3519, 3638, 3812, 4271},
             203: {676, 1990, 2490, 3421, 3505, 3891, 3979, 4189, 4208, 5127},
             204: {374, 1302, 2049, 3150, 3720, 3801, 4067, 4469, 4658, 5012},
             205: {149, 742, 3156, 3724, 4108, 4192, 4230, 5124, 5125, 5126},
             206: {129, 1039, 1108, 1377, 1686, 1766, 2023, 2096, 2349, 2572},
             207: {115, 587, 657, 1085, 1473, 1593, 2139, 2707, 2940, 3297},
             208: {672, 762, 1210, 1364, 1439, 2412, 2753, 3124, 4198, 4322},
             209: {563, 870, 1046, 1228, 1260, 1560, 1824, 1959, 1982, 2276},
             210: {551, 590, 816, 1532, 1618, 2023, 2349, 2599, 4231, 4793},
             211: {14, 647, 700, 819, 2261, 3368, 3609, 3750, 3898, 3939},
             212: {118, 126, 138, 150, 453, 1731, 2841, 3143, 3273, 3793},
             213: {3015, 3483, 3603, 3701, 4257, 4406, 4543, 4617, 4798, 4800},
             214: {41, 115, 313, 1201, 1895, 2077, 2139, 2538, 3051, 3297},
             215: {1388, 2648, 3293, 3504, 3869, 4472, 4488, 4863, 5053, 5079},
             216: {206, 387, 1175, 1377, 1766, 2023, 2096, 2406, 2572, 2624},
             217: {263, 346, 700, 819, 1160, 1383, 1388, 2767, 4404, 4836},
             218: {475, 594, 716, 1374, 2099, 4128, 4535, 4569, 4674, 5027},
             219: {28, 40, 168, 250, 753, 821, 1882, 1944, 2118, 2418},
             220: {17, 614, 1090, 1548, 1694, 1969, 2063, 2259, 2267, 2325},
             221: {60, 627, 783, 810, 1494, 1522, 1598, 1969, 2217, 2366},
             222: {429, 431, 516, 588, 649, 1392, 2075, 2364, 2421, 2422},
             223: {275, 324, 877, 3052, 4277, 5287, 5339, 5353, 5373, 5389},
             224: {607, 2340, 2499, 2739, 3026, 3036, 3119, 3133, 3207, 3421},
             225: {1264, 1507, 3125, 3473, 3893, 3999, 4019, 4200, 4214, 4226},
             226: {1280, 4731, 4917, 4990, 5297, 5302, 5304, 5305, 5316, 5334},
             227: {2704, 3836, 4180, 4199, 4219, 4352, 4568, 4581, 4619, 4707},
             228: {195, 645, 1004, 1471, 1836, 2571, 3195, 3348, 3370, 3372},
             229: {199, 574, 1265, 1276, 1377, 1844, 2096, 2349, 2944, 3154},
             230: {520, 2401, 3752, 4276, 4728, 4952, 4953, 4954, 4993, 5073},
             231: {40, 172, 1108, 1377, 1479, 1757, 2023, 2096, 2349, 2572},
             232: {112, 219, 250, 1059, 1263, 1304, 1377, 1605, 2118, 2418},
             233: {674, 1269, 1381, 3443, 3531, 3541, 3597, 3613, 3848, 4341},
             234: {116, 330, 350, 413, 444, 850, 1669, 2157, 2171, 2454},
             235: {139, 302, 1343, 2206, 2362, 3287, 4003, 4141, 4905, 4924},
             236: {320, 3863, 4305, 4566, 4667, 4695, 4757, 4770, 4849, 4986},
             237: {40, 753, 821, 1227, 1882, 1944, 2118, 2198, 2301, 2855},
             238: {976, 2359, 3164, 3912, 3924, 3938, 3950, 4145, 4181, 4195},
             239: {752, 760, 898, 1227, 1618, 1882, 1942, 2005, 2530, 2833},
             240: {1002, 1152, 1283, 1466, 1521, 1684, 1790, 2505, 2752, 3042},
             241: {315, 489, 553, 753, 1244, 1479, 1605, 2339, 2418, 2453},
             242: {422, 677, 2613, 3194, 4373, 4506, 4613, 4620, 4691, 5140},
             243: {490, 768, 1101, 1485, 1591, 2128, 2265, 2629, 2663, 3527},
             244: {44, 107, 310, 311, 312, 1325, 3202, 3525, 3550, 4852},
             245: {54, 587, 1594, 1709, 2159, 2471, 2699, 2706, 2786, 2990},
             246: {112, 232, 239, 760, 1059, 1377, 1657, 2092, 2136, 2418},
             247: {334, 462, 578, 1281, 1443, 2808, 2934, 3746, 3823, 4135},
             248: {374, 4144, 4491, 4492, 4493, 4735, 4816, 4949, 4955, 5269},
             249: {256, 446, 3165, 3626, 3866, 4058, 4131, 4255, 4294, 4324},
             250: {28, 168, 219, 251, 343, 383, 1882, 1944, 2118, 2528},
             251: {28, 219, 239, 250, 343, 752, 1618, 1882, 1942, 3180},
             252: {529, 584, 1061, 1418, 1482, 1507, 3133, 3223, 3422, 3463},
             253: {294, 1156, 1690, 4641, 4659, 4787, 5048, 5113, 5114, 5387},
             254: {314, 2665, 2670, 3348, 3411, 3905, 4107, 4147, 4883, 5017},
             255: {9, 99, 147, 671, 1333, 2669, 3612, 4333, 4431, 4815},
             256: {225, 584, 1507, 2208, 3125, 3735, 3999, 4065, 4085, 4200},
             257: {32, 833, 1622, 2522, 3937, 4576, 4595, 4786, 4789, 4808},
             258: {1139, 2382, 2466, 2505, 2587, 2721, 2770, 2771, 2835, 3554},
             259: {61, 773, 988, 1052, 1190, 1259, 1394, 1418, 1831, 4309},

In [62]:
# Specify the path to your pickle file
pickle_file_path = f"{PROCESSED_FILE_DIR}/TrustWorthy_FH_MAGrec.pickle"

# Open the pickle file in read binary mode
with open(pickle_file_path, 'rb') as file:
    # Load the data from the pickle file
    loaded_data = pickle.load(file)

In [63]:
history_u_lists, history_ur_lists, history_v_lists, history_vr_lists, train_u, train_v, train_r, test_u, test_v, test_r, social_adj_lists, ratings_list=loaded_data

In [64]:
social_adj_lists=top_trustworthy_similar_users

In [65]:
social_adj_lists

defaultdict(set,
            {0: {977, 1300, 1343, 1623, 1681, 4227, 4858, 4888, 4976, 5205},
             1: {2902, 3160, 3647, 3824, 4589, 4642, 4832, 5165, 5225, 5345},
             2: {769, 3295, 4133, 4153, 4260, 4309, 4334, 4394, 4452, 4458},
             3: {9, 420, 744, 1431, 1489, 1572, 2626, 3395, 4794, 4995},
             4: {253, 610, 716, 1156, 1690, 4641, 4787, 5048, 5113, 5114},
             5: {9, 789, 792, 840, 844, 1122, 1333, 2056, 2812, 3068},
             6: {54, 245, 587, 1594, 1644, 1709, 2159, 2699, 2706, 2786},
             7: {888, 1182, 1293, 1375, 1572, 1697, 1927, 2452, 3375, 3883},
             8: {9, 470, 744, 1107, 1526, 2060, 2182, 2291, 2580, 2626},
             9: {789, 792, 840, 844, 888, 1122, 1132, 1145, 1333, 1431},
             10: {518, 610, 876, 3194, 4542, 4655, 4972, 5183, 5288, 5350},
             11: {551, 1164, 1478, 1532, 3631, 4422, 4547, 4702, 4703, 4793},
             12: {1042, 1206, 2239, 2335, 2542, 2603, 2716, 4101, 4190, 4507},
             13: {72, 441, 981, 4353, 4430, 4518, 4531, 4596, 4621, 5191},
             14: {512, 524, 647, 672, 700, 819, 3343, 3939, 4188, 4972},
             15: {32, 3009, 3805, 4353, 4490, 4518, 4531, 4596, 4621, 5191},
             16: {45, 122, 508, 4350, 5116, 5138, 5346, 5367, 5388, 5391},
             17: {697, 744, 1200, 1572, 1813, 2182, 2291, 2580, 2626, 3198},
             18: {669, 724, 1125, 1327, 1557, 1570, 1689, 2210, 2450, 2624},
             19: {402, 1128, 1266, 1524, 1686, 1758, 2096, 2138, 2572, 2703},
             20: {58, 102, 2792, 3791, 4024, 4094, 4535, 4752, 4823, 4899},
             21: {72, 851, 940, 1080, 1102, 1393, 2188, 4596, 4859, 5191},
             22: {139, 235, 302, 346, 374, 1160, 2362, 2758, 4880, 4885},
             23: {89, 374, 2049, 3801, 3992, 4102, 4454, 4711, 5012, 5120},
             24: {771, 824, 1240, 1313, 1368, 1372, 1475, 1860, 1884, 2269},
             25: {723, 764, 814, 948, 984, 1528, 1586, 1593, 1619, 2053},
             26: {45, 579, 1695, 4670, 4902, 4927, 5206, 5289, 5346, 5388},
             27: {139, 223, 877, 4277, 5053, 5067, 5353, 5368, 5373, 5380},
             28: {168, 250, 251, 343, 752, 1618, 1882, 1942, 1944, 1958},
             29: {77, 898, 1026, 1251, 1942, 2005, 3143, 3180, 3331, 3556},
             30: {3118, 4406, 4679, 4680, 4681, 4682, 4683, 4684, 4775, 4797},
             31: {191, 268, 366, 993, 1700, 1749, 1845, 1898, 1916, 2069},
             32: {1622, 2522, 4576, 4786, 4789, 4998, 5000, 5044, 5047, 5049},
             33: {56, 81, 395, 1054, 1100, 1474, 2344, 3351, 4722, 4723},
             34: {1499, 2879, 3156, 4108, 4553, 4887, 5080, 5085, 5124, 5126},
             35: {256, 1052, 1259, 1418, 1674, 2421, 2422, 3125, 3165, 3486},
             36: {330, 350, 413, 526, 627, 872, 1155, 1658, 1831, 1871},
             37: {1107, 1351, 1489, 1675, 2039, 2568, 3212, 3446, 3808, 3896},
             38: {549, 981, 1692, 4353, 4430, 4518, 4596, 4621, 4772, 4786},
             39: {1532, 4139, 4231, 4515, 4670, 4793, 5115, 5144, 5234, 5397},
             40: {687, 821, 1627, 1943, 1944, 1946, 1947, 1958, 2118, 2855},
             41: {40, 66, 239, 687, 760, 898, 1618, 1942, 2005, 3180},
             42: {4368, 4491, 4492, 4493, 4626, 4650, 4816, 4915, 4956, 5062},
             43: {296, 619, 754, 999, 1040, 1076, 2056, 2711, 2730, 3068},
             44: {167, 244, 310, 311, 1381, 1383, 2105, 3172, 3202, 3270},
             45: {16, 122, 1991, 4932, 5116, 5138, 5320, 5346, 5367, 5388},
             46: {583, 2372, 2542, 3441, 3816, 4747, 4844, 4990, 5040, 5098},
             47: {623, 1243, 2380, 3547, 3672, 3673, 3674, 3676, 3678, 3686},
             48: {28, 752, 829, 1618, 1882, 1942, 2005, 2528, 2662, 3180},
             49: {37, 128, 635, 1289, 1306, 1307, 1432, 1773, 1827, 2399},
             50: {255, 479, 671, 789, 840, 844, 1927, 3096, 3170, 3896},
             51: {293, 549, 2178, 2879, 4641, 5080, 5085, 5125, 5126, 5218},
             52: {564, 1133, 1569, 2297, 2745, 2854, 3077, 3124, 3329, 3831},
             53: {369, 928, 941, 1999, 2664, 4041, 4334, 4360, 4411, 4474},
             54: {245, 587, 1594, 1709, 2159, 2471, 2699, 2706, 2786, 2990},
             55: {850, 1126, 2529, 2614, 2702, 2749, 2834, 3034, 3122, 3141},
             56: {334, 578, 708, 1295, 1404, 2808, 2934, 3427, 3746, 3843},
             57: {829, 1618, 1840, 1942, 2418, 2803, 3143, 3180, 3516, 3556},
             58: {102, 2792, 3791, 4024, 4094, 4535, 4717, 4752, 4823, 4899},
             59: {426, 443, 577, 646, 1143, 1323, 1426, 2199, 2505, 2685},
             60: {221, 349, 536, 588, 654, 704, 783, 1058, 1753, 2228},
             61: {318, 773, 988, 1052, 1190, 1394, 1418, 1831, 3422, 3463},
             62: {606, 3182, 3216, 3425, 4031, 4207, 4295, 4373, 4506, 4622},
             63: {21, 72, 128, 132, 163, 265, 448, 1662, 4490, 4531},
             64: {118, 157, 386, 453, 1868, 2346, 3209, 3314, 3600, 4217},
             65: {820, 860, 945, 1093, 1187, 1508, 1515, 1804, 1987, 2111},
             66: {40, 343, 687, 753, 821, 1347, 1882, 1924, 1943, 1945},
             67: {3, 9, 227, 742, 1523, 2168, 3724, 3783, 3825, 4104},
             68: {265, 323, 446, 711, 2658, 3521, 3856, 4514, 4531, 4643},
             69: {107, 244, 310, 312, 2105, 3525, 3550, 3872, 4758, 4852},
             70: {484, 1466, 1506, 2006, 2042, 2091, 2494, 2986, 3865, 4911},
             71: {644, 1117, 1268, 2067, 2174, 2304, 2347, 2385, 2442, 3099},
             72: {21, 1095, 4353, 4430, 4518, 4531, 4552, 4596, 4621, 5191},
             73: {76, 283, 981, 2446, 2980, 4730, 4939, 5009, 5317, 5341},
             74: {90, 169, 960, 1314, 1421, 1887, 2115, 4643, 4890, 5004},
             75: {186, 1083, 1531, 1673, 1710, 1924, 1945, 2749, 2841, 3294},
             76: {73, 283, 981, 2980, 4730, 4939, 5009, 5191, 5317, 5341},
             77: {29, 829, 3143, 3793, 3854, 3966, 4103, 4418, 4423, 4447},
             78: {688, 2070, 3871, 4281, 4945, 4947, 4985, 5084, 5150, 5250},
             79: {1502, 1742, 2154, 2249, 2281, 2328, 2949, 3020, 3024, 3289},
             80: {628, 814, 943, 948, 984, 1002, 1152, 1473, 1562, 1593},
             81: {33, 56, 395, 1100, 3351, 4158, 4722, 4723, 4848, 4913},
             82: {100, 157, 340, 453, 1324, 1981, 3760, 3890, 4088, 4109},
             83: {133, 332, 590, 1164, 2378, 4432, 4481, 4547, 5144, 5321},
             84: {498, 1922, 3449, 4527, 4579, 4733, 5042, 5164, 5169, 5325},
             85: {904, 1125, 1227, 1251, 1499, 1962, 2237, 2599, 3143, 3556},
             86: {253, 442, 499, 1320, 1885, 2001, 3009, 4659, 4944, 5162},
             87: {321, 660, 718, 790, 915, 1501, 2027, 2258, 2434, 2724},
             88: {171, 325, 727, 1376, 1467, 3257, 3803, 4872, 5318, 5344},
             89: {3354, 3646, 4078, 4093, 4550, 4617, 4711, 4724, 4918, 5012},
             90: {32, 1622, 4467, 4789, 4998, 5000, 5003, 5044, 5047, 5079},
             91: {89, 749, 847, 1257, 2399, 4379, 4406, 4617, 4762, 4933},
             92: {145, 237, 239, 383, 553, 760, 1227, 1944, 2118, 2530},
             93: {4398, 4408, 4500, 4591, 4598, 4639, 4656, 4697, 4768, 4865},
             94: {95, 1701, 2367, 3442, 3839, 3851, 3999, 4019, 4069, 4226},
             95: {94, 1561, 1701, 2367, 3442, 3851, 3999, 4019, 4069, 4226},
             96: {361, 695, 995, 1245, 1382, 1542, 1561, 2211, 2289, 2500},
             97: {41, 92, 232, 268, 581, 904, 1056, 1059, 1585, 1812},
             98: {343, 752, 816, 1377, 1618, 1882, 2023, 2096, 2349, 2889},
             99: {255, 420, 1333, 1338, 1431, 3261, 3395, 4484, 4746, 4790},
             100: {82, 340, 1324, 1420, 1981, 3578, 3760, 3890, 3966, 4088},
             101: {4111, 4333, 4431, 4660, 5054, 5122, 5200, 5253, 5271, 5324},
             102: {58, 2792, 3791, 4024, 4094, 4535, 4717, 4752, 4823, 4899},
             103: {372, 538, 572, 607, 1235, 1846, 1919, 2083, 2630, 3884},
             104: {1066, 1215, 1323, 1396, 1931, 1948, 3013, 3541, 3619, 3923},
             105: {83, 857, 1135, 1799, 3370, 3425, 3566, 3892, 4580, 5331},
             106: {662, 1257, 2792, 3791, 4094, 4565, 4717, 4752, 4823, 4899},
             107: {69, 244, 310, 312, 3525, 3550, 4415, 4758, 4779, 4852},
             108: {176, 569, 723, 943, 948, 1593, 1714, 2084, 2268, 2271},
             109: {477, 878, 1107, 1434, 1489, 1675, 4114, 4889, 4933, 4970},
             110: {3691, 3906, 3917, 3918, 3931, 3942, 3957, 4247, 4248, 4891},
             111: {116, 596, 628, 814, 943, 948, 984, 1002, 1437, 1593},
             112: {219, 232, 250, 251, 366, 816, 1304, 1605, 2418, 2576},
             113: {162, 619, 1076, 1103, 1322, 1720, 1852, 2694, 2919, 3074},
             114: {27, 877, 977, 1300, 1681, 2090, 3741, 3769, 4227, 4976},
             115: {901, 920, 939, 1123, 1497, 1820, 1849, 1883, 2073, 2185},
             116: {328, 330, 596, 628, 680, 814, 900, 984, 1593, 2312},
             117: {1078, 1634, 2666, 3023, 3171, 3398, 3434, 3506, 3509, 3551},
             118: {77, 212, 2803, 3945, 3966, 4103, 4217, 4390, 4421, 4423},
             119: {1098, 1655, 3543, 3611, 3717, 4516, 4844, 5107, 5143, 5163},
             120: {450, 693, 763, 876, 1960, 2695, 3194, 3922, 4613, 4972},
             121: {457, 2201, 3500, 4362, 4410, 4510, 4597, 4755, 4762, 4889},
             122: {16, 45, 579, 2627, 4925, 5116, 5138, 5346, 5367, 5388},
             123: {436, 1008, 1640, 1886, 2897, 3171, 3196, 3398, 3434, 3506},
             124: {5, 9, 336, 697, 1132, 1145, 1333, 1431, 1813, 2540},
             125: {1923, 2127, 4003, 4204, 4304, 4459, 4562, 4616, 4690, 4983},
             126: {874, 1114, 1286, 2014, 2066, 2481, 3196, 3273, 3571, 3671},
             127: {268, 753, 1263, 1700, 1898, 1916, 1940, 1944, 1946, 2118},
             128: {163, 924, 1289, 1306, 1307, 1393, 1861, 2446, 3075, 3275},
             129: {206, 710, 1108, 1377, 1766, 2096, 2406, 2526, 2572, 2814},
             130: {169, 1445, 4091, 4353, 4522, 4595, 4621, 4786, 5002, 5003},
             131: {57, 802, 960, 1322, 1433, 1449, 1710, 3135, 3245, 3273},
             132: {63, 128, 1393, 1625, 1815, 1901, 2586, 2593, 2775, 2779},
             133: {551, 1532, 3448, 3631, 4422, 4432, 4558, 4702, 4703, 5066},
             134: {752, 1618, 1786, 1882, 1942, 1943, 1945, 1946, 1947, 2833},
             135: {777, 1046, 1838, 2044, 2110, 2262, 2288, 2296, 2397, 2539},
             136: {583, 893, 2542, 3441, 3816, 4747, 4844, 4938, 5040, 5098},
             137: {294, 1690, 2049, 3606, 3996, 4097, 4332, 4641, 5086, 5114},
             138: {48, 251, 829, 1026, 1251, 2003, 2005, 3143, 3180, 3265},
             139: {235, 302, 2362, 2758, 4004, 4528, 4752, 4833, 5053, 5067},
             140: {479, 671, 896, 2995, 3194, 3284, 3907, 4063, 4613, 5012},
             141: {789, 792, 793, 840, 844, 1107, 2056, 2060, 2711, 2800},
             142: {41, 313, 633, 1404, 1585, 1883, 2139, 3051, 3297, 3322},
             143: {753, 1096, 1367, 1627, 1768, 2198, 2514, 2572, 2991, 3239},
             144: {92, 543, 751, 1594, 1709, 2198, 2512, 2662, 2706, 2855},
             145: {250, 383, 556, 1227, 1401, 2528, 2662, 2921, 3265, 3385},
             146: {714, 952, 956, 1210, 1360, 1398, 3286, 3795, 3972, 4351},
             147: {3612, 4333, 4398, 4431, 4591, 4637, 4746, 4790, 4815, 4869},
             148: {824, 1064, 1112, 1288, 1354, 1361, 1475, 2770, 2771, 3587},
             149: {58, 2792, 3791, 4024, 4094, 4535, 4717, 4752, 4823, 4899},
             150: {29, 77, 126, 212, 304, 436, 1961, 2003, 3273, 3923},
             151: {38, 374, 549, 968, 1651, 1775, 2665, 2748, 2980, 3112},
             152: {289, 692, 1085, 1414, 1429, 2531, 2707, 2997, 3228, 3508},
             153: {729, 754, 985, 1078, 1634, 1640, 1886, 2087, 2774, 3023},
             154: {901, 920, 1143, 2073, 2138, 2538, 2650, 2808, 3112, 3347},
             155: {2387, 3052, 3305, 4440, 4730, 4830, 5034, 5317, 5341, 5378},
             156: {145, 556, 1011, 1157, 1370, 1738, 3314, 3371, 3394, 3486},
             157: {64, 796, 832, 1041, 2249, 2752, 2899, 2912, 3193, 3209},
             158: {2420, 2457, 2503, 2639, 2822, 3025, 3102, 3213, 3247, 3300},
             159: {627, 800, 900, 1052, 1418, 1547, 1658, 1993, 2382, 3120},
             160: {424, 1281, 1903, 2516, 2630, 2945, 3244, 3508, 3847, 4394},
             161: {551, 610, 1164, 3631, 4421, 4422, 4542, 4559, 4703, 5288},
             162: {1373, 1538, 2037, 2230, 2850, 2955, 2976, 3000, 3020, 3132},
             163: {21, 72, 128, 1393, 1901, 2754, 2775, 2779, 3294, 3367},
             164: {583, 1100, 4207, 4629, 4640, 4722, 4723, 4791, 4844, 4938},
             165: {88, 727, 1376, 1467, 1727, 3257, 3431, 4872, 5318, 5344},
             166: {695, 868, 995, 1245, 1542, 1561, 2014, 2135, 4066, 4069},
             167: {44, 311, 415, 1383, 2105, 2895, 3202, 3212, 3270, 3510},
             168: {28, 219, 250, 251, 343, 383, 1882, 1944, 1958, 2528},
             169: {130, 190, 441, 4353, 4522, 4595, 4596, 4621, 4643, 5004},
             170: {490, 1058, 1248, 1392, 1450, 1629, 2286, 2469, 3353, 3694},
             171: {88, 1467, 3257, 3803, 3853, 4210, 4291, 4879, 5318, 5344},
             172: {168, 219, 231, 250, 753, 1377, 1479, 1767, 1944, 2118},
             173: {30, 125, 355, 1923, 2127, 3948, 4336, 4406, 4516, 4616},
             174: {117, 648, 985, 1078, 2444, 2567, 3023, 3171, 3232, 3551},
             175: {36, 185, 490, 516, 1450, 1494, 1577, 1919, 1925, 2139},
             176: {116, 569, 723, 814, 1528, 1593, 1619, 1809, 2084, 2298},
             177: {384, 408, 908, 1270, 4029, 4031, 4149, 4419, 4456, 4672},
             178: {213, 631, 781, 794, 2627, 2665, 3411, 3882, 3905, 4638},
             179: {4141, 4442, 4500, 4617, 4639, 4656, 4718, 4768, 4820, 5012},
             180: {311, 991, 1374, 1557, 2034, 2134, 2172, 2282, 2360, 2827},
             181: {901, 920, 939, 1497, 1820, 1849, 1883, 2073, 2185, 2468},
             182: {58, 102, 2232, 2792, 3791, 4022, 4024, 4094, 4535, 4752},
             183: {836, 1174, 1899, 2047, 2295, 3155, 3307, 3340, 3476, 3587},
             184: {3374, 3897, 3981, 4162, 4591, 4637, 4865, 4942, 4946, 5027},
             185: {61, 491, 516, 627, 776, 993, 1052, 1465, 1658, 1921},
             186: {1421, 1559, 1713, 1854, 2406, 2572, 2599, 2624, 2703, 2844},
             187: {0, 302, 885, 2168, 2233, 2309, 4015, 4599, 5053, 5295},
             188: {146, 367, 582, 1383, 2346, 3041, 3282, 3381, 3756, 3764},
             189: {311, 415, 2105, 2327, 3016, 3060, 3209, 3524, 3670, 3744},
             190: {13, 1445, 2104, 4196, 4353, 4490, 4518, 4531, 4621, 4786},
             191: {978, 1121, 1529, 1559, 1606, 1653, 1845, 1857, 2096, 2339},
             192: {1571, 1731, 2673, 3594, 3806, 4418, 4447, 4456, 5127, 5129},
             193: {169, 468, 809, 1759, 2093, 2964, 4585, 4643, 4772, 4941},
             194: {191, 1036, 1066, 1121, 1218, 1624, 1653, 1931, 2010, 2130},
             195: {645, 659, 906, 1471, 1836, 2054, 2088, 2254, 2571, 3195},
             196: {501, 570, 1013, 1103, 1523, 1750, 2687, 2887, 3003, 3373},
             197: {125, 3162, 3611, 4003, 4067, 4204, 4275, 4583, 4616, 5057},
             198: {474, 476, 709, 1787, 1825, 2161, 2222, 2413, 2650, 2715},
             199: {92, 229, 574, 857, 1265, 1276, 1844, 2944, 3188, 3399},
             200: {274, 820, 1342, 1750, 1790, 2180, 2194, 2196, 2778, 3397},
             201: {551, 590, 925, 1164, 1702, 3631, 4076, 4421, 4703, 5144},
             202: {406, 1034, 1153, 1204, 3017, 3108, 3519, 3638, 3812, 4271},
             203: {676, 1990, 2490, 3421, 3505, 3891, 3979, 4189, 4208, 5127},
             204: {374, 1302, 2049, 3150, 3720, 3801, 4067, 4469, 4658, 5012},
             205: {149, 742, 3156, 3724, 4108, 4192, 4230, 5124, 5125, 5126},
             206: {129, 1039, 1108, 1377, 1686, 1766, 2023, 2096, 2349, 2572},
             207: {115, 587, 657, 1085, 1473, 1593, 2139, 2707, 2940, 3297},
             208: {672, 762, 1210, 1364, 1439, 2412, 2753, 3124, 4198, 4322},
             209: {563, 870, 1046, 1228, 1260, 1560, 1824, 1959, 1982, 2276},
             210: {551, 590, 816, 1532, 1618, 2023, 2349, 2599, 4231, 4793},
             211: {14, 647, 700, 819, 2261, 3368, 3609, 3750, 3898, 3939},
             212: {118, 126, 138, 150, 453, 1731, 2841, 3143, 3273, 3793},
             213: {3015, 3483, 3603, 3701, 4257, 4406, 4543, 4617, 4798, 4800},
             214: {41, 115, 313, 1201, 1895, 2077, 2139, 2538, 3051, 3297},
             215: {1388, 2648, 3293, 3504, 3869, 4472, 4488, 4863, 5053, 5079},
             216: {206, 387, 1175, 1377, 1766, 2023, 2096, 2406, 2572, 2624},
             217: {263, 346, 700, 819, 1160, 1383, 1388, 2767, 4404, 4836},
             218: {475, 594, 716, 1374, 2099, 4128, 4535, 4569, 4674, 5027},
             219: {28, 40, 168, 250, 753, 821, 1882, 1944, 2118, 2418},
             220: {17, 614, 1090, 1548, 1694, 1969, 2063, 2259, 2267, 2325},
             221: {60, 627, 783, 810, 1494, 1522, 1598, 1969, 2217, 2366},
             222: {429, 431, 516, 588, 649, 1392, 2075, 2364, 2421, 2422},
             223: {275, 324, 877, 3052, 4277, 5287, 5339, 5353, 5373, 5389},
             224: {607, 2340, 2499, 2739, 3026, 3036, 3119, 3133, 3207, 3421},
             225: {1264, 1507, 3125, 3473, 3893, 3999, 4019, 4200, 4214, 4226},
             226: {1280, 4731, 4917, 4990, 5297, 5302, 5304, 5305, 5316, 5334},
             227: {2704, 3836, 4180, 4199, 4219, 4352, 4568, 4581, 4619, 4707},
             228: {195, 645, 1004, 1471, 1836, 2571, 3195, 3348, 3370, 3372},
             229: {199, 574, 1265, 1276, 1377, 1844, 2096, 2349, 2944, 3154},
             230: {520, 2401, 3752, 4276, 4728, 4952, 4953, 4954, 4993, 5073},
             231: {40, 172, 1108, 1377, 1479, 1757, 2023, 2096, 2349, 2572},
             232: {112, 219, 250, 1059, 1263, 1304, 1377, 1605, 2118, 2418},
             233: {674, 1269, 1381, 3443, 3531, 3541, 3597, 3613, 3848, 4341},
             234: {116, 330, 350, 413, 444, 850, 1669, 2157, 2171, 2454},
             235: {139, 302, 1343, 2206, 2362, 3287, 4003, 4141, 4905, 4924},
             236: {320, 3863, 4305, 4566, 4667, 4695, 4757, 4770, 4849, 4986},
             237: {40, 753, 821, 1227, 1882, 1944, 2118, 2198, 2301, 2855},
             238: {976, 2359, 3164, 3912, 3924, 3938, 3950, 4145, 4181, 4195},
             239: {752, 760, 898, 1227, 1618, 1882, 1942, 2005, 2530, 2833},
             240: {1002, 1152, 1283, 1466, 1521, 1684, 1790, 2505, 2752, 3042},
             241: {315, 489, 553, 753, 1244, 1479, 1605, 2339, 2418, 2453},
             242: {422, 677, 2613, 3194, 4373, 4506, 4613, 4620, 4691, 5140},
             243: {490, 768, 1101, 1485, 1591, 2128, 2265, 2629, 2663, 3527},
             244: {44, 107, 310, 311, 312, 1325, 3202, 3525, 3550, 4852},
             245: {54, 587, 1594, 1709, 2159, 2471, 2699, 2706, 2786, 2990},
             246: {112, 232, 239, 760, 1059, 1377, 1657, 2092, 2136, 2418},
             247: {334, 462, 578, 1281, 1443, 2808, 2934, 3746, 3823, 4135},
             248: {374, 4144, 4491, 4492, 4493, 4735, 4816, 4949, 4955, 5269},
             249: {256, 446, 3165, 3626, 3866, 4058, 4131, 4255, 4294, 4324},
             250: {28, 168, 219, 251, 343, 383, 1882, 1944, 2118, 2528},
             251: {28, 219, 239, 250, 343, 752, 1618, 1882, 1942, 3180},
             252: {529, 584, 1061, 1418, 1482, 1507, 3133, 3223, 3422, 3463},
             253: {294, 1156, 1690, 4641, 4659, 4787, 5048, 5113, 5114, 5387},
             254: {314, 2665, 2670, 3348, 3411, 3905, 4107, 4147, 4883, 5017},
             255: {9, 99, 147, 671, 1333, 2669, 3612, 4333, 4431, 4815},
             256: {225, 584, 1507, 2208, 3125, 3735, 3999, 4065, 4085, 4200},
             257: {32, 833, 1622, 2522, 3937, 4576, 4595, 4786, 4789, 4808},
             258: {1139, 2382, 2466, 2505, 2587, 2721, 2770, 2771, 2835, 3554},
             259: {61, 773, 988, 1052, 1190, 1259, 1394, 1418, 1831, 4309},

In [66]:
import pickle
# Organize the variables into a tuple in the desired order
data_to_save = (history_u_lists, history_ur_lists, history_v_lists, history_vr_lists,
                train_u, train_v, train_r, test_u, test_v, test_r, social_adj_lists, ratings_list)

# Specify the path to save the pickle file
output_pickle_file_path = f"{PROCESSED_FILE_DIR}/FH_Trustworthy_Neighbors_0.6_threshold.pickle"

# Open the pickle file in write binary mode ('wb')
with open(output_pickle_file_path, 'wb') as file:
    # Dump the data to the pickle file
    pickle.dump(data_to_save, file)

print("Data saved to pickle file:", output_pickle_file_path)

Data saved to pickle file: /home/shoaib/recommender-system/royal/journal-revision/New/FH/processed-files/FH_Trustworthy_Neighbors_0.6_threshold.pickle

## Training

In [67]:
import torch
import torch.nn as nn
import pickle
import numpy as np
import argparse
import os
from UV_Encoders import UV_Encoder
from UV_Aggregators import UV_Aggregator
from Social_Encoders import Social_Encoder
from Social_Aggregators import Social_Aggregator


class GraphRec(nn.Module):
    def __init__(self, enc_u, enc_v_history, r2e):
        super(GraphRec, self).__init__()
        self.enc_u = enc_u
        self.enc_v_history = enc_v_history
        self.embed_dim = enc_u.embed_dim
        self.w_ur1 = nn.Linear(self.embed_dim, self.embed_dim)
        self.w_ur2 = nn.Linear(self.embed_dim, self.embed_dim)
        self.w_vr1 = nn.Linear(self.embed_dim, self.embed_dim)
        self.w_vr2 = nn.Linear(self.embed_dim, self.embed_dim)
        self.w_uv1 = nn.Linear(self.embed_dim * 2, self.embed_dim)
        self.w_uv2 = nn.Linear(self.embed_dim, 16)
        self.w_uv3 = nn.Linear(16, 1)
        self.r2e = r2e
        self.bn1 = nn.BatchNorm1d(self.embed_dim, momentum=0.5)
        self.bn2 = nn.BatchNorm1d(self.embed_dim, momentum=0.5)
        self.bn3 = nn.BatchNorm1d(self.embed_dim, momentum=0.5)
        self.bn4 = nn.BatchNorm1d(16, momentum=0.5)

    def forward(self, nodes_u, nodes_v):
        embeds_u = self.enc_u(nodes_u)
        embeds_v = self.enc_v_history(nodes_v)
        scores_u = torch.matmul(embeds_u, embeds_v.t())
        return scores_u.squeeze()

    def bpr_loss(self, nodes_u, nodes_v, device, num_items):
        scores_u = self.forward(nodes_u, nodes_v)
        nodes_v_negative = torch.randint(0, num_items, size=nodes_u.size(), dtype=torch.long).to(device)
        scores_u_negative = self.forward(nodes_u, nodes_v_negative)
        bpr_loss = -torch.log(torch.sigmoid(scores_u - scores_u_negative)).mean()
        return bpr_loss

def train(model, device, train_loader, optimizer, epoch, num_items):
    model.train()
    running_loss = 0.0
    for i, data in enumerate(train_loader, 0):
        batch_nodes_u, batch_nodes_v, _ = data
        optimizer.zero_grad()
        loss = model.bpr_loss(batch_nodes_u.to(device), batch_nodes_v.to(device), device, num_items)
        loss.backward(retain_graph=True)
        optimizer.step()
        running_loss += loss.item()
        if i % 100 == 0:
            print('[%d, %5d] loss: %.3f' % (epoch, i, running_loss / 100))
            running_loss = 0.0

def get_top_100_recommendations(model, device, test_loader, num_items, k=100):
    model.eval()
    user_recommendations_dict = {}  # Dictionary to store user recommendations

    with torch.no_grad():
        for test_u, test_v, _ in test_loader:
            test_u, test_v = test_u.to(device), test_v.to(device)
            scores = model.forward(test_u, test_v)
            scores = scores.squeeze().tolist()
            top_indices = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:k]

            user_ids = test_u.tolist()  # Convert tensor to list

            for user_id in user_ids:
                user_recommendations = [(rank, test_v[item_index].item()) for rank, item_index in enumerate(top_indices, start=1)]
                user_recommendations_dict[user_id] = user_recommendations

    return user_recommendations_dict




def main():
    parser = argparse.ArgumentParser(description='Social Recommendation: GraphRec model')
    parser.add_argument('--batch_size', type=int, default=128, metavar='N', help='input batch size for training')
    parser.add_argument('--embed_dim', type=int, default=64, metavar='N', help='embedding size')
    parser.add_argument('--lr', type=float, default=0.001, metavar='LR', help='learning rate')
    parser.add_argument('--test_batch_size', type=int, default=1000, metavar='N', help='input batch size for testing')
    parser.add_argument('--epochs', type=int, default=100, metavar='N', help='number of epochs to train')
    args, unknown = parser.parse_known_args()

    os.environ['CUDA_VISIBLE_DEVICES'] = '0'
    use_cuda = False
    if torch.cuda.is_available():
        use_cuda = True
    device = torch.device("cuda" if use_cuda else "cpu")

    embed_dim = args.embed_dim
    dir_data = f'{PROCESSED_FILE_DIR}/FH_Trustworthy_Neighbors_0.6_threshold'

    path_data = dir_data + ".pickle"
    data_file = open(path_data, 'rb')
    history_u_lists, history_ur_lists, history_v_lists, history_vr_lists, train_u, train_v, train_r, test_u, test_v, test_r, social_adj_lists, ratings_list = pickle.load(
        data_file)
    total_num_items = len(set(train_v + test_v))

    trainset = torch.utils.data.TensorDataset(torch.LongTensor(train_u), torch.LongTensor(train_v),
                                              torch.FloatTensor(train_r))
    testset = torch.utils.data.TensorDataset(torch.LongTensor(test_u), torch.LongTensor(test_v),
                                             torch.FloatTensor(test_r))
    train_loader = torch.utils.data.DataLoader(trainset, batch_size=args.batch_size, shuffle=True)
    test_loader = torch.utils.data.DataLoader(testset, batch_size=args.test_batch_size, shuffle=True)
    num_users = history_u_lists.__len__()
    num_items = history_v_lists.__len__()

    u2e = nn.Embedding(num_users, embed_dim).to(device)
    v2e = nn.Embedding(num_items, embed_dim).to(device)
    r2e = nn.Embedding(total_num_items, embed_dim).to(device)  # Define r2e with the correct number of ratings
    total_num_items = len(set(train_v + test_v))

    agg_u_history = UV_Aggregator(v2e, r2e, u2e, embed_dim, cuda=device, uv=True)
    enc_u_history = UV_Encoder(u2e, embed_dim, history_u_lists, history_ur_lists, agg_u_history, cuda=device, uv=True)
    agg_u_social = Social_Aggregator(lambda nodes: enc_u_history(nodes).t(), u2e, embed_dim, cuda=device)
    enc_u = Social_Encoder(lambda nodes: enc_u_history(nodes).t(), embed_dim, social_adj_lists, agg_u_social,
                           base_model=enc_u_history, cuda=device)

    agg_v_history = UV_Aggregator(v2e, r2e, u2e, embed_dim, cuda=device, uv=False)
    enc_v_history = UV_Encoder(v2e, embed_dim, history_v_lists, history_vr_lists, agg_v_history, cuda=device, uv=False)

    graphrec = GraphRec(enc_u, enc_v_history, r2e).to(device)
    optimizer = torch.optim.RMSprop(graphrec.parameters(), lr=args.lr, alpha=0.9)

    for epoch in range(1, args.epochs + 1):
        train(graphrec, device, train_loader, optimizer, epoch, total_num_items)

    top_100_recommendations = get_top_100_recommendations(graphrec, device, test_loader, num_items=total_num_items)

    # Print or use top_100_recommendations as needed
    return top_100_recommendations

if __name__ == "__main__":
    recommendation_list=main()

[1,     0] loss: 0.007
[1,   100] loss: 0.543
[1,   200] loss: 0.515
[1,   300] loss: 0.517
[1,   400] loss: 0.509
[1,   500] loss: 0.508
[1,   600] loss: 0.509
[1,   700] loss: 0.511
[1,   800] loss: 0.519
[2,     0] loss: 0.005
[2,   100] loss: 0.510
[2,   200] loss: 0.512
[2,   300] loss: 0.508
[2,   400] loss: 0.506
[2,   500] loss: 0.510
[2,   600] loss: 0.506
[2,   700] loss: 0.499
[2,   800] loss: 0.497
[3,     0] loss: 0.005
[3,   100] loss: 0.509
[3,   200] loss: 0.503
[3,   300] loss: 0.516
[3,   400] loss: 0.505
[3,   500] loss: 0.503
[3,   600] loss: 0.505
[3,   700] loss: 0.499
[3,   800] loss: 0.507
[4,     0] loss: 0.005
[4,   100] loss: 0.501
[4,   200] loss: 0.504
[4,   300] loss: 0.493
[4,   400] loss: 0.501
[4,   500] loss: 0.499
[4,   600] loss: 0.495
[4,   700] loss: 0.499
[4,   800] loss: 0.506
[5,     0] loss: 0.005
[5,   100] loss: 0.500
[5,   200] loss: 0.497
[5,   300] loss: 0.502
[5,   400] loss: 0.497
[5,   500] loss: 0.492
[5,   600] loss: 0.505
[5,   700] loss: 0.494
[5,   800] loss: 0.506
[6,     0] loss: 0.007
[6,   100] loss: 0.501
[6,   200] loss: 0.499
[6,   300] loss: 0.497
[6,   400] loss: 0.489
[6,   500] loss: 0.510
[6,   600] loss: 0.496
[6,   700] loss: 0.496
[6,   800] loss: 0.509
[7,     0] loss: 0.005
[7,   100] loss: 0.492
[7,   200] loss: 0.501
[7,   300] loss: 0.513
[7,   400] loss: 0.503
[7,   500] loss: 0.500
[7,   600] loss: 0.500
[7,   700] loss: 0.507
[7,   800] loss: 0.495
[8,     0] loss: 0.005
[8,   100] loss: 0.493
[8,   200] loss: 0.494
[8,   300] loss: 0.498
[8,   400] loss: 0.503
[8,   500] loss: 0.501
[8,   600] loss: 0.498
[8,   700] loss: 0.503
[8,   800] loss: 0.499
[9,     0] loss: 0.004
[9,   100] loss: 0.505
[9,   200] loss: 0.514
[9,   300] loss: 0.498
[9,   400] loss: 0.503
[9,   500] loss: 0.495
[9,   600] loss: 0.497
[9,   700] loss: 0.499
[9,   800] loss: 0.502
[10,     0] loss: 0.005
[10,   100] loss: 0.501
[10,   200] loss: 0.500
[10,   300] loss: 0.496
[10,   400] loss: 0.499
[10,   500] loss: 0.501
[10,   600] loss: 0.510
[10,   700] loss: 0.496
[10,   800] loss: 0.499
[11,     0] loss: 0.005
[11,   100] loss: 0.494
[11,   200] loss: 0.508
[11,   300] loss: 0.500
[11,   400] loss: 0.503
[11,   500] loss: 0.501
[11,   600] loss: 0.494
[11,   700] loss: 0.499
[11,   800] loss: 0.502
[12,     0] loss: 0.004
[12,   100] loss: 0.496
[12,   200] loss: 0.497
[12,   300] loss: 0.503
[12,   400] loss: 0.501
[12,   500] loss: 0.502
[12,   600] loss: 0.502
[12,   700] loss: 0.507
[12,   800] loss: 0.500
[13,     0] loss: 0.005
[13,   100] loss: 0.492
[13,   200] loss: 0.497
[13,   300] loss: 0.494
[13,   400] loss: 0.504
[13,   500] loss: 0.502
[13,   600] loss: 0.496
[13,   700] loss: 0.494
[13,   800] loss: 0.503
[14,     0] loss: 0.006
[14,   100] loss: 0.492
[14,   200] loss: 0.493
[14,   300] loss: 0.504
[14,   400] loss: 0.498
[14,   500] loss: 0.504
[14,   600] loss: 0.507
[14,   700] loss: 0.507
[14,   800] loss: 0.500
[15,     0] loss: 0.005
[15,   100] loss: 0.503
[15,   200] loss: 0.495
[15,   300] loss: 0.497
[15,   400] loss: 0.497
[15,   500] loss: 0.502
[15,   600] loss: 0.504
[15,   700] loss: 0.496
[15,   800] loss: 0.502
[16,     0] loss: 0.005
[16,   100] loss: 0.498
[16,   200] loss: 0.496
[16,   300] loss: 0.500
[16,   400] loss: 0.496
[16,   500] loss: 0.509
[16,   600] loss: 0.496
[16,   700] loss: 0.497
[16,   800] loss: 0.500
[17,     0] loss: 0.005
[17,   100] loss: 0.505
[17,   200] loss: 0.494
[17,   300] loss: 0.499
[17,   400] loss: 0.511
[17,   500] loss: 0.508
[17,   600] loss: 0.502
[17,   700] loss: 0.506
[17,   800] loss: 0.497
[18,     0] loss: 0.005
[18,   100] loss: 0.491
[18,   200] loss: 0.498
[18,   300] loss: 0.500
[18,   400] loss: 0.504
[18,   500] loss: 0.510
[18,   600] loss: 0.498
[18,   700] loss: 0.504
[18,   800] loss: 0.503
[19,     0] loss: 0.005
[19,   100] loss: 0.499
[19,   200] loss: 0.500
[19,   300] loss: 0.500
[19,   400] loss: 0.503
[19,   500] loss: 0.501
[19,   600] loss: 0.502
[19,   700] loss: 0.502
[19,   800] loss: 0.499
[20,     0] loss: 0.005
[20,   100] loss: 0.498
[20,   200] loss: 0.496
[20,   300] loss: 0.506
[20,   400] loss: 0.506
[20,   500] loss: 0.496
[20,   600] loss: 0.505
[20,   700] loss: 0.507
[20,   800] loss: 0.497
[21,     0] loss: 0.005
[21,   100] loss: 0.502
[21,   200] loss: 0.502
[21,   300] loss: 0.503
[21,   400] loss: 0.502
[21,   500] loss: 0.500
[21,   600] loss: 0.509
[21,   700] loss: 0.504
[21,   800] loss: 0.496
[22,     0] loss: 0.004
[22,   100] loss: 0.502
[22,   200] loss: 0.503
[22,   300] loss: 0.505
[22,   400] loss: 0.506
[22,   500] loss: 0.503
[22,   600] loss: 0.506
[22,   700] loss: 0.508
[22,   800] loss: 0.502
[23,     0] loss: 0.005
[23,   100] loss: 0.508
[23,   200] loss: 0.509
[23,   300] loss: 0.504
[23,   400] loss: 0.498
[23,   500] loss: 0.501
[23,   600] loss: 0.505
[23,   700] loss: 0.497
[23,   800] loss: 0.503
[24,     0] loss: 0.005
[24,   100] loss: 0.499
[24,   200] loss: 0.494
[24,   300] loss: 0.495
[24,   400] loss: 0.495
[24,   500] loss: 0.497
[24,   600] loss: 0.507
[24,   700] loss: 0.499
[24,   800] loss: 0.495
[25,     0] loss: 0.005
[25,   100] loss: 0.499
[25,   200] loss: 0.503
[25,   300] loss: 0.497
[25,   400] loss: 0.502
[25,   500] loss: 0.502
[25,   600] loss: 0.506
[25,   700] loss: 0.499
[25,   800] loss: 0.504
[26,     0] loss: 0.005
[26,   100] loss: 0.498
[26,   200] loss: 0.498
[26,   300] loss: 0.498
[26,   400] loss: 0.503
[26,   500] loss: 0.509
[26,   600] loss: 0.503
[26,   700] loss: 0.502
[26,   800] loss: 0.510
[27,     0] loss: 0.005
[27,   100] loss: 0.502
[27,   200] loss: 0.502
[27,   300] loss: 0.510
[27,   400] loss: 0.499
[27,   500] loss: 0.500
[27,   600] loss: 0.501
[27,   700] loss: 0.497
[27,   800] loss: 0.504
[28,     0] loss: 0.006
[28,   100] loss: 0.503
[28,   200] loss: 0.495
[28,   300] loss: 0.509
[28,   400] loss: 0.505
[28,   500] loss: 0.502
[28,   600] loss: 0.499
[28,   700] loss: 0.497
[28,   800] loss: 0.501
[29,     0] loss: 0.005
[29,   100] loss: 0.501
[29,   200] loss: 0.498
[29,   300] loss: 0.498
[29,   400] loss: 0.503
[29,   500] loss: 0.498
[29,   600] loss: 0.505
[29,   700] loss: 0.504
[29,   800] loss: 0.498
[30,     0] loss: 0.006
[30,   100] loss: 0.509
[30,   200] loss: 0.500
[30,   300] loss: 0.495
[30,   400] loss: 0.502
[30,   500] loss: 0.504
[30,   600] loss: 0.503
[30,   700] loss: 0.494
[30,   800] loss: 0.499
[31,     0] loss: 0.005
[31,   100] loss: 0.493
[31,   200] loss: 0.507
[31,   300] loss: 0.504
[31,   400] loss: 0.497
[31,   500] loss: 0.494
[31,   600] loss: 0.493
[31,   700] loss: 0.504
[31,   800] loss: 0.503
[32,     0] loss: 0.005
[32,   100] loss: 0.493
[32,   200] loss: 0.499
[32,   300] loss: 0.503
[32,   400] loss: 0.499
[32,   500] loss: 0.504
[32,   600] loss: 0.506
[32,   700] loss: 0.492
[32,   800] loss: 0.512
[33,     0] loss: 0.005
[33,   100] loss: 0.502
[33,   200] loss: 0.494
[33,   300] loss: 0.502
[33,   400] loss: 0.500
[33,   500] loss: 0.498
[33,   600] loss: 0.493
[33,   700] loss: 0.500
[33,   800] loss: 0.498
[34,     0] loss: 0.006
[34,   100] loss: 0.490
[34,   200] loss: 0.494
[34,   300] loss: 0.504
[34,   400] loss: 0.499
[34,   500] loss: 0.501
[34,   600] loss: 0.499
[34,   700] loss: 0.501
[34,   800] loss: 0.502
[35,     0] loss: 0.005
[35,   100] loss: 0.502
[35,   200] loss: 0.504
[35,   300] loss: 0.501
[35,   400] loss: 0.503
[35,   500] loss: 0.506
[35,   600] loss: 0.506
[35,   700] loss: 0.500
[35,   800] loss: 0.514
[36,     0] loss: 0.005
[36,   100] loss: 0.499
[36,   200] loss: 0.505
[36,   300] loss: 0.498
[36,   400] loss: 0.497
[36,   500] loss: 0.501
[36,   600] loss: 0.500
[36,   700] loss: 0.500
[36,   800] loss: 0.508
[37,     0] loss: 0.005
[37,   100] loss: 0.504
[37,   200] loss: 0.494
[37,   300] loss: 0.502
[37,   400] loss: 0.501
[37,   500] loss: 0.502
[37,   600] loss: 0.493
[37,   700] loss: 0.500
[37,   800] loss: 0.496
[38,     0] loss: 0.005
[38,   100] loss: 0.503
[38,   200] loss: 0.507
[38,   300] loss: 0.505
[38,   400] loss: 0.505
[38,   500] loss: 0.507
[38,   600] loss: 0.501
[38,   700] loss: 0.505
[38,   800] loss: 0.502
[39,     0] loss: 0.004
[39,   100] loss: 0.497
[39,   200] loss: 0.498
[39,   300] loss: 0.507
[39,   400] loss: 0.503
[39,   500] loss: 0.503
[39,   600] loss: 0.501
[39,   700] loss: 0.496
[39,   800] loss: 0.497
[40,     0] loss: 0.005
[40,   100] loss: 0.502
[40,   200] loss: 0.501
[40,   300] loss: 0.502
[40,   400] loss: 0.501
[40,   500] loss: 0.506
[40,   600] loss: 0.494
[40,   700] loss: 0.499
[40,   800] loss: 0.503
[41,     0] loss: 0.005
[41,   100] loss: 0.499
[41,   200] loss: 0.505
[41,   300] loss: 0.506
[41,   400] loss: 0.500
[41,   500] loss: 0.504
[41,   600] loss: 0.508
[41,   700] loss: 0.502
[41,   800] loss: 0.501
[42,     0] loss: 0.006
[42,   100] loss: 0.509
[42,   200] loss: 0.508
[42,   300] loss: 0.507
[42,   400] loss: 0.505
[42,   500] loss: 0.501
[42,   600] loss: 0.504
[42,   700] loss: 0.502
[42,   800] loss: 0.509
[43,     0] loss: 0.005
[43,   100] loss: 0.508
[43,   200] loss: 0.498
[43,   300] loss: 0.497
[43,   400] loss: 0.499
[43,   500] loss: 0.504
[43,   600] loss: 0.496
[43,   700] loss: 0.503
[43,   800] loss: 0.502
[44,     0] loss: 0.004
[44,   100] loss: 0.500
[44,   200] loss: 0.490
[44,   300] loss: 0.504
[44,   400] loss: 0.504
[44,   500] loss: 0.503
[44,   600] loss: 0.505
[44,   700] loss: 0.514
[44,   800] loss: 0.501
[45,     0] loss: 0.005
[45,   100] loss: 0.497
[45,   200] loss: 0.511
[45,   300] loss: 0.501
[45,   400] loss: 0.503
[45,   500] loss: 0.510
[45,   600] loss: 0.503
[45,   700] loss: 0.502
[45,   800] loss: 0.496
[46,     0] loss: 0.005
[46,   100] loss: 0.502
[46,   200] loss: 0.504
[46,   300] loss: 0.502
[46,   400] loss: 0.511
[46,   500] loss: 0.513
[46,   600] loss: 0.506
[46,   700] loss: 0.507
[46,   800] loss: 0.501
[47,     0] loss: 0.005
[47,   100] loss: 0.504
[47,   200] loss: 0.516
[47,   300] loss: 0.508
[47,   400] loss: 0.503
[47,   500] loss: 0.500
[47,   600] loss: 0.509
[47,   700] loss: 0.507
[47,   800] loss: 0.504
[48,     0] loss: 0.006
[48,   100] loss: 0.507
[48,   200] loss: 0.511
[48,   300] loss: 0.517
[48,   400] loss: 0.494
[48,   500] loss: 0.510
[48,   600] loss: 0.506
[48,   700] loss: 0.503
[48,   800] loss: 0.505
[49,     0] loss: 0.005
[49,   100] loss: 0.507
[49,   200] loss: 0.500
[49,   300] loss: 0.505
[49,   400] loss: 0.501
[49,   500] loss: 0.504
[49,   600] loss: 0.510
[49,   700] loss: 0.513
[49,   800] loss: 0.506
[50,     0] loss: 0.005
[50,   100] loss: 0.502
[50,   200] loss: 0.501
[50,   300] loss: 0.511
[50,   400] loss: 0.508
[50,   500] loss: 0.506
[50,   600] loss: 0.514
[50,   700] loss: 0.504
[50,   800] loss: 0.501
[51,     0] loss: 0.006
[51,   100] loss: 0.508
[51,   200] loss: 0.509
[51,   300] loss: 0.501
[51,   400] loss: 0.513
[51,   500] loss: 0.496
[51,   600] loss: 0.509
[51,   700] loss: 0.510
[51,   800] loss: 0.500
[52,     0] loss: 0.006
[52,   100] loss: 0.504
[52,   200] loss: 0.510
[52,   300] loss: 0.509
[52,   400] loss: 0.511
[52,   500] loss: 0.513
[52,   600] loss: 0.505
[52,   700] loss: 0.508
[52,   800] loss: 0.509
[53,     0] loss: 0.005
[53,   100] loss: 0.505
[53,   200] loss: 0.506
[53,   300] loss: 0.513
[53,   400] loss: 0.501
[53,   500] loss: 0.508
[53,   600] loss: 0.509
[53,   700] loss: 0.502
[53,   800] loss: 0.506
[54,     0] loss: 0.005
[54,   100] loss: 0.508
[54,   200] loss: 0.505
[54,   300] loss: 0.508
[54,   400] loss: 0.509
[54,   500] loss: 0.506
[54,   600] loss: 0.508
[54,   700] loss: 0.503
[54,   800] loss: 0.517
[55,     0] loss: 0.005
[55,   100] loss: 0.502
[55,   200] loss: 0.506
[55,   300] loss: 0.515
[55,   400] loss: 0.511
[55,   500] loss: 0.505
[55,   600] loss: 0.511
[55,   700] loss: 0.511
[55,   800] loss: 0.509
[56,     0] loss: 0.004
[56,   100] loss: 0.500
[56,   200] loss: 0.511
[56,   300] loss: 0.503
[56,   400] loss: 0.503
[56,   500] loss: 0.512
[56,   600] loss: 0.510
[56,   700] loss: 0.507
[56,   800] loss: 0.508
[57,     0] loss: 0.004
[57,   100] loss: 0.511
[57,   200] loss: 0.503
[57,   300] loss: 0.507
[57,   400] loss: 0.504
[57,   500] loss: 0.504
[57,   600] loss: 0.510
[57,   700] loss: 0.505
[57,   800] loss: 0.510
[58,     0] loss: 0.005
[58,   100] loss: 0.518
[58,   200] loss: 0.507
[58,   300] loss: 0.505
[58,   400] loss: 0.506
[58,   500] loss: 0.508
[58,   600] loss: 0.508
[58,   700] loss: 0.510
[58,   800] loss: 0.519
[59,     0] loss: 0.005
[59,   100] loss: 0.506
[59,   200] loss: 0.503
[59,   300] loss: 0.504
[59,   400] loss: 0.513
[59,   500] loss: 0.509
[59,   600] loss: 0.510
[59,   700] loss: 0.508
[59,   800] loss: 0.512
[60,     0] loss: 0.005
[60,   100] loss: 0.514
[60,   200] loss: 0.508
[60,   300] loss: 0.502
[60,   400] loss: 0.512
[60,   500] loss: 0.505
[60,   600] loss: 0.514
[60,   700] loss: 0.505
[60,   800] loss: 0.504
[61,     0] loss: 0.005
[61,   100] loss: 0.511
[61,   200] loss: 0.505
[61,   300] loss: 0.500
[61,   400] loss: 0.515
[61,   500] loss: 0.511
[61,   600] loss: 0.506
[61,   700] loss: 0.502
[61,   800] loss: 0.505
[62,     0] loss: 0.005
[62,   100] loss: 0.509
[62,   200] loss: 0.506
[62,   300] loss: 0.505
[62,   400] loss: 0.510
[62,   500] loss: 0.508
[62,   600] loss: 0.510
[62,   700] loss: 0.510
[62,   800] loss: 0.511
[63,     0] loss: 0.006
[63,   100] loss: 0.513
[63,   200] loss: 0.503
[63,   300] loss: 0.504
[63,   400] loss: 0.505
[63,   500] loss: 0.517
[63,   600] loss: 0.509
[63,   700] loss: 0.508
[63,   800] loss: 0.511
[64,     0] loss: 0.004
[64,   100] loss: 0.504
[64,   200] loss: 0.509
[64,   300] loss: 0.498
[64,   400] loss: 0.512
[64,   500] loss: 0.513
[64,   600] loss: 0.509
[64,   700] loss: 0.512
[64,   800] loss: 0.508
[65,     0] loss: 0.005
[65,   100] loss: 0.507
[65,   200] loss: 0.502
[65,   300] loss: 0.509
[65,   400] loss: 0.507
[65,   500] loss: 0.506
[65,   600] loss: 0.502
[65,   700] loss: 0.510
[65,   800] loss: 0.505
[66,     0] loss: 0.006
[66,   100] loss: 0.509
[66,   200] loss: 0.501
[66,   300] loss: 0.512
[66,   400] loss: 0.506
[66,   500] loss: 0.510
[66,   600] loss: 0.501
[66,   700] loss: 0.511
[66,   800] loss: 0.512
[67,     0] loss: 0.006
[67,   100] loss: 0.513
[67,   200] loss: 0.505
[67,   300] loss: 0.511
[67,   400] loss: 0.510
[67,   500] loss: 0.503
[67,   600] loss: 0.508
[67,   700] loss: 0.505
[67,   800] loss: 0.505
[68,     0] loss: 0.005
[68,   100] loss: 0.512
[68,   200] loss: 0.503
[68,   300] loss: 0.506
[68,   400] loss: 0.510
[68,   500] loss: 0.511
[68,   600] loss: 0.514
[68,   700] loss: 0.506
[68,   800] loss: 0.498
[69,     0] loss: 0.005
[69,   100] loss: 0.510
[69,   200] loss: 0.511
[69,   300] loss: 0.508
[69,   400] loss: 0.509
[69,   500] loss: 0.510
[69,   600] loss: 0.507
[69,   700] loss: 0.509
[69,   800] loss: 0.509
[70,     0] loss: 0.005
[70,   100] loss: 0.503
[70,   200] loss: 0.510
[70,   300] loss: 0.514
[70,   400] loss: 0.516
[70,   500] loss: 0.505
[70,   600] loss: 0.503
[70,   700] loss: 0.508
[70,   800] loss: 0.500
[71,     0] loss: 0.006
[71,   100] loss: 0.501
[71,   200] loss: 0.515
[71,   300] loss: 0.514
[71,   400] loss: 0.504
[71,   500] loss: 0.505
[71,   600] loss: 0.507
[71,   700] loss: 0.502
[71,   800] loss: 0.509
[72,     0] loss: 0.006
[72,   100] loss: 0.505
[72,   200] loss: 0.506
[72,   300] loss: 0.502
[72,   400] loss: 0.511
[72,   500] loss: 0.502
[72,   600] loss: 0.520
[72,   700] loss: 0.508
[72,   800] loss: 0.507
[73,     0] loss: 0.005
[73,   100] loss: 0.517
[73,   200] loss: 0.497
[73,   300] loss: 0.506
[73,   400] loss: 0.512
[73,   500] loss: 0.517
[73,   600] loss: 0.506
[73,   700] loss: 0.510
[73,   800] loss: 0.512
[74,     0] loss: 0.005
[74,   100] loss: 0.503
[74,   200] loss: 0.513
[74,   300] loss: 0.507
[74,   400] loss: 0.510
[74,   500] loss: 0.507
[74,   600] loss: 0.507
[74,   700] loss: 0.517
[74,   800] loss: 0.506
[75,     0] loss: 0.005
[75,   100] loss: 0.506
[75,   200] loss: 0.503
[75,   300] loss: 0.512
[75,   400] loss: 0.505
[75,   500] loss: 0.503
[75,   600] loss: 0.506
[75,   700] loss: 0.511
[75,   800] loss: 0.505
[76,     0] loss: 0.006
[76,   100] loss: 0.514
[76,   200] loss: 0.510
[76,   300] loss: 0.504
[76,   400] loss: 0.507
[76,   500] loss: 0.507
[76,   600] loss: 0.508
[76,   700] loss: 0.507
[76,   800] loss: 0.506
[77,     0] loss: 0.004
[77,   100] loss: 0.512
[77,   200] loss: 0.513
[77,   300] loss: 0.506
[77,   400] loss: 0.509
[77,   500] loss: 0.499
[77,   600] loss: 0.505
[77,   700] loss: 0.508
[77,   800] loss: 0.501
[78,     0] loss: 0.006
[78,   100] loss: 0.495
[78,   200] loss: 0.512
[78,   300] loss: 0.509
[78,   400] loss: 0.505
[78,   500] loss: 0.505
[78,   600] loss: 0.514
[78,   700] loss: 0.510
[78,   800] loss: 0.504
[79,     0] loss: 0.005
[79,   100] loss: 0.507
[79,   200] loss: 0.514
[79,   300] loss: 0.505
[79,   400] loss: 0.513
[79,   500] loss: 0.501
[79,   600] loss: 0.504
[79,   700] loss: 0.507
[79,   800] loss: 0.514
[80,     0] loss: 0.005
[80,   100] loss: 0.515
[80,   200] loss: 0.503
[80,   300] loss: 0.504
[80,   400] loss: 0.507
[80,   500] loss: 0.507
[80,   600] loss: 0.504
[80,   700] loss: 0.512
[80,   800] loss: 0.506
[81,     0] loss: 0.005
[81,   100] loss: 0.512
[81,   200] loss: 0.508
[81,   300] loss: 0.501
[81,   400] loss: 0.501
[81,   500] loss: 0.508
[81,   600] loss: 0.504
[81,   700] loss: 0.516
[81,   800] loss: 0.517
[82,     0] loss: 0.005
[82,   100] loss: 0.506
[82,   200] loss: 0.502
[82,   300] loss: 0.507
[82,   400] loss: 0.521
[82,   500] loss: 0.503
[82,   600] loss: 0.505
[82,   700] loss: 0.516
[82,   800] loss: 0.515
[83,     0] loss: 0.005
[83,   100] loss: 0.505
[83,   200] loss: 0.506
[83,   300] loss: 0.505
[83,   400] loss: 0.517
[83,   500] loss: 0.512
[83,   600] loss: 0.504
[83,   700] loss: 0.507
[83,   800] loss: 0.501
[84,     0] loss: 0.005
[84,   100] loss: 0.501
[84,   200] loss: 0.507
[84,   300] loss: 0.512
[84,   400] loss: 0.510
[84,   500] loss: 0.507
[84,   600] loss: 0.511
[84,   700] loss: 0.511
[84,   800] loss: 0.514
[85,     0] loss: 0.005
[85,   100] loss: 0.506
[85,   200] loss: 0.508
[85,   300] loss: 0.515
[85,   400] loss: 0.511
[85,   500] loss: 0.509
[85,   600] loss: 0.512
[85,   700] loss: 0.509
[85,   800] loss: 0.515
[86,     0] loss: 0.005
[86,   100] loss: 0.510
[86,   200] loss: 0.511
[86,   300] loss: 0.497
[86,   400] loss: 0.502
[86,   500] loss: 0.504
[86,   600] loss: 0.507
[86,   700] loss: 0.501
[86,   800] loss: 0.512
[87,     0] loss: 0.005
[87,   100] loss: 0.504
[87,   200] loss: 0.509
[87,   300] loss: 0.506
[87,   400] loss: 0.503
[87,   500] loss: 0.515
[87,   600] loss: 0.512
[87,   700] loss: 0.511
[87,   800] loss: 0.509
[88,     0] loss: 0.005
[88,   100] loss: 0.507
[88,   200] loss: 0.512
[88,   300] loss: 0.508
[88,   400] loss: 0.510
[88,   500] loss: 0.512
[88,   600] loss: 0.515
[88,   700] loss: 0.504
[88,   800] loss: 0.509
[89,     0] loss: 0.006
[89,   100] loss: 0.511
[89,   200] loss: 0.505
[89,   300] loss: 0.505
[89,   400] loss: 0.506
[89,   500] loss: 0.505
[89,   600] loss: 0.511
[89,   700] loss: 0.508
[89,   800] loss: 0.506
[90,     0] loss: 0.005
[90,   100] loss: 0.516
[90,   200] loss: 0.502
[90,   300] loss: 0.505
[90,   400] loss: 0.508
[90,   500] loss: 0.513
[90,   600] loss: 0.521
[90,   700] loss: 0.512
[90,   800] loss: 0.506
[91,     0] loss: 0.005
[91,   100] loss: 0.507
[91,   200] loss: 0.504
[91,   300] loss: 0.507
[91,   400] loss: 0.507
[91,   500] loss: 0.510
[91,   600] loss: 0.505
[91,   700] loss: 0.504
[91,   800] loss: 0.498
[92,     0] loss: 0.005
[92,   100] loss: 0.510
[92,   200] loss: 0.504
[92,   300] loss: 0.510
[92,   400] loss: 0.506
[92,   500] loss: 0.509
[92,   600] loss: 0.509
[92,   700] loss: 0.494
[92,   800] loss: 0.511
[93,     0] loss: 0.006
[93,   100] loss: 0.504
[93,   200] loss: 0.510
[93,   300] loss: 0.509
[93,   400] loss: 0.509
[93,   500] loss: 0.501
[93,   600] loss: 0.515
[93,   700] loss: 0.508

In [68]:
file_path = f'{PROCESSED_FILE_DIR}/FH_item_update.pickle'

with open(file_path, 'rb') as file:
    loaded_dictionary = pickle.load(file)

In [69]:
def get_key_by_value(dictionary, value):
    for key, val in dictionary.items():
        if val == value:
            return key
    return None

In [70]:
rows = []
for user, rankings in recommendation_list.items():
    for rank, item in rankings:
        rows.append({"user": user, "rank": rank, "item_update": item, "item": get_key_by_value(loaded_dictionary, item)})

all_recs = pd.DataFrame(rows)

In [71]:
cold_start_item=[2,571]

In [72]:
filtered_recs = all_recs[~all_recs['item'].isin(cold_start_item)]
filtered_recs

        user  rank  item_update  item
0       3411     1          318   324
1       3411     2          256   262
2       3411     3          923   931
3       3411     4         1179  1188
4       3411     5         1308  1319
...      ...   ...          ...   ...
540695  3605    96          339   345
540696  3605    97          141   142
540697  3605    98          641   649
540698  3605    99          249   255
540699  3605   100          113   114

[539700 rows x 4 columns]

In [73]:
filtered_recs['rank'] = filtered_recs['rank'].astype(int)

/tmp/ipykernel_1399667/435666994.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_recs['rank'] = filtered_recs['rank'].astype(int)

In [74]:
filtered_recs['re-rank'] = filtered_recs.groupby('user')['rank'].rank(method='first')
filtered_recs['rank'] = filtered_recs['re-rank'].astype(int)
filtered_recs=filtered_recs.iloc[:,[0,1,2,3]]

/tmp/ipykernel_1399667/347894999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_recs['re-rank'] = filtered_recs.groupby('user')['rank'].rank(method='first')
/tmp/ipykernel_1399667/347894999.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_recs['rank'] = filtered_recs['re-rank'].astype(int)

In [75]:
# Save filtered_recs to pickle
filtered_recs.to_pickle(f'{PROCESSED_FILE_DIR}/FH_filtered_recs_neighbour_0.6_threshold.pickle')

In [76]:
filtered_recs

        user  rank  item_update  item
0       3411     1          318   324
1       3411     2          256   262
2       3411     3          923   931
3       3411     4         1179  1188
4       3411     5         1308  1319
...      ...   ...          ...   ...
540695  3605    96          339   345
540696  3605    97          141   142
540697  3605    98          641   649
540698  3605    99          249   255
540699  3605   100          113   114

[539700 rows x 4 columns]

In [77]:
# Define the different top-k values you want to generate
top_k_values = [5, 10, 15, 20]

# Loop through each k value
for k in top_k_values:
    # Filter for top-k recommendations (excluding user 0)
    MA_gnn_all_recs_top_k = filtered_recs[(filtered_recs['rank'] <= k) & (filtered_recs['user']!=5406)]
    
    # Select only the required columns: user, rank, item
    final_all_recs = MA_gnn_all_recs_top_k.iloc[:, [0, 1, 3]]
    
    # Display the final DataFrame (with only 3 columns)
    print(f"\n{'='*60}")
    print(f"TOP-{k} RECOMMENDATIONS (user, rank, item)")
    print(f"{'='*60}")
    display(final_all_recs)
    
    # Save to CSV with k in the filename
    filename = f'{DATA_FILE_DIR}/FH_Trustworthy_Neighbor_Space_0.6_threshold_top_{k}.csv'
    final_all_recs.to_csv(filename, index=False)
    
    print(f"\n✓ Saved {len(final_all_recs)} recommendations to {filename}")
    print(f"  - Number of users: {final_all_recs['user'].nunique()}")

============================================================
TOP-5 RECOMMENDATIONS (user, rank, item)
============================================================

        user  rank  item
0       3411     1   324
1       3411     2   262
2       3411     3   931
3       3411     4  1188
4       3411     5  1319
...      ...   ...   ...
540600  3605     1   290
540601  3605     2   762
540602  3605     3  1022
540603  3605     4  1076
540604  3605     5   341

[27030 rows x 3 columns]

✓ Saved 27030 recommendations to /home/shoaib/recommender-system/royal/journal-revision/New/FH/data/FH_Trustworthy_Neighbor_Space_0.6_threshold_top_5.csv
  - Number of users: 5406

============================================================
TOP-10 RECOMMENDATIONS (user, rank, item)
============================================================

        user  rank  item
0       3411     1   324
1       3411     2   262
2       3411     3   931
3       3411     4  1188
4       3411     5  1319
...      ...   ...   ...
540605  3605     6   733
540606  3605     7     1
540607  3605     8     8
540608  3605     9   293
540609  3605    10  1486

[54060 rows x 3 columns]

✓ Saved 54060 recommendations to /home/shoaib/recommender-system/royal/journal-revision/New/FH/data/FH_Trustworthy_Neighbor_Space_0.6_threshold_top_10.csv
  - Number of users: 5406

============================================================
TOP-15 RECOMMENDATIONS (user, rank, item)
============================================================

        user  rank  item
0       3411     1   324
1       3411     2   262
2       3411     3   931
3       3411     4  1188
4       3411     5  1319
...      ...   ...   ...
540610  3605    11   840
540611  3605    12  1178
540612  3605    13  1206
540613  3605    14   339
540614  3605    15   126

[81090 rows x 3 columns]

✓ Saved 81090 recommendations to /home/shoaib/recommender-system/royal/journal-revision/New/FH/data/FH_Trustworthy_Neighbor_Space_0.6_threshold_top_15.csv
  - Number of users: 5406

============================================================
TOP-20 RECOMMENDATIONS (user, rank, item)
============================================================

        user  rank  item
0       3411     1   324
1       3411     2   262
2       3411     3   931
3       3411     4  1188
4       3411     5  1319
...      ...   ...   ...
540615  3605    16   908
540616  3605    17   193
540617  3605    18   140
540618  3605    19   328
540619  3605    20   728

[108120 rows x 3 columns]

✓ Saved 108120 recommendations to /home/shoaib/recommender-system/royal/journal-revision/New/FH/data/FH_Trustworthy_Neighbor_Space_0.6_threshold_top_20.csv
  - Number of users: 5406

## Evaluation

In [78]:
test=pd.read_csv(f"{DATA_FILE_DIR}/test_ratings_final_before_train.csv")
test=test.iloc[:,[1,2,3]]
test.drop(index=5406,inplace=True)
test

      user  item  ratings
0        0   332      1.0
1        1    66      1.0
2        2   785      1.5
3        3    85      1.5
4        4   120      1.5
...    ...   ...      ...
5401  5401     1      0.5
5402  5402     5      2.0
5403  5403     1      1.0
5404  5404     1      1.5
5405  5405   914      1.5

[5406 rows x 3 columns]

In [79]:
top_k_values = [5, 10, 15, 20]

# Initialize RecListAnalysis
rla = topn.RecListAnalysis()
rla.add_metric(topn.recip_rank)

# Store results
mrr_results = {}

for k in top_k_values:
    # Load the corresponding CSV
    final_all_recs = pd.read_csv(f"{DATA_FILE_DIR}/FH_Trustworthy_Neighbor_Space_0.6_threshold_top_{k}.csv")
    
    # Compute MRR
    results = rla.compute(final_all_recs, test)
    mean_results = results.mean()
    
    # Check what's in the results
    print(f"\nTop-{k} Results:")
    print(mean_results)
    
    mrr_results[k] = mean_results['recip_rank']

# Create summary DataFrame
mrr_summary = pd.DataFrame(list(mrr_results.items()), columns=['Top-K', 'MRR'])
display(mrr_summary)

Top-5 Results:
nrecs         5.00000
recip_rank    0.00792
dtype: float64

Top-10 Results:
nrecs         10.000000
recip_rank     0.010056
dtype: float64

Top-15 Results:
nrecs         15.000000
recip_rank     0.011126
dtype: float64

Top-20 Results:
nrecs         20.000000
recip_rank     0.012528
dtype: float64

   Top-K       MRR
0      5  0.007920
1     10  0.010056
2     15  0.011126
3     20  0.012528

In [80]:
# Load the key (only once)
key = pd.read_csv(f"{DATA_FILE_DIR}/key_healthstory.csv")
key_news_id = key[["item","label"]].drop_duplicates(subset=["item"], keep="last").reset_index(drop=True)
key_news_id["fake_real_labels"] = key_news_id["label"].apply(lambda x: 0 if x == "fake" else 1)

# Define the MMC function
def mmc(dataframe, top_n):
    """
    Calculates the Misinformation Count (MC) divided by the top-N recommendations for each user.

    Parameters:
    dataframe (DataFrame): DataFrame with columns 'user_id', 'item_id', 'rank', 'news_label'.
    top_n (int): Number of top recommendations to consider.

    Returns:
    float: Mean MC across all users.
    """
    dataframe = dataframe[dataframe['rank'] <= top_n]
    sorted_df = dataframe.sort_values(by=['user', 'rank'])
    misinformation_df = sorted_df[sorted_df['label'] == 'fake']
    user_mc = misinformation_df.groupby('user').size().reset_index(name='M_item')
    user_mc['MC'] = user_mc['M_item'] / top_n
    return user_mc['MC'].mean()

# Compute MC for all top-k values
top_k_values = [5, 10, 15, 20]
mc_results = {}

for k in top_k_values:
    # Load the corresponding CSV
    final_all_recs = pd.read_csv(f"{DATA_FILE_DIR}/FH_Trustworthy_Neighbor_Space_0.6_threshold_top_{k}.csv")
    
    # Merge with news labels
    final_recs_mc = pd.merge(final_all_recs, key_news_id, left_on="item", right_on="item", how='inner')
    
    # Compute MC for this top-k
    mc_score = mmc(final_recs_mc, k)
    mc_results[k] = mc_score
    
    print(f"Top-{k} MC: {mc_score:.4f}")

# Create summary DataFrame
mc_summary = pd.DataFrame(list(mc_results.items()), columns=['Top-K', 'MC'])
display(mc_summary)

Top-5 MC: 0.4400
Top-10 MC: 0.3664
Top-15 MC: 0.3429
Top-20 MC: 0.3312

   Top-K        MC
0      5  0.439968
1     10  0.366445
2     15  0.342940
3     20  0.331188