In [ ]:
import numpy as np
import pandas as pd
from lenskit import batch, topn, util
import os

In [ ]:
PROCESSED_FILE_DIR = "/home/shoaib/recommender-system/royal/journal-revision/New/Politifact/processed-files"
DATA_FILE_DIR = "/home/shoaib/recommender-system/royal/journal-revision/New/Politifact/data-files"
RESULTS_DIR = "/home/shoaib/recommender-system/royal/journal-revision/New/Politifact/results"

In [ ]:
train=pd.read_csv(f"{DATA_FILE_DIR}/train_ratings.csv").iloc[:,[1,2,3]]

In [3]:
train.drop_duplicates(subset=['user', 'item'], inplace=True)

In [4]:
train

       user  item  ratings
0         1   288      1.0
1         1   353      2.0
2         1   435      1.5
3         1   184      1.5
4         1   416      1.5
...     ...   ...      ...
19236  1028   242      0.5
19237     0    47      1.5
19238     0    51      1.5
19239     0   231      1.5
19240     0   484      1.5

[13359 rows x 3 columns]

In [5]:
user_item_sets = train.groupby('user')['item'].apply(set).to_dict()

In [6]:
user_item_sets

{0: {47, 51, 231, 484},
 1: {3, 135, 184, 275, 288, 353, 395, 416, 435, 439, 458},
 2: {25, 26, 251, 319, 347, 352, 440, 456, 519, 522},
 3: {25,
  29,
  32,
  124,
  139,
  189,
  263,
  274,
  348,
  352,
  380,
  410,
  434,
  440,
  456,
  489,
  500,
  505},
 4: {9,
  25,
  29,
  67,
  127,
  130,
  187,
  189,
  190,
  227,
  355,
  359,
  389,
  434,
  511,
  531},
 5: {25,
  31,
  71,
  135,
  171,
  213,
  221,
  240,
  275,
  324,
  334,
  345,
  359,
  387,
  395,
  476},
 6: {25, 92, 224, 259, 260, 261, 324, 387, 394, 421, 456},
 7: {9, 25, 92, 223, 224, 288, 359, 394},
 8: {25, 31, 304, 356, 360, 387, 476, 524, 530},
 9: {21, 81, 148, 195, 250, 308, 346, 408},
 10: {20,
  22,
  86,
  106,
  109,
  113,
  127,
  171,
  173,
  175,
  187,
  204,
  206,
  223,
  269,
  282,
  300,
  323,
  334,
  360,
  382,
  412,
  432,
  450},
 11: {31, 53, 148, 195, 205, 221, 250, 263, 275, 395, 530},
 12: {21, 95, 173, 242, 269, 321, 376, 476},
 13: {44, 84, 111, 158, 221, 230, 239, 293, 301, 304, 310, 404, 478, 512},
 14: {23,
  44,
  77,
  91,
  92,
  111,
  113,
  173,
  174,
  237,
  257,
  293,
  303,
  310,
  340,
  362,
  366,
  426,
  450,
  467,
  496,
  534},
 15: {23,
  41,
  44,
  77,
  79,
  91,
  92,
  111,
  113,
  159,
  173,
  174,
  223,
  227,
  233,
  237,
  257,
  293,
  303,
  310,
  311,
  340,
  362,
  366,
  426,
  450,
  467,
  496,
  508,
  529,
  534},
 16: {21,
  39,
  44,
  45,
  58,
  98,
  106,
  108,
  110,
  111,
  206,
  219,
  222,
  232,
  250,
  278,
  294,
  308,
  309,
  314,
  333,
  334,
  346,
  356,
  374,
  387,
  389,
  409,
  466,
  472,
  524,
  537},
 17: {124, 141, 184, 247, 274, 341, 410, 427},
 18: {11, 31, 135, 195, 285, 288, 456, 468, 489},
 19: {274, 347, 348, 483, 489, 519, 522},
 20: {1,
  8,
  34,
  45,
  49,
  69,
  87,
  124,
  191,
  198,
  199,
  229,
  262,
  272,
  288,
  319,
  339,
  352,
  385,
  410,
  421,
  425,
  429,
  434,
  435,
  440,
  443,
  456,
  477,
  480,
  489,
  500,
  505,
  522,
  532,
  540},
 21: {13, 199, 247, 336, 427, 447, 456, 500, 522, 532},
 22: {104, 173, 221, 261, 271, 294, 334, 366, 376},
 23: {25, 45, 54, 120, 162, 189, 233, 240, 319, 345, 395, 435, 489, 511},
 24: {1,
  13,
  18,
  26,
  32,
  45,
  102,
  120,
  124,
  126,
  127,
  153,
  156,
  181,
  256,
  283,
  298,
  307,
  339,
  348,
  429,
  443,
  445,
  447,
  451,
  480},
 25: {113, 173, 236, 239, 301, 402, 512, 518, 537},
 26: {26,
  29,
  40,
  45,
  49,
  124,
  147,
  153,
  189,
  198,
  199,
  272,
  274,
  281,
  285,
  288,
  319,
  332,
  348,
  394,
  410,
  411,
  421,
  425,
  434,
  440,
  456,
  489,
  505,
  532},
 27: {9,
  44,
  61,
  95,
  112,
  113,
  129,
  152,
  159,
  171,
  221,
  236,
  238,
  239,
  242,
  243,
  247,
  250,
  261,
  278,
  293,
  341,
  346,
  359,
  360,
  384,
  400,
  402,
  424,
  512},
 28: {72, 88, 135, 278, 351, 437, 459, 466},
 29: {29, 42, 95, 235, 239, 361, 402, 454},
 30: {18,
  34,
  124,
  126,
  147,
  184,
  199,
  275,
  299,
  307,
  319,
  395,
  456,
  489,
  505,
  522,
  532},
 31: {9,
  53,
  55,
  65,
  81,
  95,
  106,
  113,
  131,
  132,
  190,
  224,
  239,
  278,
  286,
  292,
  293,
  294,
  304,
  317,
  334,
  345,
  351,
  360,
  361,
  364,
  366,
  375,
  382,
  401,
  409,
  416,
  435,
  450,
  454,
  501,
  512,
  513,
  526,
  531,
  534},
 32: {175, 242, 286, 345, 348, 440, 454},
 33: {8, 40, 124, 189, 229, 254, 352, 368, 397, 410, 421, 440, 451, 505, 518},
 34: {1, 87, 127, 184, 316, 405, 416, 437, 444, 445, 447, 480, 506},
 35: {9, 43, 53, 112, 154, 196, 200, 221, 237, 278, 360, 376, 391},
 36: {68, 190, 280, 308, 356, 359, 476, 487},
 37: {44, 113, 208, 294, 300, 308, 334, 422, 493, 534},
 38: {9, 91, 106, 278, 345, 360, 408, 475, 478},
 39: {1, 102, 156, 283, 298, 326, 349, 443, 480},
 40: {67,
  91,
  106,
  112,
  148,
  157,
  173,
  221,
  239,
  250,
  261,
  278,
  293,
  308,
  312,
  324,
  345,
  360,
  361,
  366,
  402,
  493,
  512},
 41: {8, 124, 247, 410, 425, 427, 504},
 42: {239, 278, 345, 359, 360, 366, 489},
 43: {184, 195, 317, 346, 351, 408, 426, 429, 435, 456, 493, 539},
 44: {8, 304, 347, 383, 401, 425, 519},
 45: {25, 28, 162, 194, 319, 348, 521, 532},
 46: {17, 81, 135, 275, 351, 359, 395, 454, 459},
 47: {72,
  91,
  95,
  106,
  148,
  175,
  223,
  239,
  240,
  242,
  259,
  286,
  304,
  318,
  329,
  345,
  361,
  380,
  384,
  408},
 48: {1, 15, 28, 114, 126, 156, 298, 339, 349, 396, 437, 471, 525},
 49: {3, 85, 101, 191, 288, 316, 348, 456},
 50: {56, 68, 91, 199, 250, 310, 361},
 51: {9, 187, 221, 222, 224, 259, 286, 314, 355, 389, 524},
 52: {94, 198, 416, 425, 500, 522, 525},
 53: {88, 210, 242, 259, 283, 314, 356, 359, 360, 389, 438, 440, 443, 530},
 54: {55,
  67,
  81,
  92,
  109,
  171,
  175,
  200,
  204,
  224,
  294,
  300,
  310,
  360,
  366,
  402,
  512},
 55: {21, 129, 175, 237, 278, 294, 327, 366, 376, 384, 426, 493},
 56: {9,
  21,
  29,
  69,
  75,
  106,
  113,
  173,
  204,
  206,
  303,
  304,
  335,
  364,
  382,
  387,
  408,
  493},
 57: {23,
  41,
  85,
  92,
  95,
  105,
  111,
  144,
  157,
  159,
  174,
  208,
  237,
  269,
  293,
  294,
  307,
  340,
  344,
  362,
  401,
  420,
  426,
  450,
  467,
  485,
  487,
  492,
  496,
  508,
  534},
 58: {67,
  127,
  173,
  189,
  195,
  216,
  278,
  312,
  318,
  346,
  351,
  408,
  412,
  415,
  437,
  508,
  537},
 59: {8, 94, 203, 243, 343, 356, 360, 371, 394, 402, 454, 514, 530},
 60: {29, 49, 137, 293, 299, 346, 394, 402, 440, 456, 489, 522, 532, 537},
 61: {8,
  18,
  120,
  156,
  247,
  278,
  285,
  307,
  341,
  348,
  352,
  365,
  421,
  425,
  427,
  440,
  445,
  456,
  489,
  500,
  505,
  513,
  532},
 62: {9, 64, 130, 208, 239, 240, 250, 345, 378, 450},
 63: {68,
  92,
  95,
  113,
  121,
  148,
  171,
  207,
  221,
  239,
  242,
  243,
  260,
  278,
  286,
  303,
  304,
  338,
  345,
  400,
  512,
  527},
 64: {39, 41, 92, 155, 200, 227, 237, 252, 450, 492, 531},
 65: {25, 46, 69, 81, 175, 206, 263, 351, 476},
 66: {44, 55, 88, 109, 173, 224, 375},
 67: {75, 121, 138, 196, 324, 356, 426},
 68: {11, 31, 94, 291, 448, 489, 514},
 69: {20,
  68,
  104,
  106,
  173,
  200,
  206,
  208,
  221,
  223,
  230,
  250,
  261,
  269,
  293,
  301,
  304,
  308,
  334,
  361,
  366,
  402,
  425,
  468,
  497},
 70: {44, 85, 95, 173, 245, 308, 450, 508},
 71: {110, 238, 263, 280, 345, 466, 497, 503},
 72: {8, 34, 124, 352, 394, 421, 540},
 73: {20,
  38,
  70,
  81,
  90,
  173,
  196,
  200,
  204,
  280,
  294,
  308,
  314,
  322,
  351,
  359,
  408,
  425,
  513},
 74: {13, 124, 156, 209, 255, 256, 285, 298, 328, 352, 430, 440, 518},
 75: {31, 54, 65, 195, 219, 233, 240, 351, 415, 416, 435, 454, 489},
 76: {45, 87, 124, 156, 348, 410, 421, 532},
 77: {8, 124, 156, 285, 319, 336, 348, 410, 437, 522},
 78: {11,
  75,
  162,
  252,
  256,
  270,
  311,
  326,
  347,
  363,
  401,
  447,
  462,
  479,
  506,
  519,
  534},
 79: {95, 171, 243, 261, 280, 286, 300, 426, 493},
 80: {9, 70, 173, 206, 351, 376, 408, 448, 454},
 81: {34,
  49,
  64,
  124,
  189,
  198,
  281,
  296,
  304,
  350,
  353,
  410,
  416,
  440,
  456,
  505,
  532},
 82: {92, 113, 173, 250, 293, 310, 318},
 83: {31, 46, 92, 272, 308, 334, 366, 537},
 84: {44, 113, 173, 257, 293, 303, 310, 366, 450},
 85: {21, 67, 171, 251, 280, 308, 402, 409, 468, 531},
 86: {206, 223, 224, 259, 260, 280, 300},
 87: {11, 31, 98, 121, 164, 188, 243, 359, 360, 466, 476},
 88: {81,
  95,
  106,
  173,
  175,
  190,
  203,
  224,
  228,
  239,
  276,
  278,
  286,
  294,
  308,
  318,
  324,
  351,
  361,
  416,
  426,
  476,
  497,
  509,
  526},
 89: {11, 25, 65, 89, 240, 360, 361, 437, 491},
 90: {21, 25, 45, 64, 195, 233, 304, 308, 345, 366, 521},
 91: {16,
  91,
  92,
  95,
  111,
  138,
  148,
  195,
  196,
  221,
  239,
  242,
  260,
  278,
  286,
  304,
  308,
  324,
  345,
  346,
  359,
  360,
  400,
  401,
  438,
  497,
  508,
  512,
  524,
  537},
 92: {23,
  41,
  44,
  92,
  111,
  157,
  174,
  237,
  293,
  310,
  311,
  340,
  362,
  420,
  426,
  450,
  467,
  496,
  534},
 93: {44, 95, 113, 145, 173, 257, 293, 303, 304, 310, 366, 450},
 94: {53, 104, 158, 237, 278, 293, 310, 376},
 95: {9,
  25,
  45,
  54,
  88,
  113,
  121,
  138,
  195,
  285,
  304,
  324,
  345,
  359,
  360,
  361,
  415,
  425,
  497},
 96: {48, 49, 130, 275, 288, 353, 405, 437, 440, 505},
 97: {94, 127, 147, 307, 339, 407, 421, 437, 445, 453, 477},
 98: {8,
  45,
  124,
  126,
  147,
  199,
  262,
  319,
  339,
  348,
  365,
  410,
  421,
  425,
  445,
  489,
  522,
  523,
  532},
 99: {9,
  21,
  44,
  56,
  68,
  84,
  86,
  88,
  91,
  92,
  95,
  138,
  150,
  242,
  286,
  303,
  318,
  345,
  356,
  387,
  426,
  472,
  482,
  493},
 100: {1, 94, 199, 361, 410, 454, 459, 480, 489, 514},
 101: {21, 68, 81, 230, 294, 304, 361, 501, 531},
 102: {113, 212, 239, 278, 314, 345, 360, 384, 400, 425, 512},
 103: {32, 40, 49, 147, 189, 256, 281, 288, 348, 425, 434, 445, 456},
 104: {21,
  25,
  44,
  45,
  70,
  92,
  120,
  121,
  173,
  187,
  189,
  200,
  206,
  221,
  222,
  223,
  224,
  259,
  275,
  278,
  307,
  309,
  314,
  334,
  348,
  355,
  356,
  359,
  380,
  381,
  389,
  402,
  416,
  425,
  445,
  468,
  489,
  505,
  513,
  532,
  541},
 105: {29, 85, 94, 434, 440, 444, 485, 514},
 106: {189, 251, 390, 395, 396, 415, 448, 489},
 107: {113, 235, 239, 242, 263, 360, 541},
 108: {41, 171, 221, 242, 270, 278, 360},
 109: {95, 99, 173, 257, 259, 280, 304, 476, 478},
 110: {39, 41, 92, 155, 200, 227, 237, 252, 397, 450, 492, 531},
 111: {119, 128, 334, 335, 340, 376, 387},
 112: {29, 69, 85, 153, 189, 229, 264, 274, 319, 434, 440, 441, 491, 500, 532},
 113: {11, 94, 147, 189, 195, 251, 288, 289, 319},
 114: {21, 68, 106, 318, 366, 400, 426, 493},
 115: {105, 119, 130, 163, 199, 276, 279, 337},
 116: {21,
  112,
  228,
  238,
  242,
  263,
  278,
  319,
  345,
  358,
  360,
  387,
  400,
  417,
  425,
  456,
  489},
 117: {45, 124, 184, 199, 281, 299, 348, 421, 456, 489, 500, 532},
 118: {95, 104, 126, 208, 221, 239, 278, 286, 360},
 119: {49, 64, 130, 252, 256, 265, 416, 447, 506, 513, 534},
 120: {94, 131, 239, 259, 346, 359, 387, 422, 467, 468, 514, 530, 532},
 121: {28, 105, 239, 242, 275, 309, 345, 351, 371, 476, 509, 512},
 122: {44,
  54,
  95,
  113,
  120,
  145,
  173,
  257,
  293,
  303,
  304,
  310,
  366,
  384,
  450,
  512},
 123: {29, 69, 247, 266, 274, 281, 341, 427, 434, 440, 516},
 124: {8, 192, 251, 255, 337, 347, 352, 383, 421, 451, 519},
 125: {102, 162, 178, 181, 283, 288, 298, 443, 480},
 126: {45, 49, 184, 251, 256, 341, 365, 396, 399, 429, 489},
 127: {113, 173, 226, 278, 317, 382, 384, 501, 526},
 128: {106, 111, 168, 228, 243, 294, 300, 345, 346, 356, 359, 400, 527},
 129: {61, 110, 117, 150, 343, 356, 360, 417, 493, 505, 524},
 130: {8,
  25,
  31,
  101,
  124,
  162,
  184,
  199,
  251,
  272,
  275,
  285,
  395,
  410,
  425,
  440,
  456,
  489,
  522,
  532},
 131: {49, 61, 95, 117, 120, 189, 278, 299, 345, 360, 384, 489, 527},
 132: {95, 113, 152, 204, 239, 261, 278, 304, 345, 400, 478, 527},
 133: {91,
  95,
  148,
  207,
  224,
  239,
  243,
  250,
  294,
  304,
  308,
  345,
  359,
  360,
  361,
  366,
  402,
  408,
  426,
  518,
  525},
 134: {25,
  31,
  37,
  53,
  58,
  68,
  81,
  95,
  106,
  108,
  111,
  112,
  171,
  173,
  175,
  208,
  236,
  285,
  293,
  300,
  305,
  308,
  317,
  345,
  346,
  359,
  366,
  376,
  384,
  400,
  409,
  422,
  511},
 135: {87,
  122,
  149,
  191,
  194,
  199,
  202,
  220,
  240,
  251,
  272,
  274,
  279,
  285,
  347,
  383,
  416,
  421,
  425,
  436,
  440,
  448,
  456,
  489,
  505,
  516,
  519,
  522,
  532},
 136: {53,
  95,
  109,
  111,
  157,
  171,
  196,
  250,
  278,
  300,
  304,
  382,
  384,
  401,
  402,
  478},
 137: {67, 91, 109, 188, 196, 200, 280, 294, 359, 390, 401},
 138: {92, 173, 204, 208, 280, 366, 384, 402},
 139: {56, 95, 224, 401, 408, 424, 501},
 140: {1,
  102,
  120,
  126,
  127,
  156,
  178,
  184,
  256,
  283,
  288,
  298,
  365,
  396,
  443,
  447,
  480},
 141: {17, 34, 120, 176, 190, 275, 285, 425, 445, 489},
 142: {113, 173, 206, 208, 269, 278, 286, 304, 317, 366, 382, 408, 493},
 143: {61,
  62,
  67,
  70,
  110,
  117,
  171,
  238,
  278,
  286,
  293,
  300,
  335,
  345,
  359,
  360,
  376,
  378,
  530},
 144: {1, 105, 113, 152, 205, 265, 294, 340, 360},
 145: {17, 68, 219, 243, 293, 294, 317, 422},
 146: {36, 89, 123, 157, 348, 352, 394, 397, 410},
 147: {124, 147, 199, 247, 319, 341, 348, 394, 410, 416, 421, 425, 427, 456},
 148: {53,
  68,
  95,
  113,
  173,
  175,
  196,
  206,
  208,
  221,
  236,
  239,
  261,
  280,
  308,
  323,
  329,
  351,
  361,
  400,
  402,
  493,
  501,
  527},
 149: {104,
  113,
  127,
  131,
  152,
  173,
  221,
  239,
  250,
  286,
  293,
  301,
  302,
  304,
  331,
  366,
  382,
  408,
  487,
  493,
  501},
 150: {92, 111, 174, 237, 293, 340, 362, 426, 450, 467},
 151: {21, 67, 187, 240, 346, 359, 387, 422, 476},
 152: {18,
  49,
  53,
  67,
  85,
  197,
  221,
  259,
  275,
  304,
  310,
  312,
  324,
  333,
  355,
  359,
  360},
 153: {21, 32, 45, 84, 105, 195, 206, 237, 409, 410, 459, 503, 512},
 154: {113, 148, 250, 280, 345, 360, 408, 512},
 155: {44,
  53,
  111,
  113,
  158,
  173,
  208,
  221,
  223,
  230,
  257,
  261,
  293,
  303,
  310,
  323,
  366,
  404,
  450,
  493},
 156: {21, 31, 38, 68, 109, 173, 204, 221, 240, 310, 317, 366},
 157: {52, 111, 117, 204, 224, 278, 314, 356, 476, 524},
 158: {44,
  53,
  75,
  111,
  113,
  158,
  173,
  208,
  221,
  230,
  257,
  261,
  286,
  293,
  310,
  323,
  404,
  450,
  493},
 159: {21, 54, 67, 88, 195, 351, 468},
 160: {49,
  89,
  139,
  156,
  229,
  288,
  304,
  347,
  348,
  416,
  426,
  428,
  435,
  440,
  447,
  519},
 161: {8,
  13,
  25,
  34,
  49,
  85,
  124,
  137,
  139,
  274,
  285,
  348,
  394,
  410,
  425,
  435,
  440,
  456,
  489,
  500,
  532},
 162: {17, 18, 69, 149, 214, 288, 434, 489},
 163: {91, 203, 207, 234, 238, 242, 304, 345, 371, 426},
 164: {272, 288, 347, 394, 429, 500, 519},
 165: {31, 162, 332, 489, 505, 513, 532},
 166: {1,
  8,
  28,
  141,
  153,
  199,
  251,
  265,
  272,
  283,
  319,
  332,
  365,
  383,
  416,
  443,
  480,
  516,
  518,
  525,
  532},
 167: {29, 69, 87, 189, 272, 319, 348, 489},
 168: {3,
  120,
  156,
  181,
  184,
  189,
  199,
  267,
  275,
  288,
  307,
  319,
  347,
  348,
  353,
  385,
  394,
  425,
  437,
  446,
  470,
  489,
  505,
  519},
 169: {46, 53, 81, 95, 106, 109, 113, 206, 239, 361, 387},
 170: {181, 184, 262, 275, 341, 351, 365, 429, 541},
 171: {56, 113, 152, 239, 376, 402, 478, 493},
 172: {8,
  29,
  49,
  124,
  189,
  198,
  240,
  256,
  274,
  275,
  284,
  319,
  415,
  434,
  454,
  477,
  489,
  505},
 173: {8, 13, 94, 127, 130, 184, 275, 290, 394, 410, 431, 437, 489},
 174: {21, 34, 54, 64, 189, 206, 239, 285, 425, 489},
 175: {162, 247, 272, 319, 425, 427, 522},
 176: {65, 68, 88, 91, 106, 203, 206, 239, 304, 314, 345, 351, 366, 426, 526},
 177: {88, 121, 123, 173, 189, 239, 251, 259, 263, 288, 359, 360, 387, 396},
 178: {9, 39, 92, 187, 189, 221, 223, 224, 259, 345, 387, 422},
 179: {95, 153, 215, 234, 242, 250, 282, 334, 360},
 180: {111, 173, 236, 278, 304, 345, 360, 387, 512},
 181: {39, 41, 95, 105, 119, 181, 202, 251, 279, 456, 526},
 182: {128, 155, 175, 190, 237, 314, 360, 524, 529, 531},
 183: {21, 190, 235, 260, 288, 331, 334, 346, 348, 359, 421, 456, 508},
 184: {55, 72, 95, 109, 208, 257, 364, 366},
 185: {127, 316, 332, 396, 416, 431, 460},
 186: {8, 18, 48, 69, 124, 283, 288, 348, 410, 440, 480, 532, 533},
 187: {91, 195, 240, 259, 280, 308, 454, 508},
 188: {45, 195, 240, 286, 387, 394, 415, 436, 537},
 189: {174, 247, 272, 352, 416, 427, 440, 525, 532},
 190: {1, 28, 156, 283, 347, 354, 443, 480, 519, 522},
 191: {31, 70, 91, 195, 240, 356, 476, 530},
 192: {13, 17, 87, 126, 182, 336, 396, 447, 523},
 193: {7, 84, 119, 199, 337, 360, 429},
 194: {45, 206, 226, 242, 272, 324, 345, 389, 456, 476, 489, 497, 530},
 195: {9,
  20,
  68,
  92,
  117,
  148,
  159,
  173,
  208,
  216,
  280,
  300,
  308,
  345,
  376,
  394,
  424,
  476,
  493},
 196: {159, 203, 237, 268, 305, 376, 377, 426, 518},
 197: {149, 187, 221, 224, 275, 304, 318, 384, 426, 501},
 198: {61, 113, 117, 207, 243, 324, 366},
 199: {1, 15, 102, 156, 178, 256, 283, 298, 326, 330, 349, 396, 443, 480},
 200: {9, 53, 152, 157, 171, 173, 196, 221, 278, 280, 304},
 201: {18, 120, 137, 156, 307, 336, 396},
 202: {31, 44, 85, 173, 187, 223, 224, 259},
 203: {41, 77, 91, 95, 227, 237, 294, 311, 314, 426, 440, 450, 492, 508, 534},
 204: {44, 199, 259, 345, 359, 409, 476},
 205: {71, 181, 251, 272, 319, 416, 421, 489, 532},
 206: {7, 107, 163, 238, 340, 426, 477},
 207: {21,
  65,
  68,
  91,
  129,
  138,
  175,
  228,
  260,
  308,
  312,
  317,
  327,
  351,
  356,
  361,
  412,
  424},
 208: {25,
  89,
  120,
  142,
  189,
  240,
  250,
  274,
  285,
  319,
  332,
  416,
  444,
  448,
  456,
  489,
  500,
  532},
 209: {11, 53, 148, 202, 251, 310, 409, 416, 429, 450},
 210: {56, 106, 171, 175, 308, 361, 384, 400, 422, 497},
 211: {44, 63, 81, 91, 173, 200, 261, 293, 304, 308, 360, 366, 367, 493, 531},
 212: {1,
  101,
  124,
  156,
  189,
  275,
  347,
  348,
  394,
  410,
  436,
  440,
  444,
  519,
  532},
 213: {130, 199, 210, 298, 365, 434, 436, 448, 477, 490},
 214: {7, 46, 119, 149, 174, 251, 295, 337, 340},
 215: {28, 89, 162, 199, 307, 341, 352, 365, 425, 494, 505, 516},
 216: {9, 39, 175, 187, 190, 221, 259, 356, 387, 389, 511, 524},
 217: {77, 94, 165, 199, 311, 348, 352, 421, 440, 456, 487, 489, 492, 532},
 218: {84,
  112,
  148,
  159,
  171,
  203,
  237,
  250,
  278,
  286,
  366,
  402,
  426,
  493,
  526},
 219: {60, 127, 173, 243, 366, 438, 501},
 220: {54, 120, 189, 195, 219, 278, 351},
 221: {21, 67, 91, 109, 111, 175, 278, 286, 293, 294, 300, 381, 389},
 222: {69, 115, 124, 176, 247, 275, 341, 410, 421, 427, 440},
 223: {78, 86, 106, 113, 175, 213, 286, 294, 308, 333, 334, 359, 422, 487},
 224: {255, 265, 272, 285, 296, 347, 352, 440, 444, 456, 489, 516, 518, 519},
 225: {100, 113, 173, 221, 314, 434, 456},
 226: {22,
  55,
  73,
  85,
  92,
  113,
  171,
  173,
  223,
  224,
  293,
  294,
  300,
  318,
  334,
  375,
  528},
 227: {50, 230, 236, 237, 250, 257, 376, 426},
 228: {187, 260, 331, 401, 425, 493, 524},
 229: {1, 11, 49, 126, 288, 303, 443, 480},
 230: {95, 239, 242, 250, 361, 384, 401},
 231: {91,
  106,
  135,
  152,
  217,
  239,
  250,
  261,
  278,
  304,
  308,
  345,
  359,
  360,
  382,
  493,
  512,
  537},
 232: {11, 69, 202, 319, 337, 434, 522},
 233: {64, 141, 156, 189, 199, 201, 272, 395, 416, 421, 489, 505, 523},
 234: {29, 34, 94, 124, 189, 275, 307, 348, 410, 425, 445, 489},
 235: {106, 171, 173, 203, 204, 234, 237, 278, 304, 314, 345, 360, 376, 400},
 236: {29, 153, 352, 397, 434, 489, 532},
 237: {18, 156, 182, 283, 339, 396, 443, 506},
 238: {53, 95, 138, 152, 171, 236, 286, 304, 356, 493, 526},
 239: {34,
  101,
  124,
  184,
  199,
  275,
  285,
  353,
  385,
  394,
  410,
  421,
  425,
  435,
  437,
  489,
  500},
 240: {8,
  17,
  87,
  101,
  124,
  176,
  181,
  182,
  189,
  194,
  265,
  285,
  316,
  348,
  363,
  380,
  405,
  410,
  416,
  425,
  437,
  440,
  456,
  470,
  505,
  541},
 241: {8,
  94,
  124,
  130,
  189,
  199,
  272,
  275,
  285,
  348,
  394,
  410,
  421,
  425,
  435,
  440,
  489,
  514},
 242: {45,
  94,
  115,
  124,
  153,
  199,
  247,
  341,
  348,
  394,
  410,
  421,
  427,
  456,
  486,
  514,
  522},
 243: {65,
  95,
  117,
  120,
  240,
  251,
  262,
  278,
  314,
  335,
  415,
  416,
  417,
  435,
  454,
  509},
 244: {46, 53, 109, 157, 221, 236, 250, 259, 294, 509},
 245: {13, 18, 101, 120, 130, 191, 199, 255, 348, 380, 416, 435, 489},
 246: {31,
  44,
  61,
  68,
  70,
  75,
  95,
  105,
  111,
  113,
  121,
  173,
  190,
  196,
  206,
  243,
  261,
  278,
  280,
  286,
  304,
  310,
  324,
  345,
  346,
  351,
  356,
  387,
  400,
  408,
  424,
  466,
  508,
  509,
  524,
  530},

In [7]:
def calculate_cosine_similarity(user1, user2, user_item_sets):
    items_user1 = user_item_sets.get(user1, set())
    items_user2 = user_item_sets.get(user2, set())
    
    # Calculate intersection of items
    intersection = len(items_user1.intersection(items_user2))
    
    # Compute the dot product of the vectors representing the item sets
    dot_product = intersection
    
    # Compute the magnitudes of the vectors
    magnitude_user1 = len(items_user1)
    magnitude_user2 = len(items_user2)
    
    # Handle division by zero
    if magnitude_user1 == 0 or magnitude_user2 == 0:
        return 0.0
    
    # Compute cosine similarity
    cosine_similarity = dot_product / (magnitude_user1 * magnitude_user2) ** 0.5
    return cosine_similarity

In [8]:
unique_users = train['user'].unique()

In [9]:
# number of elements
print(len(unique_users))

# equivalent for numpy arrays
print(unique_users.size)

# shape (useful for multi-dim arrays)
print(unique_users.shape)

1029
1029
(1029,)

In [10]:
from itertools import product

In [11]:
# Calculate Jaccard similarity for all user pairs
cosine_similarities = []

for user1, user2 in product(unique_users, repeat=2):
    if user1 != user2:
        similarity = calculate_cosine_similarity(user1, user2,user_item_sets)
        cosine_similarities.append({'User1': user1, 'User2': user2, 'Similarity': similarity})

In [12]:
# Create a DataFrame for Jaccard similarities
cosine_df = pd.DataFrame(cosine_similarities)

# Reshape the DataFrame to have User1, User2, and Similarity as columns
cosine_matrix = cosine_df.pivot(index='User1', columns='User2', values='Similarity')

idx = range(len(cosine_matrix))
cosine_matrix.values[idx, idx] = 1.0

In [13]:
cosine_df

         User1  User2  Similarity
0            1      2    0.000000
1            1      3    0.000000
2            1      4    0.000000
3            1      5    0.226134
4            1      6    0.000000
...        ...    ...         ...
1057807      0   1024    0.000000
1057808      0   1025    0.000000
1057809      0   1026    0.000000
1057810      0   1027    0.000000
1057811      0   1028    0.000000

[1057812 rows x 3 columns]

In [14]:
cosine_matrix

User2,0,1,2,3,4,5,6,7,8,9,...,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028
User1,,,,,,,,,,,,,,,,,,,,,
0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.0,1.000000,0.000000,0.000000,0.000000,0.226134,0.000000,0.106600,0.000000,0.000000,...,0.261116,0.090909,0.000000,0.000000,0.000000,0.000000,0.000000,0.128565,0.064282,0.000000
2,0.0,0.000000,1.000000,0.298142,0.079057,0.079057,0.190693,0.111803,0.105409,0.000000,...,0.091287,0.095346,0.000000,0.000000,0.119523,0.000000,0.000000,0.269680,0.000000,0.084515
3,0.0,0.000000,0.298142,1.000000,0.235702,0.058926,0.142134,0.083333,0.078567,0.000000,...,0.272166,0.213201,0.000000,0.000000,0.178174,0.223607,0.000000,0.201008,0.050252,0.000000
4,0.0,0.000000,0.079057,0.235702,1.000000,0.125000,0.075378,0.265165,0.083333,0.000000,...,0.000000,0.000000,0.106600,0.000000,0.094491,0.158114,0.149071,0.053300,0.053300,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,0.0,0.000000,0.000000,0.223607,0.158114,0.000000,0.095346,0.000000,0.000000,0.000000,...,0.182574,0.000000,0.067420,0.000000,0.119523,1.000000,0.000000,0.134840,0.067420,0.000000
1025,0.0,0.000000,0.000000,0.000000,0.149071,0.186339,0.089893,0.210819,0.049690,0.105409,...,0.000000,0.000000,0.286039,0.188562,0.056344,0.000000,1.000000,0.031782,0.095346,0.119523
1026,0.0,0.128565,0.269680,0.201008,0.053300,0.000000,0.128565,0.150756,0.000000,0.000000,...,0.184637,0.192847,0.045455,0.000000,0.080582,0.134840,0.031782,1.000000,0.045455,0.170941
1027,0.0,0.064282,0.000000,0.050252,0.053300,0.106600,0.000000,0.000000,0.213201,0.075378,...,0.000000,0.064282,0.090909,0.000000,0.161165,0.067420,0.095346,0.045455,1.000000,0.056980
1028,0.0,0.000000,0.084515,0.000000,0.000000,0.066815,0.080582,0.000000,0.089087,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.119523,0.170941,0.056980,1.000000

In [ ]:
key = pd.read_csv(f"{DATA_FILE_DIR}/politifact_Shu_fake_news_keyforSOCIALMF.csv")

In [17]:
key_news_id=key[["news_id_new","news_label"]].drop_duplicates(subset=["news_id_new"],keep="last").reset_index(drop=True)

In [18]:
key_news_id["fake_real_labels"]=key_news_id["news_label"].apply(lambda x:0 if x=="fake" else 1)

In [19]:
train= pd.merge(train,key_news_id,left_on="item",right_on="news_id_new", how='inner')

In [20]:
train=train.iloc[:,[0,1,2,4,5]]

In [21]:
interaction_counts = train.groupby(['user', 'news_label']).size().unstack(fill_value=0)
interaction_counts.rename(columns={'fake': 'fake_news_count', 'real': 'real_news_count'}, inplace=True)
interaction_counts=interaction_counts.reset_index()

In [22]:
interaction_counts=interaction_counts.loc[:,['user','fake_news_count','real_news_count']]

In [23]:
def reputation_user(alpha, beta):
    """
    Calculate the ratio (alpha + 1) / (alpha + beta + 2).

    Parameters:
    alpha (float): The alpha parameter.
    beta (float): The beta parameter.

    Returns:
    float: The calculated ratio.
    """
    ratio = (alpha) / (alpha + beta)
    return ratio

In [24]:
interaction_counts['reputation'] = (interaction_counts['real_news_count'])/ (interaction_counts['real_news_count'] + interaction_counts['fake_news_count'])

In [25]:
interaction_counts

news_label  user  fake_news_count  real_news_count  reputation
0              0                2                2    0.500000
1              1                3                8    0.727273
2              2                2                8    0.800000
3              3                4               14    0.777778
4              4               12                4    0.250000
...          ...              ...              ...         ...
1024        1024                1                9    0.900000
1025        1025               45                0    0.000000
1026        1026                5               17    0.772727
1027        1027               17                5    0.227273
1028        1028               12                2    0.142857

[1029 rows x 4 columns]

In [26]:
from collections import defaultdict

In [27]:
# Filter users based on reputation greater than 0.5
reputation_threshold = 0.6

trusted_users = interaction_counts[interaction_counts['reputation'] > reputation_threshold]['user']

untrusted_users = interaction_counts[interaction_counts['reputation'] <= reputation_threshold]['user'] # Save as a untrusted user list and use it to the social space ss60

# Dictionary to store top similar trustworthy users for each user
top_trustworthy_similar_users = defaultdict(set)

# Iterate over each user
for user in cosine_matrix.index:
    # Get cosine similarity values for the user
    user_similarity = cosine_matrix.loc[user]
    # Exclude untrustworthy similar users (reputation <= 0.6) and the user itself
    similar_trustworthy_users = user_similarity[(user_similarity > 0) & (interaction_counts.loc[user_similarity.index, 'reputation'] > reputation_threshold) & (user_similarity.index != user)]
    # Sort similar trustworthy users by similarity (descending order) and take the top 10
    temp=set(similar_trustworthy_users.sort_values(ascending=False).index[:10].tolist())
    if len(temp)>0:
        top_trustworthy_similar_users[user] =set(similar_trustworthy_users.sort_values(ascending=False).index[:10].tolist())

In [28]:
# Convert to a simple Python list
untrusted_users_list_ss60 = untrusted_users.tolist()

# Save as pickle file
import pickle
with open('/home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/processed-files/untrusted_users_ss60.pickle', 'wb') as f:
    pickle.dump(untrusted_users_list_ss60, f)

print(f"Saved {len(untrusted_users_list_ss60)} untrusted users")
print("Preview:", untrusted_users_list_ss60[:10])  # Show first 10

# Later, to load it:
# with open('untrusted_users.pickle', 'rb') as f:
#     untrusted_users_list = pickle.load(f)

Saved 660 untrusted users
Preview: [0, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [29]:
top_trustworthy_similar_users

defaultdict(set,
            {1: {96, 168, 239, 266, 267, 289, 591, 717, 744, 913},
             2: {124, 224, 289, 429, 432, 452, 528, 682, 698, 916},
             3: {26, 161, 272, 307, 349, 362, 463, 521, 762, 956},
             4: {3, 112, 236, 279, 362, 431, 463, 653, 956, 1015},
             5: {1, 130, 267, 425, 502, 591, 614, 717, 744, 840},
             6: {72, 147, 333, 362, 397, 537, 791, 956, 962, 985},
             7: {164, 266, 279, 289, 333, 362, 471, 573, 591, 791},
             8: {44, 130, 165, 357, 454, 698, 713, 778, 956, 985},
             9: {60, 113, 266, 388, 425, 527, 563, 570, 865, 909},
             10: {97, 185, 583, 591, 649, 796, 849, 865, 991, 1024},
             11: {1, 130, 258, 425, 554, 614, 717, 887, 909, 919},
             12: {326, 334, 411, 540, 879, 1010},
             13: {44, 60, 81, 160, 440, 442, 515, 698, 703, 864},
             14: {189, 229, 288, 440, 596, 600, 637, 849, 879, 909},
             15: {78, 189, 217, 229, 440, 471, 596, 837, 879, 909},
             16: {60, 76, 408, 426, 568, 591, 635, 655, 857, 909},
             17: {41, 147, 222, 307, 419, 535, 566, 650, 733, 925},
             18: {113, 251, 266, 309, 388, 493, 653, 747, 809, 906},
             19: {299, 370, 429, 432, 452, 493, 528, 619, 809, 824},
             20: {26, 98, 269, 394, 521, 550, 553, 666, 791, 1013},
             21: {242, 393, 394, 521, 620, 675, 864, 955, 964, 985},
             22: {738, 872, 909},
             23: {45, 106, 167, 208, 357, 454, 580, 749, 913, 1010},
             24: {39, 140, 199, 249, 389, 449, 516, 599, 894, 922},
             25: {33, 60, 74, 224, 273, 442, 857, 862, 945, 961},
             26: {20, 362, 394, 521, 566, 670, 791, 831, 962, 967},
             27: {17, 60, 299, 408, 535, 650, 675, 879, 925, 1012},
             28: {170, 266, 279, 408, 425, 549, 582, 591, 655, 738},
             29: {60, 100, 167, 172, 236, 307, 456, 647, 861, 1004},
             30: {117, 130, 394, 452, 521, 553, 666, 840, 967, 977},
             31: {44, 119, 160, 408, 454, 563, 738, 749, 782, 913},
             32: {307, 326, 358, 508, 635, 670, 871, 916, 935, 956},
             33: {3, 20, 72, 241, 349, 391, 433, 719, 762, 989},
             34: {24, 140, 185, 275, 342, 495, 540, 599, 747, 1009},
             35: {61, 266, 279, 299, 408, 440, 454, 570, 800, 991},
             36: {141, 217, 371, 411, 615, 749, 1010},
             37: {78, 119, 440, 738, 837, 872},
             38: {61, 266, 279, 299, 408, 442, 570, 637, 800, 991},
             39: {125, 140, 190, 199, 342, 462, 473, 516, 945, 966},
             40: {60, 100, 146, 408, 442, 637, 800, 909, 991, 1015},
             41: {17, 147, 222, 514, 535, 649, 650, 675, 733, 925},
             42: {61, 165, 258, 266, 299, 357, 408, 442, 991, 1004},
             43: {170, 367, 379, 411, 425, 527, 568, 865, 909, 913},
             44: {19, 41, 124, 160, 164, 273, 383, 493, 824, 1026},
             45: {263, 333, 362, 380, 528, 553, 670, 916, 983, 994},
             46: {1, 141, 170, 408, 425, 591, 717, 738, 744, 840},
             47: {44, 100, 326, 442, 537, 621, 637, 864, 879, 958},
             48: {39, 199, 305, 342, 430, 462, 473, 481, 516, 966},
             49: {103, 240, 245, 289, 333, 387, 703, 791, 829, 934},
             50: {100, 418, 455, 470, 541, 637, 648, 703, 913, 998},
             51: {266, 279, 408, 454, 570, 637, 945},
             52: {370, 391, 550, 652, 681, 832, 917, 964, 985, 1000},
             53: {39, 237, 579, 656, 785, 802, 894, 930, 945, 966},
             54: {60, 299, 591, 703, 738, 749, 800, 909, 991, 1015},
             55: {61, 160, 408, 440, 454, 738, 909, 976},
             56: {123, 167, 279, 431, 471, 570, 575, 647, 738, 861},
             57: {105, 217, 273, 311, 334, 440, 849, 934, 989, 1017},
             58: {106, 113, 266, 425, 563, 582, 637, 865, 1010, 1015},
             59: {100, 173, 241, 387, 477, 559, 569, 727, 762, 1004},
             60: {161, 362, 394, 492, 613, 652, 698, 791, 967, 994},
             61: {440, 535, 675, 733, 785, 850, 916, 955, 962, 977},
             62: {119, 208, 258, 266, 408, 411, 442, 469, 909, 1010},
             63: {44, 229, 334, 442, 591, 600, 637, 864, 879, 909},
             64: {119, 217, 440, 464, 688, 792, 837, 973, 989, 1026},
             65: {3, 258, 279, 357, 471, 554, 647, 713, 738, 1010},
             66: {655},
             67: {78, 160, 440},
             68: {100, 315, 388, 569, 727, 917, 919, 1004, 1011, 1019},
             69: {44, 60, 175, 258, 397, 426, 440, 698, 852, 985},
             70: {49, 105, 112, 334, 492, 540, 636, 681, 749, 934},
             71: {258, 279, 442, 527, 572, 655, 765, 887, 890, 1024},
             72: {20, 33, 239, 241, 470, 535, 559, 573, 636, 688},
             73: {61, 397, 426, 520, 570, 637, 738, 871, 878, 1009},
             74: {24, 33, 224, 272, 430, 438, 519, 687, 778, 916},
             75: {172, 408, 554, 563, 582, 637, 749, 865, 913, 1010},
             76: {77, 98, 117, 212, 242, 387, 553, 714, 733, 989},
             77: {76, 98, 240, 241, 477, 537, 553, 733, 887, 1020},
             78: {19, 44, 119, 273, 383, 458, 493, 809, 837, 854},
             79: {160, 334, 440, 454, 540, 591, 637, 872},
             80: {106, 170, 266, 432, 563, 570, 582, 738, 878, 1012},
             81: {26, 161, 269, 349, 521, 566, 666, 906, 916, 1013},
             82: {60, 208, 440, 703, 852, 1026},
             83: {130, 164, 165, 167, 175, 455, 456, 713, 872, 1026},
             84: {60, 229, 440, 442, 600, 703, 747, 852, 879, 909},
             85: {106, 113, 205, 262, 289, 422, 432, 591, 613, 738},
             87: {113, 165, 229, 371, 422, 493, 653, 809, 964, 991},
             88: {52, 160, 185, 360, 454, 456, 637, 738, 749, 961},
             89: {208, 251, 279, 333, 452, 454, 527, 582, 749, 964},
             90: {45, 554, 563, 580, 582, 698, 864, 909, 983, 1010},
             91: {44, 60, 266, 273, 371, 408, 442, 563, 637, 909},
             92: {78, 119, 146, 189, 288, 440, 471, 596, 837, 849},
             93: {44, 229, 334, 515, 600, 703, 778, 864, 879, 909},
             94: {60, 61, 408, 440, 454, 703, 852},
             95: {44, 279, 388, 426, 570, 580, 582, 637, 1010, 1015},
             96: {81, 168, 265, 431, 559, 573, 762, 829, 906, 919},
             97: {98, 334, 369, 389, 393, 583, 832, 849, 922, 995},
             98: {20, 76, 147, 387, 521, 553, 728, 791, 819, 977},
             99: {229, 266, 279, 334, 442, 600, 637, 655, 879, 909},
             100: {241, 357, 407, 464, 477, 502, 727, 917, 998, 1019},
             101: {44, 81, 100, 160, 515, 698, 738, 864, 958, 985},
             102: {61, 175, 258, 397, 408, 426, 442, 456, 541, 871},
             103: {3, 26, 326, 670, 791, 820, 829, 831, 906, 1013},
             104: {61, 168, 234, 360, 580, 666, 691, 788, 858, 977},
             105: {112, 455, 492, 569, 647, 727, 861, 917, 985, 1004},
             106: {126, 233, 251, 381, 417, 425, 432, 463, 637, 865},
             107: {170, 258, 554, 655, 672, 879, 887, 991, 1010, 1024},
             108: {326, 408, 426, 591, 605, 800, 879, 885, 991, 1004},
             109: {44, 81, 160, 334, 411, 515, 540, 698, 864, 985},
             110: {146, 236, 440, 464, 565, 656, 688, 694, 973, 1026},
             111: {263, 360, 440, 872, 983},
             112: {123, 236, 269, 394, 463, 492, 647, 810, 861, 956},
             113: {266, 309, 388, 425, 493, 554, 809, 906, 998, 1008},
             114: {160, 440, 909},
             115: {213, 241, 245, 326, 438, 477, 762, 872, 895, 991},
             116: {258, 315, 363, 394, 492, 637, 670, 727, 824, 906},
             117: {26, 30, 76, 521, 553, 580, 676, 728, 791, 977},
             118: {192, 229, 408, 502, 605, 689, 802, 849, 894, 991},
             119: {34, 78, 81, 160, 326, 339, 563, 774, 837, 854},
             120: {105, 371, 477, 569, 840, 919, 985, 998, 1004, 1011},
             121: {170, 258, 273, 326, 426, 442, 516, 648, 778, 840},
             122: {44, 201, 229, 540, 738, 778, 802, 909, 943, 1010},
             123: {17, 112, 222, 307, 535, 566, 647, 650, 861, 1012},
             124: {2, 33, 44, 72, 224, 289, 383, 419, 432, 493},
             125: {24, 39, 140, 199, 249, 342, 449, 462, 473, 583},
             126: {106, 170, 249, 379, 493, 568, 615, 672, 858, 1000},
             127: {61, 408, 976},
             128: {60, 371, 408, 440, 442, 527, 615, 738, 872, 961},
             129: {165, 349, 357, 360, 456, 647, 655, 713, 913, 925},
             130: {239, 241, 477, 521, 537, 549, 698, 728, 977, 985},
             131: {60, 167, 266, 357, 408, 706, 788, 906, 913, 976},
             132: {44, 81, 160, 334, 442, 515, 540, 698, 864, 985},
             133: {44, 52, 160, 166, 273, 442, 778, 862, 909, 961},
             134: {60, 130, 251, 381, 417, 440, 454, 537, 857, 976},
             135: {263, 360, 432, 452, 520, 521, 550, 666, 854, 962},
             136: {44, 60, 146, 273, 334, 383, 408, 515, 591, 864},
             137: {44, 78, 106, 273, 371, 383, 637, 738, 749, 1015},
             138: {60, 440, 909, 976, 1026},
             139: {44, 78, 273, 334, 383, 540, 570},
             140: {24, 39, 125, 199, 249, 449, 462, 574, 599, 966},
             141: {61, 234, 239, 258, 451, 470, 493, 507, 705, 977},
             142: {44, 81, 160, 454, 515, 570, 637, 698, 864, 909},
             143: {279, 371, 408, 591, 637, 655, 765, 800, 890, 991},
             144: {166, 357, 407, 462, 473, 481, 495, 778, 894, 945},
             145: {162, 192, 426, 441, 624, 671, 672, 738, 852, 878},
             146: {33, 147, 212, 236, 272, 387, 688, 733, 762, 934},
             147: {41, 242, 307, 387, 419, 566, 650, 675, 733, 850},
             148: {60, 100, 170, 334, 442, 540, 637, 738, 958, 1010},
             149: {44, 97, 185, 454, 596, 649, 849, 864, 909, 1024},
             150: {60, 160, 189, 288, 408, 440, 454, 572, 596, 849},
             151: {60, 135, 172, 208, 371, 411, 527, 615, 749, 1015},
             152: {96, 451, 573, 706, 732, 749, 849, 906, 934, 983},
             153: {76, 100, 387, 388, 563, 717, 719, 780, 909, 989},
             154: {208, 299, 408, 442, 570, 800, 991},
             155: {60, 229, 408, 440, 442, 600, 703, 747, 879, 909},
             156: {165, 172, 208, 411, 454, 703, 749, 909, 919, 945},
             157: {61, 408, 411, 440, 945, 1010},
             158: {60, 78, 408, 440, 454, 637, 703, 778, 852},
             159: {113, 170, 266, 388, 563, 655, 749, 909, 1010, 1015},
             160: {19, 164, 212, 263, 289, 326, 429, 682, 809, 837},
             161: {3, 130, 241, 362, 394, 451, 521, 676, 762, 805},
             162: {186, 236, 266, 422, 471, 575, 738, 791, 820, 967},
             163: {44, 160, 478, 515, 572, 637, 765, 864, 879, 890},
             164: {289, 328, 377, 431, 493, 527, 800, 809, 1000, 1026},
             165: {61, 130, 360, 364, 377, 380, 580, 605, 919, 1011},
             166: {190, 205, 449, 481, 515, 778, 894, 930, 945, 966},
             167: {26, 234, 553, 575, 670, 808, 810, 861, 967, 1020},
             168: {239, 446, 451, 559, 762, 788, 791, 824, 858, 977},
             169: {100, 334, 442, 540, 732, 958},
             170: {126, 299, 379, 389, 446, 449, 514, 599, 858, 925},
             171: {60, 442},
             172: {3, 26, 262, 307, 463, 647, 706, 906, 967, 1004},
             173: {239, 241, 284, 309, 477, 502, 549, 559, 727, 762},
             174: {141, 234, 239, 258, 394, 470, 493, 580, 666, 1010},
             175: {41, 147, 189, 492, 535, 785, 850, 977, 983, 1012},
             176: {44, 160, 170, 442, 637, 655, 738, 864, 909, 1010},
             177: {106, 113, 266, 289, 328, 433, 442, 655, 809, 1008},
             178: {106, 167, 266, 357, 418, 635, 713, 913, 956, 998},
             179: {112, 236, 299, 334, 336, 796, 800, 872, 879, 991},
             180: {44, 81, 160, 299, 408, 442, 515, 800, 864, 991},
             181: {2, 135, 205, 289, 360, 425, 613, 703, 869, 994},
             182: {141, 299, 408, 440, 454, 749, 800, 945, 991},
             183: {49, 103, 117, 333, 363, 527, 614, 728, 791, 831},
             184: {334, 440, 540, 909},
             185: {34, 275, 339, 389, 583, 782, 849, 865, 922, 961},
             186: {76, 269, 358, 374, 647, 714, 728, 871, 912, 1013},
             187: {100, 113, 172, 266, 388, 425, 563, 582, 637, 909},
             188: {60, 387, 425, 563, 582, 591, 637, 652, 909, 1015},
             189: {21, 61, 175, 205, 391, 535, 785, 916, 955, 1013},
             190: {39, 140, 199, 273, 449, 515, 516, 894, 945, 966},
             191: {113, 165, 266, 388, 411, 563, 637, 865, 909, 1010},
             192: {21, 389, 430, 458, 565, 574, 615, 672, 694, 973},
             193: {164, 328, 418, 422, 429, 541, 648, 895, 991, 998},
             194: {117, 224, 364, 614, 637, 652, 670, 774, 864, 976},
             195: {72, 164, 266, 349, 397, 440, 469, 470, 591, 613},
             196: {33, 74, 224, 273, 336, 440, 596, 857, 945, 961},
             197: {44, 160, 258, 358, 455, 649, 737, 778, 871, 909},
             198: {872, 909},
             199: {39, 125, 140, 249, 342, 462, 473, 481, 516, 966},
             200: {44, 146, 160, 266, 279, 408, 515, 570, 591, 864},
             201: {24, 61, 237, 389, 446, 449, 478, 615, 885, 922},
             202: {49, 105, 112, 165, 492, 636, 681, 749, 919, 945},
             203: {78, 160, 217, 440, 792, 837, 861, 871, 956, 989},
             204: {370, 371, 418, 422, 455, 470, 541, 563, 648, 998},
             205: {135, 233, 345, 380, 470, 550, 553, 670, 819, 1020},
             206: {97, 213, 434, 440, 572, 583, 765, 824, 849, 890},
             207: {100, 170, 408, 411, 554, 637, 738, 958, 976, 1010},
             208: {161, 315, 394, 411, 580, 670, 749, 788, 906, 1011},
             209: {113, 126, 205, 360, 422, 449, 493, 681, 703, 1000},
             210: {100, 591, 958, 976},
             211: {44, 60, 160, 299, 515, 637, 800, 864, 909, 991},
             212: {76, 241, 272, 358, 431, 649, 733, 800, 871, 887},
             213: {370, 438, 455, 473, 765, 878, 885, 890, 895, 930},
             214: {106, 124, 135, 162, 273, 360, 422, 572, 596, 738},
             215: {61, 446, 559, 621, 785, 788, 850, 858, 879, 977},
             216: {141, 266, 279, 408, 570, 749, 854, 1010},
             217: {117, 521, 550, 614, 666, 727, 728, 791, 916, 935},
             218: {60, 160, 208, 336, 408, 440, 454, 591, 637, 909},
             219: {97, 185, 583, 649, 796, 849, 865, 909, 973, 1024},
             220: {113, 266, 388, 425, 563, 637, 738, 865, 1010, 1015},
             221: {60, 61, 408, 440, 454, 637, 738, 749, 852, 1015},
             222: {17, 147, 242, 307, 358, 419, 514, 650, 733, 925},
             223: {217, 371, 454, 615, 637, 738, 872},
             224: {2, 74, 135, 263, 432, 452, 455, 670, 778, 1026},
             225: {103, 349, 362, 364, 452, 455, 653, 791, 831, 967},
             226: {49, 60, 105, 492, 591, 636, 681, 738, 749, 852},
             227: {160, 208, 440, 454},
             228: {44, 175, 258, 273, 397, 426, 456, 541, 705, 871},
             229: {39, 125, 140, 190, 442, 574, 599, 747, 894, 966},
             230: {44, 100, 273, 334, 383, 442, 540, 879, 958, 976},
             231: {1, 44, 266, 371, 408, 442, 591, 717, 864, 991},
             232: {112, 175, 363, 394, 422, 431, 572, 647, 861, 967},
             233: {205, 241, 380, 521, 550, 614, 653, 666, 782, 913},
             234: {141, 241, 272, 394, 553, 705, 762, 871, 887, 977},
             235: {44, 299, 408, 442, 515, 591, 800, 864, 945, 991},
             236: {112, 345, 362, 394, 422, 492, 569, 647, 967, 1004},
             237: {201, 249, 389, 449, 615, 694, 802, 894, 922, 966},
             238: {44, 81, 160, 334, 454, 515, 540, 591, 637, 864},
             239: {130, 241, 352, 394, 451, 470, 559, 762, 805, 887},
             240: {3, 77, 130, 241, 440, 521, 666, 762, 871, 1013},
             241: {234, 239, 352, 387, 477, 559, 727, 762, 887, 977},
             242: {147, 222, 241, 307, 387, 419, 566, 650, 733, 791},
             243: {106, 172, 208, 245, 408, 411, 425, 563, 749, 913},
             244: {146, 208, 440, 732, 738},
             245: {241, 352, 550, 614, 666, 782, 788, 872, 913, 955},
             246: {44, 141, 165, 170, 334, 408, 454, 637, 738, 864},
             247: {44, 201, 229, 540, 712, 778, 802, 879, 909, 943},
             248: {130, 165, 208, 299, 408, 454, 800, 919, 945, 991},
             249: {24, 39, 140, 199, 237, 389, 462, 568, 583, 922},
             250: {113, 175, 363, 481, 624, 648, 649, 800, 861, 998},
             251: {161, 208, 263, 333, 363, 381, 417, 653, 747, 774},
             252: {24, 284, 397, 434, 514, 593, 719, 780, 850, 989},
             253: {279, 371, 408, 570, 655, 765, 800, 865, 890, 991},
             254: {76, 426, 508, 563, 568, 582, 591, 635, 672, 909},
             255: {164, 170, 208, 508, 568, 591, 681, 749, 912, 925},
             256: {119, 162, 201, 237, 323, 440, 478, 689, 849, 894},
             257: {112, 492, 519, 572, 647, 670, 800, 861, 916, 994},
             258: {130, 141, 241, 360, 477, 519, 670, 887, 919, 1015},
             259: {135, 349, 360, 433, 438, 572, 647, 713, 829, 895},
             260: {161, 315, 380, 569, 613, 637, 727, 917, 985, 1011},
             261: {418, 422, 470, 550, 580, 582, 637, 703, 985, 1011},
             262: {20, 172, 345, 433, 456, 463, 575, 647, 738, 1013},
             263: {135, 161, 224, 360, 528, 670, 691, 762, 778, 852},
             264: {345, 380, 408, 469, 534, 854, 879, 991, 1000, 1026},
             265: {20, 26, 96, 431, 463, 604, 791, 796, 850, 962},
             266: {1, 113, 168, 272, 425, 788, 809, 865, 906, 1015},
             267: {1, 168, 266, 495, 575, 591, 744, 808, 869, 1019},
             268: {172, 266, 307, 411, 425, 563, 637, 810, 956, 1015},
             269: {20, 112, 186, 349, 358, 374, 521, 647, 714, 800},
             270: {61, 147, 222, 419, 604, 675, 733, 785, 850, 991},
             271: {60, 172, 208, 266, 408, 411, 655, 934, 956, 976},
             272: {3, 161, 234, 241, 299, 358, 762, 871, 887, 977},
             273: {19, 44, 78, 164, 190, 224, 263, 383, 528, 824},
             274: {258, 266, 388, 637, 749, 872, 976, 1010, 1015, 1020},
             275: {140, 199, 249, 462, 481, 583, 599, 671, 894, 966},
             276: {146, 440, 655, 945},
             277: {44, 160, 334, 440, 454, 515, 570, 596, 778, 864},
             278: {100, 208, 408, 411, 554, 778, 909, 958, 976, 1010},
             279: {362, 431, 456, 471, 570, 647, 738, 810, 832, 861},
             280: {408, 440, 909, 1026},
             281: {60, 105, 236, 279, 456, 647, 655, 738, 861, 1004},
             282: {100, 266, 279, 570, 637, 655, 703, 872, 909, 1010},
             283: {119, 170, 233, 478, 502, 574, 637, 672, 909, 1010},
             284: {34, 166, 173, 240, 339, 446, 694, 792, 913, 945},
             285: {164, 170, 328, 442, 493, 527, 637, 712, 964, 1000},
             286: {165, 279, 371, 442, 655, 765, 890, 919, 945, 991},
             287: {45, 135, 263, 360, 469, 534, 579, 681, 852, 879},
             288: {77, 112, 201, 333, 394, 418, 652, 906, 934, 998},
             289: {2, 49, 164, 168, 333, 419, 493, 613, 809, 1026},
             290: {78, 217, 471, 837},
             291: {44, 146, 160, 326, 440, 441, 442, 591, 738, 879},
             292: {45, 270, 273, 408, 426, 648, 687, 738, 966, 991},
             293: {60, 279, 371, 388, 527, 615, 655, 749, 976, 1010},
             294: {234, 388, 418, 534, 563, 637, 691, 705, 977, 1010},
             295: {76, 167, 192, 408, 430, 434, 442, 852, 879, 991},
             296: {205, 397, 605, 613, 676, 703, 906, 916, 994, 1015},
             297: {44, 52, 189, 273, 288, 311, 383, 391, 471, 909},
             298: {44, 175, 408, 442, 481, 624, 649, 800, 861, 998},
             299: {19, 123, 272, 514, 535, 573, 650, 850, 955, 1012},
             300: {160, 279, 299, 360, 408, 655, 800, 945, 983, 991},

In [30]:
import pickle

# Specify the path to your pickle file
pickle_file_path = "/home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/processed-files/TrustWorthy_Politifact_MAGrec.pickle"

# Open the pickle file in read binary mode
with open(pickle_file_path, 'rb') as file:
    # Load the data from the pickle file
    loaded_data = pickle.load(file)

In [31]:
history_u_lists, history_ur_lists, history_v_lists, history_vr_lists, train_u, train_v, train_r, test_u, test_v, test_r, social_adj_lists, ratings_list=loaded_data

In [32]:
social_adj_lists=top_trustworthy_similar_users

In [33]:
social_adj_lists

defaultdict(set,
            {1: {96, 168, 239, 266, 267, 289, 591, 717, 744, 913},
             2: {124, 224, 289, 429, 432, 452, 528, 682, 698, 916},
             3: {26, 161, 272, 307, 349, 362, 463, 521, 762, 956},
             4: {3, 112, 236, 279, 362, 431, 463, 653, 956, 1015},
             5: {1, 130, 267, 425, 502, 591, 614, 717, 744, 840},
             6: {72, 147, 333, 362, 397, 537, 791, 956, 962, 985},
             7: {164, 266, 279, 289, 333, 362, 471, 573, 591, 791},
             8: {44, 130, 165, 357, 454, 698, 713, 778, 956, 985},
             9: {60, 113, 266, 388, 425, 527, 563, 570, 865, 909},
             10: {97, 185, 583, 591, 649, 796, 849, 865, 991, 1024},
             11: {1, 130, 258, 425, 554, 614, 717, 887, 909, 919},
             12: {326, 334, 411, 540, 879, 1010},
             13: {44, 60, 81, 160, 440, 442, 515, 698, 703, 864},
             14: {189, 229, 288, 440, 596, 600, 637, 849, 879, 909},
             15: {78, 189, 217, 229, 440, 471, 596, 837, 879, 909},
             16: {60, 76, 408, 426, 568, 591, 635, 655, 857, 909},
             17: {41, 147, 222, 307, 419, 535, 566, 650, 733, 925},
             18: {113, 251, 266, 309, 388, 493, 653, 747, 809, 906},
             19: {299, 370, 429, 432, 452, 493, 528, 619, 809, 824},
             20: {26, 98, 269, 394, 521, 550, 553, 666, 791, 1013},
             21: {242, 393, 394, 521, 620, 675, 864, 955, 964, 985},
             22: {738, 872, 909},
             23: {45, 106, 167, 208, 357, 454, 580, 749, 913, 1010},
             24: {39, 140, 199, 249, 389, 449, 516, 599, 894, 922},
             25: {33, 60, 74, 224, 273, 442, 857, 862, 945, 961},
             26: {20, 362, 394, 521, 566, 670, 791, 831, 962, 967},
             27: {17, 60, 299, 408, 535, 650, 675, 879, 925, 1012},
             28: {170, 266, 279, 408, 425, 549, 582, 591, 655, 738},
             29: {60, 100, 167, 172, 236, 307, 456, 647, 861, 1004},
             30: {117, 130, 394, 452, 521, 553, 666, 840, 967, 977},
             31: {44, 119, 160, 408, 454, 563, 738, 749, 782, 913},
             32: {307, 326, 358, 508, 635, 670, 871, 916, 935, 956},
             33: {3, 20, 72, 241, 349, 391, 433, 719, 762, 989},
             34: {24, 140, 185, 275, 342, 495, 540, 599, 747, 1009},
             35: {61, 266, 279, 299, 408, 440, 454, 570, 800, 991},
             36: {141, 217, 371, 411, 615, 749, 1010},
             37: {78, 119, 440, 738, 837, 872},
             38: {61, 266, 279, 299, 408, 442, 570, 637, 800, 991},
             39: {125, 140, 190, 199, 342, 462, 473, 516, 945, 966},
             40: {60, 100, 146, 408, 442, 637, 800, 909, 991, 1015},
             41: {17, 147, 222, 514, 535, 649, 650, 675, 733, 925},
             42: {61, 165, 258, 266, 299, 357, 408, 442, 991, 1004},
             43: {170, 367, 379, 411, 425, 527, 568, 865, 909, 913},
             44: {19, 41, 124, 160, 164, 273, 383, 493, 824, 1026},
             45: {263, 333, 362, 380, 528, 553, 670, 916, 983, 994},
             46: {1, 141, 170, 408, 425, 591, 717, 738, 744, 840},
             47: {44, 100, 326, 442, 537, 621, 637, 864, 879, 958},
             48: {39, 199, 305, 342, 430, 462, 473, 481, 516, 966},
             49: {103, 240, 245, 289, 333, 387, 703, 791, 829, 934},
             50: {100, 418, 455, 470, 541, 637, 648, 703, 913, 998},
             51: {266, 279, 408, 454, 570, 637, 945},
             52: {370, 391, 550, 652, 681, 832, 917, 964, 985, 1000},
             53: {39, 237, 579, 656, 785, 802, 894, 930, 945, 966},
             54: {60, 299, 591, 703, 738, 749, 800, 909, 991, 1015},
             55: {61, 160, 408, 440, 454, 738, 909, 976},
             56: {123, 167, 279, 431, 471, 570, 575, 647, 738, 861},
             57: {105, 217, 273, 311, 334, 440, 849, 934, 989, 1017},
             58: {106, 113, 266, 425, 563, 582, 637, 865, 1010, 1015},
             59: {100, 173, 241, 387, 477, 559, 569, 727, 762, 1004},
             60: {161, 362, 394, 492, 613, 652, 698, 791, 967, 994},
             61: {440, 535, 675, 733, 785, 850, 916, 955, 962, 977},
             62: {119, 208, 258, 266, 408, 411, 442, 469, 909, 1010},
             63: {44, 229, 334, 442, 591, 600, 637, 864, 879, 909},
             64: {119, 217, 440, 464, 688, 792, 837, 973, 989, 1026},
             65: {3, 258, 279, 357, 471, 554, 647, 713, 738, 1010},
             66: {655},
             67: {78, 160, 440},
             68: {100, 315, 388, 569, 727, 917, 919, 1004, 1011, 1019},
             69: {44, 60, 175, 258, 397, 426, 440, 698, 852, 985},
             70: {49, 105, 112, 334, 492, 540, 636, 681, 749, 934},
             71: {258, 279, 442, 527, 572, 655, 765, 887, 890, 1024},
             72: {20, 33, 239, 241, 470, 535, 559, 573, 636, 688},
             73: {61, 397, 426, 520, 570, 637, 738, 871, 878, 1009},
             74: {24, 33, 224, 272, 430, 438, 519, 687, 778, 916},
             75: {172, 408, 554, 563, 582, 637, 749, 865, 913, 1010},
             76: {77, 98, 117, 212, 242, 387, 553, 714, 733, 989},
             77: {76, 98, 240, 241, 477, 537, 553, 733, 887, 1020},
             78: {19, 44, 119, 273, 383, 458, 493, 809, 837, 854},
             79: {160, 334, 440, 454, 540, 591, 637, 872},
             80: {106, 170, 266, 432, 563, 570, 582, 738, 878, 1012},
             81: {26, 161, 269, 349, 521, 566, 666, 906, 916, 1013},
             82: {60, 208, 440, 703, 852, 1026},
             83: {130, 164, 165, 167, 175, 455, 456, 713, 872, 1026},
             84: {60, 229, 440, 442, 600, 703, 747, 852, 879, 909},
             85: {106, 113, 205, 262, 289, 422, 432, 591, 613, 738},
             87: {113, 165, 229, 371, 422, 493, 653, 809, 964, 991},
             88: {52, 160, 185, 360, 454, 456, 637, 738, 749, 961},
             89: {208, 251, 279, 333, 452, 454, 527, 582, 749, 964},
             90: {45, 554, 563, 580, 582, 698, 864, 909, 983, 1010},
             91: {44, 60, 266, 273, 371, 408, 442, 563, 637, 909},
             92: {78, 119, 146, 189, 288, 440, 471, 596, 837, 849},
             93: {44, 229, 334, 515, 600, 703, 778, 864, 879, 909},
             94: {60, 61, 408, 440, 454, 703, 852},
             95: {44, 279, 388, 426, 570, 580, 582, 637, 1010, 1015},
             96: {81, 168, 265, 431, 559, 573, 762, 829, 906, 919},
             97: {98, 334, 369, 389, 393, 583, 832, 849, 922, 995},
             98: {20, 76, 147, 387, 521, 553, 728, 791, 819, 977},
             99: {229, 266, 279, 334, 442, 600, 637, 655, 879, 909},
             100: {241, 357, 407, 464, 477, 502, 727, 917, 998, 1019},
             101: {44, 81, 100, 160, 515, 698, 738, 864, 958, 985},
             102: {61, 175, 258, 397, 408, 426, 442, 456, 541, 871},
             103: {3, 26, 326, 670, 791, 820, 829, 831, 906, 1013},
             104: {61, 168, 234, 360, 580, 666, 691, 788, 858, 977},
             105: {112, 455, 492, 569, 647, 727, 861, 917, 985, 1004},
             106: {126, 233, 251, 381, 417, 425, 432, 463, 637, 865},
             107: {170, 258, 554, 655, 672, 879, 887, 991, 1010, 1024},
             108: {326, 408, 426, 591, 605, 800, 879, 885, 991, 1004},
             109: {44, 81, 160, 334, 411, 515, 540, 698, 864, 985},
             110: {146, 236, 440, 464, 565, 656, 688, 694, 973, 1026},
             111: {263, 360, 440, 872, 983},
             112: {123, 236, 269, 394, 463, 492, 647, 810, 861, 956},
             113: {266, 309, 388, 425, 493, 554, 809, 906, 998, 1008},
             114: {160, 440, 909},
             115: {213, 241, 245, 326, 438, 477, 762, 872, 895, 991},
             116: {258, 315, 363, 394, 492, 637, 670, 727, 824, 906},
             117: {26, 30, 76, 521, 553, 580, 676, 728, 791, 977},
             118: {192, 229, 408, 502, 605, 689, 802, 849, 894, 991},
             119: {34, 78, 81, 160, 326, 339, 563, 774, 837, 854},
             120: {105, 371, 477, 569, 840, 919, 985, 998, 1004, 1011},
             121: {170, 258, 273, 326, 426, 442, 516, 648, 778, 840},
             122: {44, 201, 229, 540, 738, 778, 802, 909, 943, 1010},
             123: {17, 112, 222, 307, 535, 566, 647, 650, 861, 1012},
             124: {2, 33, 44, 72, 224, 289, 383, 419, 432, 493},
             125: {24, 39, 140, 199, 249, 342, 449, 462, 473, 583},
             126: {106, 170, 249, 379, 493, 568, 615, 672, 858, 1000},
             127: {61, 408, 976},
             128: {60, 371, 408, 440, 442, 527, 615, 738, 872, 961},
             129: {165, 349, 357, 360, 456, 647, 655, 713, 913, 925},
             130: {239, 241, 477, 521, 537, 549, 698, 728, 977, 985},
             131: {60, 167, 266, 357, 408, 706, 788, 906, 913, 976},
             132: {44, 81, 160, 334, 442, 515, 540, 698, 864, 985},
             133: {44, 52, 160, 166, 273, 442, 778, 862, 909, 961},
             134: {60, 130, 251, 381, 417, 440, 454, 537, 857, 976},
             135: {263, 360, 432, 452, 520, 521, 550, 666, 854, 962},
             136: {44, 60, 146, 273, 334, 383, 408, 515, 591, 864},
             137: {44, 78, 106, 273, 371, 383, 637, 738, 749, 1015},
             138: {60, 440, 909, 976, 1026},
             139: {44, 78, 273, 334, 383, 540, 570},
             140: {24, 39, 125, 199, 249, 449, 462, 574, 599, 966},
             141: {61, 234, 239, 258, 451, 470, 493, 507, 705, 977},
             142: {44, 81, 160, 454, 515, 570, 637, 698, 864, 909},
             143: {279, 371, 408, 591, 637, 655, 765, 800, 890, 991},
             144: {166, 357, 407, 462, 473, 481, 495, 778, 894, 945},
             145: {162, 192, 426, 441, 624, 671, 672, 738, 852, 878},
             146: {33, 147, 212, 236, 272, 387, 688, 733, 762, 934},
             147: {41, 242, 307, 387, 419, 566, 650, 675, 733, 850},
             148: {60, 100, 170, 334, 442, 540, 637, 738, 958, 1010},
             149: {44, 97, 185, 454, 596, 649, 849, 864, 909, 1024},
             150: {60, 160, 189, 288, 408, 440, 454, 572, 596, 849},
             151: {60, 135, 172, 208, 371, 411, 527, 615, 749, 1015},
             152: {96, 451, 573, 706, 732, 749, 849, 906, 934, 983},
             153: {76, 100, 387, 388, 563, 717, 719, 780, 909, 989},
             154: {208, 299, 408, 442, 570, 800, 991},
             155: {60, 229, 408, 440, 442, 600, 703, 747, 879, 909},
             156: {165, 172, 208, 411, 454, 703, 749, 909, 919, 945},
             157: {61, 408, 411, 440, 945, 1010},
             158: {60, 78, 408, 440, 454, 637, 703, 778, 852},
             159: {113, 170, 266, 388, 563, 655, 749, 909, 1010, 1015},
             160: {19, 164, 212, 263, 289, 326, 429, 682, 809, 837},
             161: {3, 130, 241, 362, 394, 451, 521, 676, 762, 805},
             162: {186, 236, 266, 422, 471, 575, 738, 791, 820, 967},
             163: {44, 160, 478, 515, 572, 637, 765, 864, 879, 890},
             164: {289, 328, 377, 431, 493, 527, 800, 809, 1000, 1026},
             165: {61, 130, 360, 364, 377, 380, 580, 605, 919, 1011},
             166: {190, 205, 449, 481, 515, 778, 894, 930, 945, 966},
             167: {26, 234, 553, 575, 670, 808, 810, 861, 967, 1020},
             168: {239, 446, 451, 559, 762, 788, 791, 824, 858, 977},
             169: {100, 334, 442, 540, 732, 958},
             170: {126, 299, 379, 389, 446, 449, 514, 599, 858, 925},
             171: {60, 442},
             172: {3, 26, 262, 307, 463, 647, 706, 906, 967, 1004},
             173: {239, 241, 284, 309, 477, 502, 549, 559, 727, 762},
             174: {141, 234, 239, 258, 394, 470, 493, 580, 666, 1010},
             175: {41, 147, 189, 492, 535, 785, 850, 977, 983, 1012},
             176: {44, 160, 170, 442, 637, 655, 738, 864, 909, 1010},
             177: {106, 113, 266, 289, 328, 433, 442, 655, 809, 1008},
             178: {106, 167, 266, 357, 418, 635, 713, 913, 956, 998},
             179: {112, 236, 299, 334, 336, 796, 800, 872, 879, 991},
             180: {44, 81, 160, 299, 408, 442, 515, 800, 864, 991},
             181: {2, 135, 205, 289, 360, 425, 613, 703, 869, 994},
             182: {141, 299, 408, 440, 454, 749, 800, 945, 991},
             183: {49, 103, 117, 333, 363, 527, 614, 728, 791, 831},
             184: {334, 440, 540, 909},
             185: {34, 275, 339, 389, 583, 782, 849, 865, 922, 961},
             186: {76, 269, 358, 374, 647, 714, 728, 871, 912, 1013},
             187: {100, 113, 172, 266, 388, 425, 563, 582, 637, 909},
             188: {60, 387, 425, 563, 582, 591, 637, 652, 909, 1015},
             189: {21, 61, 175, 205, 391, 535, 785, 916, 955, 1013},
             190: {39, 140, 199, 273, 449, 515, 516, 894, 945, 966},
             191: {113, 165, 266, 388, 411, 563, 637, 865, 909, 1010},
             192: {21, 389, 430, 458, 565, 574, 615, 672, 694, 973},
             193: {164, 328, 418, 422, 429, 541, 648, 895, 991, 998},
             194: {117, 224, 364, 614, 637, 652, 670, 774, 864, 976},
             195: {72, 164, 266, 349, 397, 440, 469, 470, 591, 613},
             196: {33, 74, 224, 273, 336, 440, 596, 857, 945, 961},
             197: {44, 160, 258, 358, 455, 649, 737, 778, 871, 909},
             198: {872, 909},
             199: {39, 125, 140, 249, 342, 462, 473, 481, 516, 966},
             200: {44, 146, 160, 266, 279, 408, 515, 570, 591, 864},
             201: {24, 61, 237, 389, 446, 449, 478, 615, 885, 922},
             202: {49, 105, 112, 165, 492, 636, 681, 749, 919, 945},
             203: {78, 160, 217, 440, 792, 837, 861, 871, 956, 989},
             204: {370, 371, 418, 422, 455, 470, 541, 563, 648, 998},
             205: {135, 233, 345, 380, 470, 550, 553, 670, 819, 1020},
             206: {97, 213, 434, 440, 572, 583, 765, 824, 849, 890},
             207: {100, 170, 408, 411, 554, 637, 738, 958, 976, 1010},
             208: {161, 315, 394, 411, 580, 670, 749, 788, 906, 1011},
             209: {113, 126, 205, 360, 422, 449, 493, 681, 703, 1000},
             210: {100, 591, 958, 976},
             211: {44, 60, 160, 299, 515, 637, 800, 864, 909, 991},
             212: {76, 241, 272, 358, 431, 649, 733, 800, 871, 887},
             213: {370, 438, 455, 473, 765, 878, 885, 890, 895, 930},
             214: {106, 124, 135, 162, 273, 360, 422, 572, 596, 738},
             215: {61, 446, 559, 621, 785, 788, 850, 858, 879, 977},
             216: {141, 266, 279, 408, 570, 749, 854, 1010},
             217: {117, 521, 550, 614, 666, 727, 728, 791, 916, 935},
             218: {60, 160, 208, 336, 408, 440, 454, 591, 637, 909},
             219: {97, 185, 583, 649, 796, 849, 865, 909, 973, 1024},
             220: {113, 266, 388, 425, 563, 637, 738, 865, 1010, 1015},
             221: {60, 61, 408, 440, 454, 637, 738, 749, 852, 1015},
             222: {17, 147, 242, 307, 358, 419, 514, 650, 733, 925},
             223: {217, 371, 454, 615, 637, 738, 872},
             224: {2, 74, 135, 263, 432, 452, 455, 670, 778, 1026},
             225: {103, 349, 362, 364, 452, 455, 653, 791, 831, 967},
             226: {49, 60, 105, 492, 591, 636, 681, 738, 749, 852},
             227: {160, 208, 440, 454},
             228: {44, 175, 258, 273, 397, 426, 456, 541, 705, 871},
             229: {39, 125, 140, 190, 442, 574, 599, 747, 894, 966},
             230: {44, 100, 273, 334, 383, 442, 540, 879, 958, 976},
             231: {1, 44, 266, 371, 408, 442, 591, 717, 864, 991},
             232: {112, 175, 363, 394, 422, 431, 572, 647, 861, 967},
             233: {205, 241, 380, 521, 550, 614, 653, 666, 782, 913},
             234: {141, 241, 272, 394, 553, 705, 762, 871, 887, 977},
             235: {44, 299, 408, 442, 515, 591, 800, 864, 945, 991},
             236: {112, 345, 362, 394, 422, 492, 569, 647, 967, 1004},
             237: {201, 249, 389, 449, 615, 694, 802, 894, 922, 966},
             238: {44, 81, 160, 334, 454, 515, 540, 591, 637, 864},
             239: {130, 241, 352, 394, 451, 470, 559, 762, 805, 887},
             240: {3, 77, 130, 241, 440, 521, 666, 762, 871, 1013},
             241: {234, 239, 352, 387, 477, 559, 727, 762, 887, 977},
             242: {147, 222, 241, 307, 387, 419, 566, 650, 733, 791},
             243: {106, 172, 208, 245, 408, 411, 425, 563, 749, 913},
             244: {146, 208, 440, 732, 738},
             245: {241, 352, 550, 614, 666, 782, 788, 872, 913, 955},
             246: {44, 141, 165, 170, 334, 408, 454, 637, 738, 864},
             247: {44, 201, 229, 540, 712, 778, 802, 879, 909, 943},
             248: {130, 165, 208, 299, 408, 454, 800, 919, 945, 991},
             249: {24, 39, 140, 199, 237, 389, 462, 568, 583, 922},
             250: {113, 175, 363, 481, 624, 648, 649, 800, 861, 998},
             251: {161, 208, 263, 333, 363, 381, 417, 653, 747, 774},
             252: {24, 284, 397, 434, 514, 593, 719, 780, 850, 989},
             253: {279, 371, 408, 570, 655, 765, 800, 865, 890, 991},
             254: {76, 426, 508, 563, 568, 582, 591, 635, 672, 909},
             255: {164, 170, 208, 508, 568, 591, 681, 749, 912, 925},
             256: {119, 162, 201, 237, 323, 440, 478, 689, 849, 894},
             257: {112, 492, 519, 572, 647, 670, 800, 861, 916, 994},
             258: {130, 141, 241, 360, 477, 519, 670, 887, 919, 1015},
             259: {135, 349, 360, 433, 438, 572, 647, 713, 829, 895},
             260: {161, 315, 380, 569, 613, 637, 727, 917, 985, 1011},
             261: {418, 422, 470, 550, 580, 582, 637, 703, 985, 1011},
             262: {20, 172, 345, 433, 456, 463, 575, 647, 738, 1013},
             263: {135, 161, 224, 360, 528, 670, 691, 762, 778, 852},
             264: {345, 380, 408, 469, 534, 854, 879, 991, 1000, 1026},
             265: {20, 26, 96, 431, 463, 604, 791, 796, 850, 962},
             266: {1, 113, 168, 272, 425, 788, 809, 865, 906, 1015},
             267: {1, 168, 266, 495, 575, 591, 744, 808, 869, 1019},
             268: {172, 266, 307, 411, 425, 563, 637, 810, 956, 1015},
             269: {20, 112, 186, 349, 358, 374, 521, 647, 714, 800},
             270: {61, 147, 222, 419, 604, 675, 733, 785, 850, 991},
             271: {60, 172, 208, 266, 408, 411, 655, 934, 956, 976},
             272: {3, 161, 234, 241, 299, 358, 762, 871, 887, 977},
             273: {19, 44, 78, 164, 190, 224, 263, 383, 528, 824},
             274: {258, 266, 388, 637, 749, 872, 976, 1010, 1015, 1020},
             275: {140, 199, 249, 462, 481, 583, 599, 671, 894, 966},
             276: {146, 440, 655, 945},
             277: {44, 160, 334, 440, 454, 515, 570, 596, 778, 864},
             278: {100, 208, 408, 411, 554, 778, 909, 958, 976, 1010},
             279: {362, 431, 456, 471, 570, 647, 738, 810, 832, 861},
             280: {408, 440, 909, 1026},
             281: {60, 105, 236, 279, 456, 647, 655, 738, 861, 1004},
             282: {100, 266, 279, 570, 637, 655, 703, 872, 909, 1010},
             283: {119, 170, 233, 478, 502, 574, 637, 672, 909, 1010},
             284: {34, 166, 173, 240, 339, 446, 694, 792, 913, 945},
             285: {164, 170, 328, 442, 493, 527, 637, 712, 964, 1000},
             286: {165, 279, 371, 442, 655, 765, 890, 919, 945, 991},
             287: {45, 135, 263, 360, 469, 534, 579, 681, 852, 879},
             288: {77, 112, 201, 333, 394, 418, 652, 906, 934, 998},
             289: {2, 49, 164, 168, 333, 419, 493, 613, 809, 1026},
             290: {78, 217, 471, 837},
             291: {44, 146, 160, 326, 440, 441, 442, 591, 738, 879},
             292: {45, 270, 273, 408, 426, 648, 687, 738, 966, 991},
             293: {60, 279, 371, 388, 527, 615, 655, 749, 976, 1010},
             294: {234, 388, 418, 534, 563, 637, 691, 705, 977, 1010},
             295: {76, 167, 192, 408, 430, 434, 442, 852, 879, 991},
             296: {205, 397, 605, 613, 676, 703, 906, 916, 994, 1015},
             297: {44, 52, 189, 273, 288, 311, 383, 391, 471, 909},
             298: {44, 175, 408, 442, 481, 624, 649, 800, 861, 998},
             299: {19, 123, 272, 514, 535, 573, 650, 850, 955, 1012},
             300: {160, 279, 299, 360, 408, 655, 800, 945, 983, 991},

In [34]:
import pickle
# Organize the variables into a tuple in the desired order
data_to_save = (history_u_lists, history_ur_lists, history_v_lists, history_vr_lists,
                train_u, train_v, train_r, test_u, test_v, test_r, social_adj_lists, ratings_list)

# Specify the path to save the pickle file
output_pickle_file_path = "/home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/processed-files/D1_Trust_Neighbor_Update_0.6_threshold.pickle"

# Open the pickle file in write binary mode ('wb')
with open(output_pickle_file_path, 'wb') as file:
    # Dump the data to the pickle file
    pickle.dump(data_to_save, file)

print("Data saved to pickle file:", output_pickle_file_path)

Data saved to pickle file: /home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/processed-files/D1_Trust_Neighbor_Update_0.6_threshold.pickle

## Training

In [37]:
import torch
import torch.nn as nn
import pickle
import numpy as np
import argparse
import os
from UV_Encoders import UV_Encoder
from UV_Aggregators import UV_Aggregator
from Social_Encoders import Social_Encoder
from Social_Aggregators import Social_Aggregator


class GraphRec(nn.Module):
    def __init__(self, enc_u, enc_v_history, r2e):
        super(GraphRec, self).__init__()
        self.enc_u = enc_u
        self.enc_v_history = enc_v_history
        self.embed_dim = enc_u.embed_dim
        self.w_ur1 = nn.Linear(self.embed_dim, self.embed_dim)
        self.w_ur2 = nn.Linear(self.embed_dim, self.embed_dim)
        self.w_vr1 = nn.Linear(self.embed_dim, self.embed_dim)
        self.w_vr2 = nn.Linear(self.embed_dim, self.embed_dim)
        self.w_uv1 = nn.Linear(self.embed_dim * 2, self.embed_dim)
        self.w_uv2 = nn.Linear(self.embed_dim, 16)
        self.w_uv3 = nn.Linear(16, 1)
        self.r2e = r2e
        self.bn1 = nn.BatchNorm1d(self.embed_dim, momentum=0.5)
        self.bn2 = nn.BatchNorm1d(self.embed_dim, momentum=0.5)
        self.bn3 = nn.BatchNorm1d(self.embed_dim, momentum=0.5)
        self.bn4 = nn.BatchNorm1d(16, momentum=0.5)

    def forward(self, nodes_u, nodes_v):
        embeds_u = self.enc_u(nodes_u)
        embeds_v = self.enc_v_history(nodes_v)
        scores_u = torch.matmul(embeds_u, embeds_v.t())
        return scores_u.squeeze()

    def bpr_loss(self, nodes_u, nodes_v, device, num_items):
        scores_u = self.forward(nodes_u, nodes_v)
        nodes_v_negative = torch.randint(0, num_items, size=nodes_u.size(), dtype=torch.long).to(device)
        scores_u_negative = self.forward(nodes_u, nodes_v_negative)
        bpr_loss = -torch.log(torch.sigmoid(scores_u - scores_u_negative)).mean()
        return bpr_loss

def train(model, device, train_loader, optimizer, epoch, num_items):
    model.train()
    running_loss = 0.0
    for i, data in enumerate(train_loader, 0):
        batch_nodes_u, batch_nodes_v, _ = data
        optimizer.zero_grad()
        loss = model.bpr_loss(batch_nodes_u.to(device), batch_nodes_v.to(device), device, num_items)
        loss.backward(retain_graph=True)
        optimizer.step()
        running_loss += loss.item()
        if i % 100 == 0:
            print('[%d, %5d] loss: %.3f' % (epoch, i, running_loss / 100))
            running_loss = 0.0

def get_top_100_recommendations(model, device, test_loader, num_items, k=100):
    model.eval()
    user_recommendations_dict = {}  # Dictionary to store user recommendations

    with torch.no_grad():
        for test_u, test_v, _ in test_loader:
            test_u, test_v = test_u.to(device), test_v.to(device)
            scores = model.forward(test_u, test_v)
            scores = scores.squeeze().tolist()
            top_indices = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:k]

            user_ids = test_u.tolist()  # Convert tensor to list

            for user_id in user_ids:
                user_recommendations = [(rank, test_v[item_index].item()) for rank, item_index in enumerate(top_indices, start=1)]
                user_recommendations_dict[user_id] = user_recommendations

    return user_recommendations_dict




def main():
    parser = argparse.ArgumentParser(description='Social Recommendation: GraphRec model')
    parser.add_argument('--batch_size', type=int, default=128, metavar='N', help='input batch size for training')
    parser.add_argument('--embed_dim', type=int, default=64, metavar='N', help='embedding size')
    parser.add_argument('--lr', type=float, default=0.001, metavar='LR', help='learning rate')
    parser.add_argument('--test_batch_size', type=int, default=1000, metavar='N', help='input batch size for testing')
    parser.add_argument('--epochs', type=int, default=100, metavar='N', help='number of epochs to train')
    args, unknown = parser.parse_known_args()

    os.environ['CUDA_VISIBLE_DEVICES'] = '0'
    use_cuda = False
    if torch.cuda.is_available():
        use_cuda = True
    device = torch.device("cuda" if use_cuda else "cpu")

    embed_dim = args.embed_dim
    dir_data = '/home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/processed-files/D1_Trust_Neighbor_Update_0.6_threshold'

    path_data = dir_data + ".pickle"
    data_file = open(path_data, 'rb')
    history_u_lists, history_ur_lists, history_v_lists, history_vr_lists, train_u, train_v, train_r, test_u, test_v, test_r, social_adj_lists, ratings_list = pickle.load(
        data_file)
    total_num_items = len(set(train_v + test_v))

    trainset = torch.utils.data.TensorDataset(torch.LongTensor(train_u), torch.LongTensor(train_v),
                                              torch.FloatTensor(train_r))
    testset = torch.utils.data.TensorDataset(torch.LongTensor(test_u), torch.LongTensor(test_v),
                                             torch.FloatTensor(test_r))
    train_loader = torch.utils.data.DataLoader(trainset, batch_size=args.batch_size, shuffle=True)
    test_loader = torch.utils.data.DataLoader(testset, batch_size=args.test_batch_size, shuffle=True)
    num_users = history_u_lists.__len__()
    num_items = history_v_lists.__len__()

    u2e = nn.Embedding(num_users, embed_dim).to(device)
    v2e = nn.Embedding(num_items, embed_dim).to(device)
    r2e = nn.Embedding(total_num_items, embed_dim).to(device)  # Define r2e with the correct number of ratings
    total_num_items = len(set(train_v + test_v))

    agg_u_history = UV_Aggregator(v2e, r2e, u2e, embed_dim, cuda=device, uv=True)
    enc_u_history = UV_Encoder(u2e, embed_dim, history_u_lists, history_ur_lists, agg_u_history, cuda=device, uv=True)
    agg_u_social = Social_Aggregator(lambda nodes: enc_u_history(nodes).t(), u2e, embed_dim, cuda=device)
    enc_u = Social_Encoder(lambda nodes: enc_u_history(nodes).t(), embed_dim, social_adj_lists, agg_u_social,
                           base_model=enc_u_history, cuda=device)

    agg_v_history = UV_Aggregator(v2e, r2e, u2e, embed_dim, cuda=device, uv=False)
    enc_v_history = UV_Encoder(v2e, embed_dim, history_v_lists, history_vr_lists, agg_v_history, cuda=device, uv=False)

    graphrec = GraphRec(enc_u, enc_v_history, r2e).to(device)
    optimizer = torch.optim.RMSprop(graphrec.parameters(), lr=args.lr, alpha=0.9)

    for epoch in range(1, args.epochs + 1):
        train(graphrec, device, train_loader, optimizer, epoch, total_num_items)

    top_100_recommendations = get_top_100_recommendations(graphrec, device, test_loader, num_items=total_num_items)

    # Print or use top_100_recommendations as needed
    return top_100_recommendations

if __name__ == "__main__":
    recommendation_list=main()

[1,     0] loss: 0.007
[1,   100] loss: 0.478
[2,     0] loss: 0.004
[2,   100] loss: 0.421
[3,     0] loss: 0.005
[3,   100] loss: 0.411
[4,     0] loss: 0.005
[4,   100] loss: 0.406
[5,     0] loss: 0.004
[5,   100] loss: 0.406
[6,     0] loss: 0.004
[6,   100] loss: 0.397
[7,     0] loss: 0.004
[7,   100] loss: 0.393
[8,     0] loss: 0.005
[8,   100] loss: 0.400
[9,     0] loss: 0.004
[9,   100] loss: 0.398
[10,     0] loss: 0.004
[10,   100] loss: 0.397
[11,     0] loss: 0.004
[11,   100] loss: 0.401
[12,     0] loss: 0.004
[12,   100] loss: 0.397
[13,     0] loss: 0.004
[13,   100] loss: 0.399
[14,     0] loss: 0.004
[14,   100] loss: 0.399
[15,     0] loss: 0.004
[15,   100] loss: 0.392
[16,     0] loss: 0.005
[16,   100] loss: 0.399
[17,     0] loss: 0.004
[17,   100] loss: 0.394
[18,     0] loss: 0.004
[18,   100] loss: 0.395
[19,     0] loss: 0.004
[19,   100] loss: 0.397
[20,     0] loss: 0.005
[20,   100] loss: 0.394
[21,     0] loss: 0.004
[21,   100] loss: 0.392
[22,     0] loss: 0.004
[22,   100] loss: 0.396
[23,     0] loss: 0.005
[23,   100] loss: 0.394
[24,     0] loss: 0.004
[24,   100] loss: 0.396
[25,     0] loss: 0.004
[25,   100] loss: 0.390
[26,     0] loss: 0.004
[26,   100] loss: 0.392
[27,     0] loss: 0.004
[27,   100] loss: 0.396
[28,     0] loss: 0.004
[28,   100] loss: 0.395
[29,     0] loss: 0.004
[29,   100] loss: 0.383
[30,     0] loss: 0.004
[30,   100] loss: 0.391
[31,     0] loss: 0.005
[31,   100] loss: 0.399
[32,     0] loss: 0.003
[32,   100] loss: 0.396
[33,     0] loss: 0.003
[33,   100] loss: 0.393
[34,     0] loss: 0.004
[34,   100] loss: 0.390
[35,     0] loss: 0.003
[35,   100] loss: 0.390
[36,     0] loss: 0.004
[36,   100] loss: 0.392
[37,     0] loss: 0.003
[37,   100] loss: 0.396
[38,     0] loss: 0.003
[38,   100] loss: 0.391
[39,     0] loss: 0.004
[39,   100] loss: 0.398
[40,     0] loss: 0.004
[40,   100] loss: 0.387
[41,     0] loss: 0.004
[41,   100] loss: 0.398
[42,     0] loss: 0.005
[42,   100] loss: 0.394
[43,     0] loss: 0.004
[43,   100] loss: 0.395
[44,     0] loss: 0.004
[44,   100] loss: 0.395
[45,     0] loss: 0.003
[45,   100] loss: 0.390
[46,     0] loss: 0.005
[46,   100] loss: 0.392
[47,     0] loss: 0.003
[47,   100] loss: 0.394
[48,     0] loss: 0.003
[48,   100] loss: 0.388
[49,     0] loss: 0.004
[49,   100] loss: 0.395
[50,     0] loss: 0.005
[50,   100] loss: 0.390
[51,     0] loss: 0.003
[51,   100] loss: 0.383
[52,     0] loss: 0.004
[52,   100] loss: 0.395
[53,     0] loss: 0.004
[53,   100] loss: 0.390
[54,     0] loss: 0.004
[54,   100] loss: 0.394
[55,     0] loss: 0.003
[55,   100] loss: 0.406
[56,     0] loss: 0.004
[56,   100] loss: 0.387
[57,     0] loss: 0.004
[57,   100] loss: 0.393
[58,     0] loss: 0.004
[58,   100] loss: 0.395
[59,     0] loss: 0.005
[59,   100] loss: 0.398
[60,     0] loss: 0.004
[60,   100] loss: 0.388
[61,     0] loss: 0.004
[61,   100] loss: 0.391
[62,     0] loss: 0.004
[62,   100] loss: 0.384
[63,     0] loss: 0.004
[63,   100] loss: 0.386
[64,     0] loss: 0.005
[64,   100] loss: 0.397
[65,     0] loss: 0.004
[65,   100] loss: 0.396
[66,     0] loss: 0.004
[66,   100] loss: 0.394
[67,     0] loss: 0.004
[67,   100] loss: 0.390
[68,     0] loss: 0.004
[68,   100] loss: 0.389
[69,     0] loss: 0.004
[69,   100] loss: 0.393
[70,     0] loss: 0.003
[70,   100] loss: 0.393
[71,     0] loss: 0.003
[71,   100] loss: 0.388
[72,     0] loss: 0.004
[72,   100] loss: 0.388
[73,     0] loss: 0.004
[73,   100] loss: 0.384
[74,     0] loss: 0.004
[74,   100] loss: 0.399
[75,     0] loss: 0.004
[75,   100] loss: 0.389
[76,     0] loss: 0.004
[76,   100] loss: 0.388
[77,     0] loss: 0.004
[77,   100] loss: 0.383
[78,     0] loss: 0.004
[78,   100] loss: 0.390
[79,     0] loss: 0.003
[79,   100] loss: 0.399
[80,     0] loss: 0.004
[80,   100] loss: 0.386
[81,     0] loss: 0.004
[81,   100] loss: 0.395
[82,     0] loss: 0.003
[82,   100] loss: 0.387
[83,     0] loss: 0.003
[83,   100] loss: 0.388
[84,     0] loss: 0.004
[84,   100] loss: 0.384
[85,     0] loss: 0.004
[85,   100] loss: 0.391
[86,     0] loss: 0.004
[86,   100] loss: 0.393
[87,     0] loss: 0.004
[87,   100] loss: 0.390
[88,     0] loss: 0.004
[88,   100] loss: 0.395
[89,     0] loss: 0.003
[89,   100] loss: 0.384
[90,     0] loss: 0.004
[90,   100] loss: 0.398
[91,     0] loss: 0.004
[91,   100] loss: 0.389
[92,     0] loss: 0.002
[92,   100] loss: 0.385
[93,     0] loss: 0.004
[93,   100] loss: 0.396
[94,     0] loss: 0.004
[94,   100] loss: 0.395
[95,     0] loss: 0.004
[95,   100] loss: 0.384
[96,     0] loss: 0.005
[96,   100] loss: 0.391
[97,     0] loss: 0.004
[97,   100] loss: 0.386
[98,     0] loss: 0.003
[98,   100] loss: 0.384
[99,     0] loss: 0.004
[99,   100] loss: 0.396
[100,     0] loss: 0.003
[100,   100] loss: 0.380

In [38]:
rows = []
for user, rankings in recommendation_list.items():
    for rank, item in rankings:
        rows.append({"user": user, "rank": rank, "item_update": item, "item": item+1})

all_recs = pd.DataFrame(rows)

In [39]:
cold_start_item=[47, 51, 231, 484]

In [40]:
filtered_recs = all_recs[~all_recs['item'].isin(cold_start_item)]
filtered_recs

        user  rank  item_update  item
0        341     1          409   410
1        341     2          455   456
2        341     3          531   532
3        341     4          359   360
4        341     5          262   263
...      ...   ...          ...   ...
100836  1021    25          318   319
100837  1021    26          116   117
100838  1021    27           69    70
100839  1021    28           28    29
100840  1021    29           69    70

[99841 rows x 4 columns]

In [41]:
filtered_recs['rank'] = filtered_recs['rank'].astype(int)

/tmp/ipykernel_1390737/435666994.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_recs['rank'] = filtered_recs['rank'].astype(int)

In [42]:
filtered_recs['re-rank'] = filtered_recs.groupby('user')['rank'].rank(method='first')
filtered_recs['rank'] = filtered_recs['re-rank'].astype(int)
filtered_recs=filtered_recs.iloc[:,[0,1,2,3]]

/tmp/ipykernel_1390737/347894999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_recs['re-rank'] = filtered_recs.groupby('user')['rank'].rank(method='first')
/tmp/ipykernel_1390737/347894999.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_recs['rank'] = filtered_recs['re-rank'].astype(int)

In [ ]:
# Save filtered_recs to pickle
filtered_recs.to_pickle(f'{PROCESSED_FILE_DIR}/Politifact_filtered_recs_trust_neighbour_0.6_threshold.pickle')

In [43]:
filtered_recs

        user  rank  item_update  item
0        341     1          409   410
1        341     2          455   456
2        341     3          531   532
3        341     4          359   360
4        341     5          262   263
...      ...   ...          ...   ...
100836  1021    25          318   319
100837  1021    26          116   117
100838  1021    27           69    70
100839  1021    28           28    29
100840  1021    29           69    70

[99841 rows x 4 columns]

In [ ]:
# Save filtered_recs to pickle
filtered_recs.to_pickle(f'{PROCESSED_FILE_DIR}/Politifact_filtered_recs_social_intersect_neighbour_0.6_threshold.pickle')

In [ ]:
# Define the different top-k values you want to generate
top_k_values = [5, 10, 15, 20]

# Loop through each k value
for k in top_k_values:
    # Filter for top-k recommendations (excluding user 0)
    MA_gnn_all_recs_top_k = filtered_recs[(filtered_recs['rank'] <= k) & (filtered_recs['user'] != 0)]
    
    # Select only the required columns: user, rank, item
    final_all_recs = MA_gnn_all_recs_top_k.iloc[:, [0, 1, 3]]
    
    # Display the final DataFrame (with only 3 columns)
    print(f"\n{'='*60}")
    print(f"TOP-{k} RECOMMENDATIONS (user, rank, item)")
    print(f"{'='*60}")
    display(final_all_recs)
    
    # Save to CSV with k in the filename
    filename = f'{DATA_FILE_DIR}/Politifact_Trustworthy_Neighbor_Space_0.6_threshold_Updated_top_{k}.csv'
    final_all_recs.to_csv(filename, index=False)
    
    print(f"\n✓ Saved {len(final_all_recs)} recommendations to {filename}")
    print(f"  - Number of users: {final_all_recs['user'].nunique()}")

============================================================
TOP-5 RECOMMENDATIONS (user, rank, item)
============================================================

        user  rank  item
0        341     1   410
1        341     2   456
2        341     3   532
3        341     4   360
4        341     5   263
...      ...   ...   ...
100812  1021     1   489
100813  1021     2   189
100814  1021     3   124
100815  1021     4   522
100816  1021     5     8

[5140 rows x 3 columns]

✓ Saved 5140 recommendations to /home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/data/Politifact_Trustworthy_Neighbor_Space_0.6_threshold_Updated_top_5.csv
  - Number of users: 1028

============================================================
TOP-10 RECOMMENDATIONS (user, rank, item)
============================================================

        user  rank  item
0        341     1   410
1        341     2   456
2        341     3   532
3        341     4   360
4        341     5   263
...      ...   ...   ...
100817  1021     6   272
100818  1021     7   440
100819  1021     8   532
100820  1021     9   348
100821  1021    10   251

[10280 rows x 3 columns]

✓ Saved 10280 recommendations to /home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/data/Politifact_Trustworthy_Neighbor_Space_0.6_threshold_Updated_top_10.csv
  - Number of users: 1028

============================================================
TOP-15 RECOMMENDATIONS (user, rank, item)
============================================================

        user  rank  item
0        341     1   410
1        341     2   456
2        341     3   532
3        341     4   360
4        341     5   263
...      ...   ...   ...
100822  1021    11   189
100823  1021    12   394
100824  1021    13   307
100825  1021    14   356
100826  1021    15   275

[15420 rows x 3 columns]

✓ Saved 15420 recommendations to /home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/data/Politifact_Trustworthy_Neighbor_Space_0.6_threshold_Updated_top_15.csv
  - Number of users: 1028

============================================================
TOP-20 RECOMMENDATIONS (user, rank, item)
============================================================

        user  rank  item
0        341     1   410
1        341     2   456
2        341     3   532
3        341     4   360
4        341     5   263
...      ...   ...   ...
100827  1021    16   440
100828  1021    17   456
100829  1021    18   173
100830  1021    19   532
100831  1021    20   195

[20560 rows x 3 columns]

✓ Saved 20560 recommendations to /home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/data/Politifact_Trustworthy_Neighbor_Space_0.6_threshold_Updated_top_20.csv
  - Number of users: 1028

## Evaluation

In [ ]:
test=pd.read_csv(f"{DATA_FILE_DIR}/politifact_test.csv")

test=test.iloc[:,[1,2,3]]
test.drop(index=1028,inplace=True)
test

      user  item  ratings
0        1   199      0.5
1        2    34      0.5
2        3    51      2.0
3        4   187      0.5
4        5   261      1.0
...    ...   ...      ...
1023  1024   380      1.0
1024  1025   356      0.5
1025  1026   272      1.5
1026  1027   489      0.5
1027  1028   347      0.5

[1028 rows x 3 columns]

In [ ]:
top_k_values = [5, 10, 15, 20]

# Initialize RecListAnalysis
rla = topn.RecListAnalysis()
rla.add_metric(topn.recip_rank)

# Store results
mrr_results = {}

for k in top_k_values:
    # Load the corresponding CSV
    final_all_recs = pd.read_csv(f"{DATA_FILE_DIR}/Politifact_Trustworthy_Neighbor_Space_0.6_threshold_Updated_top_{k}.csv")
    
    # Compute MRR
    results = rla.compute(final_all_recs, test)
    mean_results = results.mean()
    
    # Check what's in the results
    print(f"\nTop-{k} Results:")
    print(mean_results)
    
    mrr_results[k] = mean_results['recip_rank']

# Create summary DataFrame
mrr_summary = pd.DataFrame(list(mrr_results.items()), columns=['Top-K', 'MRR'])
display(mrr_summary)

mrr_summary_path = os.path.join(RESULTS_DIR, 'trust_neighbour_mrr_summary_0.6_threshold.csv')
mrr_summary.to_csv(mrr_summary_path, index=False)

print(f"\n✓ MRR summary saved to {mrr_summary_path}")

Top-5 Results:
nrecs         5.000000
recip_rank    0.047568
dtype: float64

Top-10 Results:
nrecs         10.00000
recip_rank     0.05726
dtype: float64

Top-15 Results:
nrecs         15.000000
recip_rank     0.064972
dtype: float64

Top-20 Results:
nrecs         20.000000
recip_rank     0.067889
dtype: float64

   Top-K       MRR
0      5  0.047568
1     10  0.057260
2     15  0.064972
3     20  0.067889

In [ ]:
# Load the key (only once)
key = pd.read_csv("/home/shoaib/recommender-system/royal/journal-revision/src-v3/Politifact/New/data/politifact_Shu_fake_news_keyforSOCIALMF.csv")
key_news_id = key[["news_id_new","news_label"]].drop_duplicates(subset=["news_id_new"], keep="last").reset_index(drop=True)
key_news_id["fake_real_labels"] = key_news_id["news_label"].apply(lambda x: 0 if x == "fake" else 1)

# Define the MMC function
def mmc(dataframe, top_n):
    """
    Calculates the Misinformation Count (MC) divided by the top-N recommendations for each user.

    Parameters:
    dataframe (DataFrame): DataFrame with columns 'user_id', 'item_id', 'rank', 'news_label'.
    top_n (int): Number of top recommendations to consider.

    Returns:
    float: Mean MC across all users.
    """
    dataframe = dataframe[dataframe['rank'] <= top_n]
    sorted_df = dataframe.sort_values(by=['user', 'rank'])
    misinformation_df = sorted_df[sorted_df['news_label'] == 'fake']
    user_mc = misinformation_df.groupby('user').size().reset_index(name='M_item')
    user_mc['MC'] = user_mc['M_item'] / top_n
    return user_mc['MC'].mean()

# Compute MC for all top-k values
top_k_values = [5, 10, 15, 20]
mc_results = {}

for k in top_k_values:
    # Load the corresponding CSV
    final_all_recs = pd.read_csv(f"{DATA_FILE_DIR}/Politifact_Trustworthy_Neighbor_Space_0.6_threshold_Updated_top_{k}.csv")
    
    # Merge with news labels
    final_recs_mc = pd.merge(final_all_recs, key_news_id, left_on="item", right_on="news_id_new", how='inner')
    
    # Compute MC for this top-k
    mc_score = mmc(final_recs_mc, k)
    mc_results[k] = mc_score
    
    print(f"Top-{k} MC: {mc_score:.4f}")

# Create summary DataFrame
mc_summary = pd.DataFrame(list(mc_results.items()), columns=['Top-K', 'MC'])
display(mc_summary)

# Save the MC summary DataFrame to a CSV file
mc_summary_path = os.path.join(RESULTS_DIR, 'trust_neighbour_mc_summary_0.6_threshold.csv')
mc_summary.to_csv(mc_summary_path, index=False)

print(f"\n✓ MC summary saved to {mc_summary_path}")

Top-5 MC: 0.2000
Top-10 MC: 0.1972
Top-15 MC: 0.2629
Top-20 MC: 0.2986

   Top-K        MC
0      5  0.200000
1     10  0.197179
2     15  0.262905
3     20  0.298589